[tools]
"core:dotnet" = "{{vars.dotnet_version}}"

[tasks.build]
extends = "ffi:preset"
dir = "../.."
run = '''
MaplibreNativeCInstallDir="$MISE_MONOREPO_ROOT/build/$usage_preset/install" \
  dotnet build \
    examples/dotnet-map/Maplibre.NativeFfi.Examples.DotnetMap.csproj \
    -p:Platform="Any CPU"
'''

[tasks.run]
extends = "ffi:example-run"
dir = "../.."
run = '''
MaplibreNativeCInstallDir="$MISE_MONOREPO_ROOT/build/$usage_preset/install" \
  dotnet run \
    --project examples/dotnet-map/Maplibre.NativeFfi.Examples.DotnetMap.csproj \
    -p:Platform="Any CPU" \
    -- "$usage_render_target"
'''
