[tools]
"core:dotnet" = "{{vars.dotnet_version}}"

[tasks.build]
usage = 'arg "[preset]" default="{{vars.host_native_preset}}"'
depends = [{ task = "//:build", args = ["{{usage.preset}}"] }]
dir = "../.."
run = '''
MaplibreNativeCInstallDir="$MISE_MONOREPO_ROOT/build/$usage_preset/install" \
  dotnet build \
    examples/dotnet-map/Maplibre.Native.Examples.DotnetMap.csproj \
    -p:Platform="Any CPU"
'''

[tasks.run]
depends = ["//:build"]
dir = "../.."
usage = '''
arg "[render-target]" default="owned-texture" {
  choices "owned-texture" "borrowed-texture" "native-surface"
}
'''
run = '''
MaplibreNativeCInstallDir="$MISE_MONOREPO_ROOT/build/{{vars.host_native_preset}}/install" \
  dotnet run \
    --project examples/dotnet-map/Maplibre.Native.Examples.DotnetMap.csproj \
    -p:Platform="Any CPU" \
    -- "{{ usage.render_target }}"
'''

[tasks."run:owned-texture"]
run = [{ task = "run", args = ["owned-texture"] }]

[tasks."run:borrowed-texture"]
run = [{ task = "run", args = ["borrowed-texture"] }]

[tasks."run:native-surface"]
run = [{ task = "run", args = ["native-surface"] }]
