[tools]
"core:dotnet" = "{{vars.dotnet_version}}"

[tasks.build]
usage = 'arg "[preset]" default="{{vars.host_native_preset}}"'
depends = [{ task = "//:build", args = ["{{usage.preset}}"] }]
dir = "../.."
run = '''
MaplibreNativeCInstallDir="$MISE_MONOREPO_ROOT/build/$usage_preset/install" \
  dotnet build \
    examples/dotnet-map/Maplibre.NativeFfi.Examples.DotnetMap.csproj \
    -p:Platform="Any CPU"
'''

[tasks.run]
usage = '''
arg "[render-target]" default="owned-texture" {
  choices "owned-texture" "borrowed-texture" "native-surface"
}
flag "--preset <preset>" default="{{vars.host_native_preset}}"
'''
depends = [{ task = ":build", args = ["{{usage.preset}}"] }]
dir = "../.."
run = '''
MaplibreNativeCInstallDir="$MISE_MONOREPO_ROOT/build/$usage_preset/install" \
  dotnet run \
    --project examples/dotnet-map/Maplibre.NativeFfi.Examples.DotnetMap.csproj \
    -p:Platform="Any CPU" \
    -- "$usage_render_target"
'''
