org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true

maplibre.maven.group=org.maplibre.nativeffi
maplibre.maven.version=0.1.0-SNAPSHOT

POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/maplibre/maplibre-native-ffi
POM_LICENSE_NAME=BSD 2-Clause License
POM_LICENSE_URL=https://opensource.org/license/bsd-2-clause
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/maplibre/maplibre-native-ffi
POM_SCM_CONNECTION=scm:git:https://github.com/maplibre/maplibre-native-ffi.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/maplibre/maplibre-native-ffi.git
POM_DEVELOPER_ID=maplibre
POM_DEVELOPER_NAME=MapLibre contributors
POM_DEVELOPER_URL=https://maplibre.org
