[vars]
host_native_preset = "linux-{{ arch() }}-vulkan"

[bootstrap.packages]
"apt:build-essential" = "latest"
"apt:clang" = "latest"
"apt:glslang-tools" = "latest"
"apt:libclang-dev" = "latest"
"apt:libegl1-mesa-dev" = "latest"
"apt:libgles2-mesa-dev" = "latest"
"apt:libicu-dev" = "latest"
"apt:libncurses6" = "latest"
"apt:libsqlite3-0" = "latest"
"apt:libuv1-dev" = "latest"
"apt:libvulkan-dev" = "latest"
"apt:ninja-build" = "latest"
"apt:pkg-config" = "latest"
"apt:zlib1g-dev" = "latest"
"dnf:clang-devel" = "latest"
"dnf:clang" = "latest"
"dnf:gcc" = "latest"
"dnf:gcc-c++" = "latest"
"dnf:glslang" = "latest"
"dnf:libicu-devel" = "latest"
"dnf:libglvnd-devel" = "latest"
"dnf:libstdc++-static" = "latest"
"dnf:libuv-devel" = "latest"
"dnf:libuv-static" = "latest"
"dnf:mesa-libEGL-devel" = "latest"
"dnf:ncurses-libs" = "latest"
"dnf:ninja-build" = "latest"
"dnf:pkgconf-pkg-config" = "latest"
"dnf:sqlite-libs" = "latest"
"dnf:vulkan-loader-devel" = "latest"
"dnf:zlib-ng-compat-devel" = "latest"
"dnf:zlib-ng-compat-static" = "latest"
