[vars]
host_native_preset = "macos-arm64-metal"

[bootstrap.packages]
"brew:cmake" = "latest"
"brew:doxygen" = "latest"
"brew:glslang" = "latest"
"brew:llvm" = "latest"
"brew:molten-vk" = "latest"
"brew:ninja" = "latest"
"brew:pkgconf" = "latest"
"brew:vulkan-loader" = "latest"

[env]
VULKAN_SDK = "/opt/homebrew/opt/vulkan-loader"
