[bootstrap.packages]
"apt:build-essential" = "latest"
"apt:clang" = "latest"
"apt:clang-tidy" = "latest"
"apt:cmake" = "latest"
"apt:doxygen" = "latest"
"apt:glslang-tools" = "latest"
"apt:libclang-dev" = "latest"
"apt:libegl1-mesa-dev" = "latest"
"apt:libgles2-mesa-dev" = "latest"
"apt:libuv1-dev" = "latest"
"apt:libvulkan-dev" = "latest"
"apt:ninja-build" = "latest"
"apt:pkg-config" = "latest"
"apt:zlib1g-dev" = "latest"
"dnf:clang-devel" = "latest"
"dnf:clang" = "latest"
"dnf:clang-tools-extra" = "latest"
"dnf:cmake" = "latest"
"dnf:doxygen" = "latest"
"dnf:gcc" = "latest"
"dnf:gcc-c++" = "latest"
"dnf:glslang" = "latest"
"dnf:libglvnd-devel" = "latest"
"dnf:libuv-devel" = "latest"
"dnf:libuv-static" = "latest"
"dnf:mesa-libEGL-devel" = "latest"
"dnf:ninja-build" = "latest"
"dnf:pkgconf-pkg-config" = "latest"
"dnf:vulkan-loader-devel" = "latest"
"dnf:zlib-ng-compat-devel" = "latest"
"dnf:zlib-ng-compat-static" = "latest"
