[tasks.ci]
run = ["mise run :build"]

[tasks.build]
depends = ["//:ensure-native-library", ":compile-shaders"]
run = "zig build"

[tasks.run]
depends = ["//:ensure-native-library", ":compile-shaders"]
run = "zig build run -- --render-target=owned-texture"

[tasks."run:owned-texture"]
depends = ["//:ensure-native-library", ":compile-shaders"]
run = "zig build run -- --render-target=owned-texture"

[tasks."run:borrowed-texture"]
depends = ["//:ensure-native-library", ":compile-shaders"]
run = "zig build run -- --render-target=borrowed-texture"

[tasks."run:native-surface"]
depends = ["//:ensure-native-library", ":compile-shaders"]
run = "zig build run -- --render-target=native-surface"
