#!/usr/bin/env python3
"""Generate and validate the private raw VAPI from its annotated source."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any


SCRIPT_PATH = Path(__file__).resolve()
REPOSITORY_ROOT = SCRIPT_PATH.parents[3]
DEFAULT_SOURCE = REPOSITORY_ROOT / "bindings/vala/vapi/maplibre-native-c.vapi.in"
DEFAULT_OUTPUT = REPOSITORY_ROOT / "bindings/vala/vapi/maplibre-native-c.vapi"
GENERATED_HEADER = (
    "/* Generated by scripts/generate-raw-vapi.py; "
    "edit vapi/maplibre-native-c.vapi.in. */"
)

NAMED_DECLARATION = re.compile(
    r"((?:\s*\[[^\]]+\]\s*)+)"
    r"public\s+(enum|struct|class)\s+(\w+)"
)
DELEGATE_DECLARATION = re.compile(
    r"((?:\s*\[[^\]]+\]\s*)+)"
    r"public\s+delegate\s+\S+\s+(\w+)"
)
DELEGATE_SIGNATURE = re.compile(
    r"((?:\s*\[[^\]]+\]\s*)+)"
    r"public\s+delegate\s+(.+?)\s+(\w+)\s*\((.*?)\)\s*;",
    re.DOTALL,
)
FUNCTION_DECLARATION = re.compile(
    r'\[CCode \(cname = "(mln_[^"]+)"\)\]\s*'
    r"public static\s+([^;]+);"
)
STRUCT_DECLARATION = re.compile(
    r"((?:\s*\[[^\]]+\]\s*)*)"
    r"public struct\s+(\w+)(?:\s*:\s*([^\s{]+))?\s*"
    r"\{(.*?)\n    \}",
    re.DOTALL,
)
STRUCT_FIELD = re.compile(
    r'(?:\[CCode \([^\]]*?cname = "([^"]+)"[^\]]*?\)\]\s*)?'
    r"public\s+(.+?)\s+(\w+)\s*;"
)
ENUM_DECLARATION = re.compile(
    r"((?:\s*\[[^\]]+\]\s*)+)"
    r"public enum\s+\w+\s*\{(.*?)\n    \}",
    re.DOTALL,
)
PRIMITIVE_C_TYPES = {
    "CBool": "bool",
    "bool": "bool",
    "char": "char",
    "double": "double",
    "float": "float",
    "int32": "int32_t",
    "int64": "int64_t",
    "size_t": "size_t",
    "uint8": "uint8_t",
    "uint32": "uint32_t",
    "uint64": "uint64_t",
    "void": "void",
}


def c_name(attributes: str) -> str | None:
    names = re.findall(r'cname = "(mln_[^"]+)"', attributes)
    return names[-1] if names else None


def named_c_types(source: str) -> dict[str, tuple[str, str]]:
    types: dict[str, tuple[str, str]] = {}
    for match in NAMED_DECLARATION.finditer(source):
        attributes, declaration_kind, vala_name = match.groups()
        name = c_name(attributes)
        if name is not None:
            types[vala_name] = (name, declaration_kind)
    for match in DELEGATE_DECLARATION.finditer(source):
        attributes, vala_name = match.groups()
        name = c_name(attributes)
        if name is not None:
            types[vala_name] = (name, "delegate")
    return types


def vala_type_to_c(
    vala_type: str,
    types: dict[str, tuple[str, str]],
) -> str:
    vala_type = vala_type.strip()
    if vala_type.endswith("?"):
        vala_type = vala_type[:-1]
    if vala_type in {"string", "unowned string"}:
        return "const char *"

    pointer_suffix = ""
    while vala_type.endswith("*"):
        pointer_suffix += " *"
        vala_type = vala_type[:-1].strip()

    if vala_type in PRIMITIVE_C_TYPES:
        base_type = PRIMITIVE_C_TYPES[vala_type]
    elif vala_type in types:
        base_type, declaration_kind = types[vala_type]
        if declaration_kind == "class":
            base_type += " *"
    else:
        raise SystemExit(f"unsupported raw VAPI type: {vala_type}")
    return base_type + pointer_suffix


def normalize_c_type(c_type: str) -> str:
    # Vala has no pointee-const spelling in a VAPI declaration. Const does not
    # change the ABI shape, so compare the return type, parameter order, named
    # types, and pointer depth after removing it.
    c_type = re.sub(r"\bconst\b", "", c_type)
    c_type = c_type.replace("(void)", "()")
    c_type = re.sub(r"\s+", " ", c_type)
    c_type = re.sub(r"\s*\*\s*", "*", c_type)
    c_type = re.sub(r"\s*,\s*", ", ", c_type)
    c_type = re.sub(r"\(\s+", "(", c_type)
    return c_type.strip()


def vapi_function_signatures(
    source: str,
    types: dict[str, tuple[str, str]],
) -> dict[str, str]:
    signatures: dict[str, str] = {}
    for match in FUNCTION_DECLARATION.finditer(source):
        function_name, declaration = match.groups()
        parts = re.fullmatch(
            r"(.+?)\s+\w+\s*\((.*)\)",
            declaration.strip(),
            re.DOTALL,
        )
        if parts is None:
            raise SystemExit(
                f"cannot parse raw VAPI function declaration for {function_name}"
            )
        return_type = vala_type_to_c(parts.group(1), types)
        parameters: list[str] = []
        parameter_text = parts.group(2).strip()
        if parameter_text:
            for parameter in parameter_text.split(","):
                parameter = re.sub(
                    r"^\[CCode \([^\]]+\)\]\s*",
                    "",
                    parameter.strip(),
                )
                parameter_parts = re.fullmatch(
                    r"(?:(out|ref)\s+)?(.+?)\s+\w+",
                    parameter,
                )
                if parameter_parts is None:
                    raise SystemExit(
                        "cannot parse raw VAPI parameter for "
                        f"{function_name}: {parameter.strip()}"
                    )
                direction, vala_type = parameter_parts.groups()
                c_type = vala_type_to_c(vala_type, types)
                if direction in {"out", "ref"}:
                    c_type += " *"
                parameters.append(c_type)
        signatures[function_name] = normalize_c_type(
            f"{return_type} ({', '.join(parameters)})"
        )
    return signatures


def vapi_delegate_signatures(
    source: str,
    types: dict[str, tuple[str, str]],
) -> dict[str, str]:
    signatures: dict[str, str] = {}
    for match in DELEGATE_SIGNATURE.finditer(source):
        attributes, return_type, _, parameter_text = match.groups()
        delegate_name = c_name(attributes)
        if delegate_name is None:
            continue
        parameters: list[str] = []
        if parameter_text.strip():
            for parameter in parameter_text.split(","):
                parameter = re.sub(
                    r"^\[CCode \([^\]]+\)\]\s*",
                    "",
                    parameter.strip(),
                )
                parameter_parts = re.fullmatch(
                    r"(?:(out|ref)\s+)?(.+?)\s+\w+",
                    parameter,
                )
                if parameter_parts is None:
                    raise SystemExit(
                        "cannot parse raw VAPI delegate parameter for "
                        f"{delegate_name}: {parameter.strip()}"
                    )
                direction, vala_type = parameter_parts.groups()
                c_type = vala_type_to_c(vala_type, types)
                if direction in {"out", "ref"}:
                    c_type += " *"
                parameters.append(c_type)
        signatures[delegate_name] = normalize_c_type(
            f"{vala_type_to_c(return_type, types)} ({', '.join(parameters)})"
        )
    return signatures


def vapi_struct_layouts(
    source: str,
    types: dict[str, tuple[str, str]],
) -> dict[str, list[tuple[str, str]]]:
    layouts: dict[str, list[tuple[str, str]]] = {}
    for match in STRUCT_DECLARATION.finditer(source):
        attributes, _, underlying_type, body = match.groups()
        struct_name = c_name(attributes)
        if struct_name is None or underlying_type is not None:
            continue
        fields: list[tuple[str, str]] = []
        for field in STRUCT_FIELD.finditer(body):
            field_c_name, vala_type, field_name = field.groups()
            fields.append(
                (
                    field_c_name or field_name,
                    normalize_c_type(vala_type_to_c(vala_type, types)),
                )
            )
        if fields:
            layouts[struct_name] = fields
    return layouts


def vapi_enum_constants(source: str) -> dict[str, set[str]]:
    constants: dict[str, set[str]] = {}
    for attributes, body in ENUM_DECLARATION.findall(source):
        enum_name = c_name(attributes)
        prefix_match = re.search(r'cprefix = "([^"]+)"', attributes)
        if enum_name is None or prefix_match is None:
            continue
        members = {
            prefix_match.group(1) + member
            for member in re.findall(
                r"^\s*([A-Z][A-Z0-9_]*)\s*,?\s*$", body, re.MULTILINE
            )
        }
        if members:
            constants[enum_name] = members
    return constants


def run_clang_ast() -> dict[str, Any]:
    path_entries = [
        entry
        for entry in os.environ.get("PATH", os.defpath).split(os.pathsep)
        if "mise/shims" not in entry.replace("\\", "/")
        and "ccache" not in entry.replace("\\", "/")
    ]
    clang = shutil.which("clang", path=os.pathsep.join(path_entries))
    if clang is None:
        raise SystemExit(
            "clang is required to validate raw VAPI signatures and layouts"
        )
    result = subprocess.run(
        [
            clang,
            "-std=c23",
            f"-I{REPOSITORY_ROOT / 'include'}",
            "-Xclang",
            "-ast-dump=json",
            "-fsyntax-only",
            str(REPOSITORY_ROOT / "include/maplibre_native_c.h"),
        ],
        check=False,
        capture_output=True,
        env={**os.environ, "PATH": os.pathsep.join(path_entries)},
        text=True,
    )
    if result.returncode != 0:
        raise SystemExit(
            "clang failed to parse the public C headers:\n" + result.stderr
        )
    return json.loads(result.stdout)


def walk_ast(node: Any):
    if isinstance(node, dict):
        yield node
        for value in node.values():
            yield from walk_ast(value)
    elif isinstance(node, list):
        for value in node:
            yield from walk_ast(value)


def clang_function_signatures(ast: dict[str, Any]) -> dict[str, str]:
    return {
        node["name"]: normalize_c_type(node["type"]["qualType"])
        for node in walk_ast(ast)
        if node.get("kind") == "FunctionDecl"
        and node.get("name", "").startswith("mln_")
    }


def flatten_record_fields(
    record: dict[str, Any],
    prefix: str = "",
) -> list[tuple[str, str]]:
    children = record.get("inner", [])
    fields: list[tuple[str, str]] = []
    previous_anonymous_record: dict[str, Any] | None = None
    for child in children:
        if child.get("kind") == "RecordDecl" and child.get("name") is None:
            previous_anonymous_record = child
            continue
        if child.get("kind") != "FieldDecl" or "name" not in child:
            continue
        field_name = child["name"]
        field_type = child["type"]["qualType"]
        if previous_anonymous_record is not None and "unnamed union at" in field_type:
            fields.extend(
                flatten_record_fields(
                    previous_anonymous_record,
                    prefix=f"{prefix}{field_name}.",
                )
            )
        else:
            fields.append(
                (
                    f"{prefix}{field_name}",
                    normalize_c_type(field_type),
                )
            )
        previous_anonymous_record = None
    return fields


def clang_struct_layouts(
    ast: dict[str, Any],
    expected_names: set[str],
) -> dict[str, list[tuple[str, str]]]:
    return {
        node["name"]: flatten_record_fields(node)
        for node in walk_ast(ast)
        if node.get("kind") == "RecordDecl"
        and node.get("completeDefinition") is True
        and node.get("name") in expected_names
    }


def clang_enum_constants(
    ast: dict[str, Any], expected_names: set[str]
) -> dict[str, set[str]]:
    constants: dict[str, set[str]] = {}
    for node in walk_ast(ast):
        if node.get("kind") != "EnumDecl" or node.get("name") not in expected_names:
            continue
        members = {
            child["name"]
            for child in node.get("inner", [])
            if child.get("kind") == "EnumConstantDecl"
        }
        if members:
            constants[node["name"]] = members
    return constants


def compare_declarations(source: str) -> None:
    types = named_c_types(source)
    expected_functions = vapi_function_signatures(source, types)
    expected_delegates = vapi_delegate_signatures(source, types)
    expected_structs = vapi_struct_layouts(source, types)
    expected_enums = vapi_enum_constants(source)
    ast = run_clang_ast()
    actual_functions = clang_function_signatures(ast)
    actual_delegates = {
        node["name"]: normalize_c_type(
            re.sub(r"\(\s*\*\s*\)", "", node["type"]["qualType"], count=1)
        )
        for node in walk_ast(ast)
        if node.get("kind") == "TypedefDecl" and node.get("name") in expected_delegates
    }
    actual_structs = clang_struct_layouts(ast, set(expected_structs))
    actual_enums = clang_enum_constants(ast, set(expected_enums))

    differences: list[str] = []
    for name, signature in sorted(expected_functions.items()):
        actual = actual_functions.get(name)
        if actual != signature:
            differences.append(f"{name}: VAPI {signature!r}, C header {actual!r}")
    for name, signature in sorted(expected_delegates.items()):
        actual = actual_delegates.get(name)
        if actual != signature:
            differences.append(f"{name}: VAPI {signature!r}, C header {actual!r}")
    for name, layout in sorted(expected_structs.items()):
        actual = actual_structs.get(name)
        if actual != layout:
            differences.append(
                f"{name}: VAPI fields {layout!r}, C header fields {actual!r}"
            )
    for name, constants in sorted(expected_enums.items()):
        actual = actual_enums.get(name)
        if actual != constants:
            differences.append(
                f"{name}: VAPI constants {sorted(constants)!r}, "
                f"C header constants {sorted(actual) if actual is not None else None!r}"
            )
    if differences:
        raise SystemExit(
            "raw VAPI signatures or layouts differ from the C headers:\n"
            + "\n".join(differences)
        )


def public_c_functions(headers: str) -> set[str]:
    functions: set[str] = set()
    for declaration in re.findall(r"\bMLN_API\b([^;]+);", headers, re.DOTALL):
        match = re.search(r"\b(mln_[A-Za-z0-9_]+)\s*\(", declaration)
        if match:
            functions.add(match.group(1))
    return functions


def vapi_functions(source: str) -> set[str]:
    return set(
        re.findall(
            r'\[CCode \(cname = "(mln_[^"]+)"\)\]\s*public static',
            source,
        )
    )


def validate_source(source: str) -> None:
    header_text = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted((REPOSITORY_ROOT / "include").rglob("*.h"))
        if path.name != "callback_adapter.h"
    )
    c_functions = public_c_functions(header_text)
    declared_functions = vapi_functions(source)
    missing = sorted(c_functions - declared_functions)
    extra = sorted(declared_functions - c_functions)
    if missing or extra:
        details = []
        if missing:
            details.append("missing C functions: " + ", ".join(missing))
        if extra:
            details.append("unknown C functions: " + ", ".join(extra))
        raise SystemExit(
            "raw VAPI function surface differs from the C headers; "
            + "; ".join(details)
        )

    c_names = set(re.findall(r'cname = "(mln_[A-Za-z0-9_]+)"', source))
    unknown_names = sorted(name for name in c_names if name not in header_text)
    if unknown_names:
        raise SystemExit(
            "raw VAPI names absent from the C headers: " + ", ".join(unknown_names)
        )
    compare_declarations(source)


def generate(source_path: Path, output_path: Path) -> None:
    source = source_path.read_text(encoding="utf-8")
    validate_source(source)
    lines = source.splitlines()
    if not lines:
        raise SystemExit("raw VAPI annotated source is empty")
    lines[0] = GENERATED_HEADER
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8", newline="\n") as output:
        output.write("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    arguments = parser.parse_args()
    generate(arguments.source.resolve(), arguments.output.resolve())


if __name__ == "__main__":
    main()
