#!/usr/bin/env python3
"""Generate and validate the private raw VAPI from its annotated source."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


SCRIPT_PATH = Path(__file__).resolve()
REPOSITORY_ROOT = SCRIPT_PATH.parents[3]
DEFAULT_SOURCE = REPOSITORY_ROOT / "bindings/vala/vapi/maplibre-native-c.vapi.in"
DEFAULT_OUTPUT = REPOSITORY_ROOT / "bindings/vala/vapi/maplibre-native-c.vapi"
GENERATED_HEADER = (
    "/* Generated by scripts/generate-raw-vapi.py; "
    "edit vapi/maplibre-native-c.vapi.in. */"
)


def public_c_functions(headers: str) -> set[str]:
    functions: set[str] = set()
    for declaration in re.findall(r"\bMLN_API\b([^;]+);", headers, re.DOTALL):
        match = re.search(r"\b(mln_[A-Za-z0-9_]+)\s*\(", declaration)
        if match:
            functions.add(match.group(1))
    return functions


def vapi_functions(source: str) -> set[str]:
    return set(
        re.findall(
            r'\[CCode \(cname = "(mln_[^"]+)"\)\]\s*public static',
            source,
        )
    )


def validate_source(source: str) -> None:
    header_text = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted((REPOSITORY_ROOT / "include").rglob("*.h"))
    )
    c_functions = public_c_functions(header_text)
    declared_functions = vapi_functions(source)
    missing = sorted(c_functions - declared_functions)
    extra = sorted(declared_functions - c_functions)
    if missing or extra:
        details = []
        if missing:
            details.append("missing C functions: " + ", ".join(missing))
        if extra:
            details.append("unknown C functions: " + ", ".join(extra))
        raise SystemExit(
            "raw VAPI function surface differs from the C headers; "
            + "; ".join(details)
        )

    c_names = set(re.findall(r'cname = "(mln_[A-Za-z0-9_]+)"', source))
    unknown_names = sorted(name for name in c_names if name not in header_text)
    if unknown_names:
        raise SystemExit(
            "raw VAPI names absent from the C headers: " + ", ".join(unknown_names)
        )


def generate(source_path: Path, output_path: Path) -> None:
    source = source_path.read_text(encoding="utf-8")
    validate_source(source)
    lines = source.splitlines()
    if not lines:
        raise SystemExit("raw VAPI annotated source is empty")
    lines[0] = GENERATED_HEADER
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    arguments = parser.parse_args()
    generate(arguments.source.resolve(), arguments.output.resolve())


if __name__ == "__main__":
    main()
