// Unity glue for the native suites: the entry point, the case runner behind
// RUN_TEST, and the per-case reclaim that keeps one failure from cascading.

#include <stdatomic.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "harness.h"

#include "support/test_support.h"
#include "unity.h"

// Defined by Unity's command-line support, which declares it only in unity.c.
extern char* UnityOptionIncludeNamed;

typedef struct mln_test_group_entry {
  void (*run)(void);
  const char* file;
} mln_test_group_entry;

#define MLN_TEST_REGISTRY_ENTRY(symbol, path) void symbol(void);
#include "mln_native_test_registry.inc"
#undef MLN_TEST_REGISTRY_ENTRY

// Generated by CMake from the globbed test files, in domain order with plugin
// groups last, since a plugin registration lasts for the rest of the process.
static const mln_test_group_entry groups[] = {
#define MLN_TEST_REGISTRY_ENTRY(symbol, path) {symbol, path},
#include "mln_native_test_registry.inc"
#undef MLN_TEST_REGISTRY_ENTRY
};

static bool listing;
static size_t selected_cases;

// Library threads read the scale too, from waits inside provider and transform
// callbacks, so the cache is atomic. Every reader computes the same value.
uint32_t mln_test_timeout_scale(void) {
  static atomic_uint scale;
  unsigned int cached = atomic_load_explicit(&scale, memory_order_relaxed);
  if (cached == 0) {
    const char* value = getenv("MLN_TEST_TIMEOUT_SCALE");
    const long parsed = value == NULL ? 0 : strtol(value, NULL, 10);
    cached = parsed > 0 && parsed <= 100 ? (unsigned int)parsed : 1U;
    atomic_store_explicit(&scale, cached, memory_order_relaxed);
  }
  return cached;
}

void setUp(void) {}

// Unity runs this even after a test body aborts on a failing assertion, so
// reclaiming leaked handles here keeps one failure from cascading into every
// later test that needs a runtime on this thread.
void tearDown(void) {
  if (!mln_test_reclaim_thread_resources()) {
    return;
  }
  if (!Unity.CurrentTestFailed && !Unity.CurrentTestIgnored) {
    TEST_FAIL_MESSAGE(
      "Test finished with live handles; the suite reclaimed them. Destroy the "
      "render session, map, and runtime the test created."
    );
  }
}

void mln_test_run_case(UnityTestFunction func, const char* name, int line) {
  Unity.CurrentTestName = name;
  Unity.CurrentTestLineNumber = (UNITY_LINE_TYPE)line;
  if (!UnityTestMatches()) {
    return;
  }
  selected_cases += 1;
  if (listing) {
    UnityPrint(Unity.TestFile);
    UNITY_OUTPUT_CHAR(':');
    UnityPrint(name);
    UNITY_PRINT_EOL();
    return;
  }

  // Unity's default runner, which defining RUN_TEST compiles out, plus the
  // watchdog around the case.
  Unity.NumberOfTests++;
  UNITY_CLR_DETAILS();
  mln_test_watchdog_arm(Unity.TestFile, name);
  UNITY_EXEC_TIME_START();
  if (TEST_PROTECT()) {
    setUp();
    func();
  }
  if (TEST_PROTECT()) {
    tearDown();
  }
  UNITY_EXEC_TIME_STOP();
  mln_test_watchdog_disarm();
  UnityConcludeTest();
}

int main(int argc, char** argv) {
  const int parsed = UnityParseOptions(argc, argv);
  if (parsed > 0) {
    return parsed;
  }
  listing = parsed < 0;

  UnityBegin("tests/native");
  for (size_t index = 0; index < sizeof(groups) / sizeof(*groups); index += 1) {
    UnitySetTestFile(groups[index].file);
    groups[index].run();
  }
  if (listing) {
    return EXIT_SUCCESS;
  }
  // A CTest entry, shard, or emulator run names its cases by filter, so a
  // filter that matches nothing is a broken registration rather than a pass.
  if (selected_cases == 0 && UnityOptionIncludeNamed != NULL) {
    fprintf(stderr, "no case matches -f %s\n", UnityOptionIncludeNamed);
    return EXIT_FAILURE;
  }
  const int failures = UnityEnd();
  // main() runs on a pthread under -sPROXY_TO_PTHREAD, where a graphics device
  // held past the entry point keeps the runtime alive and the process never
  // exits.
  mln_test_release_thread_gpu_resources();
  return failures;
}
