//! Emitters for the generated raw layer and the normalized C dispatch.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use sha2::{Digest, Sha256};

use crate::model::SlotKind;
use crate::parse::{Parsed, RecordLayout};

pub const BANNER: &str =
    "// Generated by `mise run //bindings/typescript:generate`. Do not edit.\n";
pub const C_BANNER: &str =
    "/* Generated by `mise run //bindings/typescript:generate`. Do not edit. */\n";

/// Everything the fingerprint covers, rendered canonically.
///
/// The facade refuses to call a runtime payload whose fingerprint differs, so
/// this rendering is what decides whether two builds agree about the ABI.
pub fn canonical_schema(native: &Parsed, wasm: &Parsed, header_digest: &str) -> String {
    let mut text = String::new();
    let _ = writeln!(text, "schema 2");
    // The linked library is the third party to this ABI. Slot kinds alone would
    // let two struct types trade places, and a same-named C function whose
    // signature changed would still link, so the concrete C spellings and the
    // header bytes they came from are part of what the handshake compares.
    let _ = writeln!(text, "headers sha256={header_digest}");
    for (index, entrypoint) in native.entrypoints.iter().enumerate() {
        let _ = writeln!(
            text,
            "entrypoint {index} {} -> {} : {}",
            entrypoint.name,
            entrypoint.result_spelling,
            entrypoint.result.as_str()
        );
        for (position, param) in entrypoint.params.iter().enumerate() {
            let _ = writeln!(
                text,
                "  param {position} {} : {}",
                param.spelling,
                param.slot.as_str()
            );
        }
        let _ = writeln!(text, "  symbol {index} {}", entrypoint.name);
    }
    for (abi, parsed) in [("native64", native), ("wasm32", wasm)] {
        for (name, record) in &parsed.records {
            let _ = writeln!(
                text,
                "record {abi} {name} size={} align={} union={}",
                record.size, record.align, record.is_union
            );
            for field in &record.order {
                let (offset, size) = record.fields[field];
                let spelling = record
                    .spellings
                    .get(field)
                    .map(String::as_str)
                    .unwrap_or("?");
                let _ = writeln!(
                    text,
                    "  field {field} : {spelling} offset={offset} size={size}"
                );
            }
        }
    }
    for enumeration in &native.enums {
        let _ = writeln!(text, "enum {}", enumeration.name);
        for (member, value) in &enumeration.members {
            let _ = writeln!(text, "  member {member} = {value}");
        }
    }
    for constant in &native.constants {
        let _ = writeln!(text, "constant {} = {}", constant.name, constant.value);
    }
    text
}

pub fn fingerprint(schema: &str) -> String {
    let digest = Sha256::digest(schema.as_bytes());
    digest.iter().map(|byte| format!("{byte:02x}")).collect()
}

// ---------------------------------------------------------------- TypeScript

pub fn entrypoints_ts(native: &Parsed) -> String {
    let mut text = String::from(BANNER);
    text.push_str(
        "\n/** Slot kinds in the normalized call ABI. Every slot is eight bytes wide. */\n\
         export type SlotKind =\n  | \"void\"\n  | \"bool\"\n  | \"i32\"\n  | \"u32\"\n  | \"i64\"\n  \
         | \"u64\"\n  | \"f32\"\n  | \"f64\"\n  | \"usize\"\n  | \"ptr\"\n  | \"handle\"\n  | \"struct\";\n\n\
         /** One public C entrypoint, as the shim's dispatch table sees it. */\n\
         export interface EntrypointInfo {\n  readonly name: string;\n  \
         readonly result: SlotKind;\n  readonly params: readonly SlotKind[];\n}\n\n",
    );

    let _ = writeln!(
        text,
        "/** Entrypoint ids, which are the indexes the shim dispatches on. */\nexport const EP = {{"
    );
    for (index, entrypoint) in native.entrypoints.iter().enumerate() {
        let _ = writeln!(text, "  {}: {index},", entrypoint.name);
    }
    text.push_str("} as const;\n\n");

    text.push_str("export const ENTRYPOINTS: readonly EntrypointInfo[] = [\n");
    for entrypoint in &native.entrypoints {
        let params = entrypoint
            .params
            .iter()
            .map(|param| format!("\"{}\"", param.slot.as_str()))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            text,
            "  {{ name: \"{}\", result: \"{}\", params: [{params}] }},",
            entrypoint.name,
            entrypoint.result.as_str()
        );
    }
    text.push_str("];\n");
    text
}

pub fn layouts_ts(native: &Parsed, wasm: &Parsed) -> String {
    let mut text = String::from(BANNER);
    text.push_str(
        "\n/** One record field's placement, measured by Clang for its ABI class. */\n\
         export interface FieldLayout {\n  readonly offset: number;\n  readonly size: number;\n}\n\n\
         export interface RecordLayout {\n  readonly size: number;\n  readonly align: number;\n  \
         readonly fields: Readonly<Record<string, FieldLayout>>;\n}\n\n\
         /** The ABI classes this binding's transports present. */\n\
         export type AbiClass = \"native64\" | \"wasm32\";\n\n",
    );
    text.push_str("export const LAYOUTS: Readonly<\n  Record<AbiClass, Readonly<Record<string, RecordLayout>>>\n> = {\n");
    for (abi, parsed) in [("native64", native), ("wasm32", wasm)] {
        let _ = writeln!(text, "  {abi}: {{");
        for (name, record) in &parsed.records {
            let _ = writeln!(
                text,
                "    {name}: {{ size: {}, align: {}, fields: {{",
                record.size, record.align
            );
            for field in &record.order {
                let (offset, size) = record.fields[field];
                let _ = writeln!(text, "      {field}: {{ offset: {offset}, size: {size} }},");
            }
            text.push_str("    } },\n");
        }
        text.push_str("  },\n");
    }
    text.push_str("};\n");
    text
}

pub fn enums_ts(native: &Parsed) -> String {
    let mut text = String::from(BANNER);
    text.push('\n');
    for enumeration in &native.enums {
        let _ = writeln!(
            text,
            "/** `{}` values as the C API defines them. */\nexport const {} = {{",
            enumeration.name,
            enumeration.name.to_uppercase()
        );
        for (member, value) in &enumeration.members {
            let _ = writeln!(text, "  {member}: {value},");
        }
        text.push_str("} as const;\n\n");
    }
    text
}

pub fn constants_ts(native: &Parsed) -> String {
    let mut text = String::from(BANNER);
    text.push('\n');
    for constant in &native.constants {
        // Handle ids cross the boundary as bigints, so the null handle is one
        // too; every other constant is an ordinary number.
        if constant.name == "MLN_HANDLE_NULL" {
            let _ = writeln!(
                text,
                "export const {} = {}n;",
                constant.name, constant.value
            );
        } else {
            let _ = writeln!(text, "export const {} = {};", constant.name, constant.value);
        }
    }
    text
}

pub fn fingerprint_ts(value: &str, header_digest: &str) -> String {
    format!(
        "{BANNER}\n/**\n * The ABI schema fingerprint this binding was generated from.\n *\n \
         * A runtime payload reports its own. The facade refuses to call one that\n \
         * disagrees, because the call ABI indexes entrypoints rather than naming them.\n */\n\
         export const ABI_FINGERPRINT = \"{value}\";\n\n\
         /**\n * Digest of the public header bytes the generation ran against.\n *\n \
         * The addon build refuses to link a native artifact whose headers differ,\n \
         * because a checked-in dispatch table describes one exact library ABI.\n */\n\
         export const ABI_HEADER_DIGEST = \"{header_digest}\";\n"
    )
}

// ------------------------------------------------------------------------- C

pub fn dispatch_inc(native: &Parsed) -> Result<String, String> {
    let mut text = String::from(C_BANNER);
    for (index, entrypoint) in native.entrypoints.iter().enumerate() {
        let mut arguments = Vec::new();
        for (position, param) in entrypoint.params.iter().enumerate() {
            let slot = position + 1;
            if param.spelling.contains('[') {
                return Err(format!(
                    "{}: array parameter {} has no slot spelling",
                    entrypoint.name, param.name
                ));
            }
            arguments.push(read_slot(&param.spelling, param.slot, slot));
        }
        let call = format!("{}({})", entrypoint.name, arguments.join(", "));
        let body = write_result(&entrypoint.result_spelling, entrypoint.result, &call);
        let _ = writeln!(
            text,
            "case {index}: /* {} */ {{\n  {body}\n  break;\n}}",
            entrypoint.name
        );
    }
    Ok(text)
}

fn read_slot(spelling: &str, slot: SlotKind, index: usize) -> String {
    match slot {
        SlotKind::Bool => format!("(bool)(slots[{index}] != 0)"),
        SlotKind::I32 => format!("({spelling})(int32_t)(uint32_t)slots[{index}]"),
        SlotKind::U32 => format!("({spelling})(uint32_t)slots[{index}]"),
        SlotKind::I64 => format!("({spelling})(int64_t)slots[{index}]"),
        SlotKind::U64 | SlotKind::Handle => format!("({spelling})slots[{index}]"),
        SlotKind::Usize => format!("(size_t)slots[{index}]"),
        SlotKind::F32 => format!("mln_abi_read_f32(slots[{index}])"),
        SlotKind::F64 => format!("mln_abi_read_f64(slots[{index}])"),
        SlotKind::Ptr => format!("({spelling})(uintptr_t)slots[{index}]"),
        SlotKind::Struct => format!("*(const {spelling}*)(uintptr_t)slots[{index}]"),
        SlotKind::Void => "(void)0".to_string(),
    }
}

fn write_result(spelling: &str, slot: SlotKind, call: &str) -> String {
    match slot {
        SlotKind::Void => format!("{call};"),
        SlotKind::Bool => format!("slots[0] = (uint64_t)({call} ? 1 : 0);"),
        SlotKind::I32 => format!("slots[0] = (uint64_t)(uint32_t)(int32_t)({call});"),
        SlotKind::U32 => format!("slots[0] = (uint64_t)(uint32_t)({call});"),
        SlotKind::I64 => format!("slots[0] = (uint64_t)(int64_t)({call});"),
        SlotKind::U64 | SlotKind::Handle => format!("slots[0] = (uint64_t)({call});"),
        SlotKind::Usize => format!("slots[0] = (uint64_t)(size_t)({call});"),
        SlotKind::F32 => format!("slots[0] = mln_abi_write_f32({call});"),
        SlotKind::F64 => format!("slots[0] = mln_abi_write_f64({call});"),
        SlotKind::Ptr => format!("slots[0] = (uint64_t)(uintptr_t)({call});"),
        // A struct return lands in caller storage the return slot points at.
        SlotKind::Struct => format!("*({spelling}*)(uintptr_t)slots[0] = {call};"),
    }
}

pub fn symbols_inc(native: &Parsed) -> String {
    let mut text = String::from(C_BANNER);
    for (index, entrypoint) in native.entrypoints.iter().enumerate() {
        let _ = writeln!(
            text,
            "case {index}: return (void*)(uintptr_t)&{};",
            entrypoint.name
        );
    }
    text
}

pub fn layout_assert_c(native: &Parsed, wasm: &Parsed) -> String {
    let mut text = String::from(C_BANNER);
    text.push_str(
        "\n/*\n * Compiled for every supported target. A layout table that disagrees with\n \
         * the compiler fails the build instead of corrupting memory at run time.\n */\n\n\
         #include <stddef.h>\n#include <stdint.h>\n\n\
         #include \"maplibre_native_c.h\"\n#include \"maplibre_native_c/callback_adapter.h\"\n\n",
    );
    text.push_str("#if UINTPTR_MAX == 0xFFFFFFFFu\n");
    append_asserts(&mut text, &wasm.records);
    text.push_str("#else\n");
    append_asserts(&mut text, &native.records);
    text.push_str("#endif\n");
    text
}

fn append_asserts(text: &mut String, records: &BTreeMap<String, RecordLayout>) {
    for (name, record) in records {
        let _ = writeln!(
            text,
            "static_assert(sizeof({name}) == {}, \"{name} size\");",
            record.size
        );
        let _ = writeln!(
            text,
            "static_assert(_Alignof({name}) == {}, \"{name} alignment\");",
            record.align
        );
        for field in &record.order {
            let (offset, _) = record.fields[field];
            let _ = writeln!(
                text,
                "static_assert(offsetof({name}, {field}) == {offset}, \"{name}.{field} offset\");"
            );
        }
    }
}

pub fn fingerprint_h(value: &str, header_digest: &str, entrypoint_count: usize) -> String {
    format!(
        "{C_BANNER}\n#ifndef MLN_ABI_FINGERPRINT_H\n#define MLN_ABI_FINGERPRINT_H\n\n\
         #define MLN_ABI_FINGERPRINT_VALUE \"{value}\"\n\
         #define MLN_ABI_HEADER_DIGEST \"{header_digest}\"\n\
         #define MLN_ABI_ENTRYPOINT_COUNT {entrypoint_count}u\n\n\
         #endif /* MLN_ABI_FINGERPRINT_H */\n"
    )
}

pub fn entrypoint_names_inc(native: &Parsed) -> String {
    let mut text = String::from(C_BANNER);
    for entrypoint in &native.entrypoints {
        let _ = writeln!(text, "\"{}\",", entrypoint.name);
    }
    text
}

/// Marks which entrypoints report `mln_status`.
///
/// The shim copies the thread-local diagnostic inside the failing call, so it
/// has to know which results are statuses without asking the host.
pub fn result_is_status_inc(native: &Parsed) -> String {
    let mut text = String::from(C_BANNER);
    for entrypoint in &native.entrypoints {
        let is_status = entrypoint.result_spelling == "mln_status";
        let _ = writeln!(text, "{}, /* {} */", u8::from(is_status), entrypoint.name);
    }
    text
}
