# Generated from the C headers by tools/bindgen. Do not edit.
from collections.abc import Callable
from concurrent.futures import Future
from typing import Any

from ._completion import CommandCompletion
from ._generated_values import *

class _AcquiredFrameHandle:
    closed: bool
    id: int
    def with_metal_texture(self) -> Any: ...
    def with_opengl_texture(self) -> Any: ...
    def with_producer_sync(self) -> Any: ...
    def get_result(self) -> Any: ...
    def with_vulkan_texture(self) -> Any: ...
    def with_webgpu_texture(self) -> Any: ...
    def close(self, consumer_completion: GpuSync | None = None) -> Any: ...

class _BufferHandle:
    closed: bool
    id: int
    def close(self) -> Any: ...
    def get(self) -> Any: ...

class _EventBatchHandle:
    closed: bool
    id: int
    def get(self) -> Any: ...
    def close(self) -> Any: ...

class _GeojsonSourceDataHandle:
    closed: bool
    id: int
    def close(self) -> Any: ...

class _HttpHeaderTransformResponseScope:
    closed: bool
    id: int
    def set(self, name: str, value: str) -> Any: ...

class _MapHandle:
    closed: bool
    id: int
    def add_color_relief_layer(
        self, layer_id: str, source_id: str, before_layer_id: str | None = None
    ) -> Future[CommandCompletion]: ...
    def add_custom_geometry_source(
        self, source_id: str, options: CustomGeometrySourceOptions | None = None
    ) -> Future[CommandCompletion]: ...
    def add_custom_mvt_vector_source(
        self, source_id: str, options: CustomMvtVectorSourceOptions | None = None
    ) -> Future[CommandCompletion]: ...
    def add_geojson_source_data(
        self, source_id: str, data: _GeojsonSourceDataHandle
    ) -> Future[CommandCompletion]: ...
    def add_geojson_source_url(
        self, source_id: str, url: str, options: GeojsonSourceOptions | None = None
    ) -> Future[CommandCompletion]: ...
    def add_hillshade_layer(
        self, layer_id: str, source_id: str, before_layer_id: str | None = None
    ) -> Future[CommandCompletion]: ...
    def add_image_source_image(
        self,
        source_id: str,
        coordinates: tuple[LatLng, ...],
        image: PremultipliedRgba8Image | None = None,
    ) -> Future[CommandCompletion]: ...
    def add_image_source_url(
        self, source_id: str, coordinates: tuple[LatLng, ...], url: str
    ) -> Future[CommandCompletion]: ...
    def add_location_indicator_layer(
        self, layer_id: str, before_layer_id: str | None = None
    ) -> Future[CommandCompletion]: ...
    def add_raster_dem_source_tiles(
        self,
        source_id: str,
        tiles: tuple[str, ...],
        options: StyleTileSourceOptions | None = None,
    ) -> Future[CommandCompletion]: ...
    def add_raster_dem_source_url(
        self, source_id: str, url: str, options: StyleTileSourceOptions | None = None
    ) -> Future[CommandCompletion]: ...
    def add_raster_source_tiles(
        self,
        source_id: str,
        tiles: tuple[str, ...],
        options: StyleTileSourceOptions | None = None,
    ) -> Future[CommandCompletion]: ...
    def add_raster_source_url(
        self, source_id: str, url: str, options: StyleTileSourceOptions | None = None
    ) -> Future[CommandCompletion]: ...
    def add_style_layer_json(
        self, layer_json: bytes, before_layer_id: str | None = None
    ) -> Future[CommandCompletion]: ...
    def add_style_source_json(
        self, source_id: str, source_json: bytes
    ) -> Future[CommandCompletion]: ...
    def add_vector_source_tiles(
        self,
        source_id: str,
        tiles: tuple[str, ...],
        options: StyleTileSourceOptions | None = None,
    ) -> Future[CommandCompletion]: ...
    def add_vector_source_url(
        self, source_id: str, url: str, options: StyleTileSourceOptions | None = None
    ) -> Future[CommandCompletion]: ...
    def apply_camera_delta(
        self, delta: CameraDelta | None = None
    ) -> Future[CommandCompletion]: ...
    def camera_for_geometry(
        self, geometry: bytes, fit_options: CameraFitOptions | None = None
    ) -> Future[Any]: ...
    def camera_for_lat_lng_bounds(
        self, bounds: LatLngBounds, fit_options: CameraFitOptions | None = None
    ) -> Future[Any]: ...
    def camera_for_lat_lngs(
        self,
        coordinates: tuple[LatLng, ...],
        fit_options: CameraFitOptions | None = None,
    ) -> Future[Any]: ...
    def camera_query(self) -> Future[Any]: ...
    def camera_snapshot_get(self) -> Any: ...
    def cancel_transitions(self) -> Future[CommandCompletion]: ...
    def copy_layer_source_id(self, layer_id: str) -> Future[Any]: ...
    def copy_layer_source_layer(self, layer_id: str) -> Future[Any]: ...
    def copy_style_image_premultiplied_rgba8(self, image_id: str) -> Future[Any]: ...
    def copy_style_image_stretches(self, image_id: str) -> Future[Any]: ...
    def copy_style_source_attribution(self, source_id: str) -> Future[Any]: ...
    def copy_style_source_url(self, source_id: str) -> Future[Any]: ...
    def dump_debug_logs(self) -> Future[CommandCompletion]: ...
    def get_feature_state(self, selector: FeatureStateSelector) -> Future[Any]: ...
    def get_global_state(self) -> Future[Any]: ...
    def get_image_source_coordinates(self, source_id: str) -> Future[Any]: ...
    def get_layer_filter(self, layer_id: str) -> Future[Any]: ...
    def get_layer_property(self, layer_id: str, property_name: str) -> Future[Any]: ...
    def get_style_image_info(self, image_id: str) -> Future[Any]: ...
    def get_style_layer_info(self, layer_id: str) -> Future[Any]: ...
    def get_style_layer_json(self, layer_id: str) -> Future[Any]: ...
    def get_style_light_property(self, property_name: str) -> Future[Any]: ...
    def get_style_source_info(self, source_id: str) -> Future[Any]: ...
    def get_style_source_tile_urls(self, source_id: str) -> Future[Any]: ...
    def get_style_transition_options(self) -> Future[Any]: ...
    def invalidate_custom_geometry_source_region(
        self, source_id: str, bounds: LatLngBounds
    ) -> Future[CommandCompletion]: ...
    def invalidate_custom_geometry_source_tile(
        self, source_id: str, tile_id: CanonicalTileId
    ) -> Future[CommandCompletion]: ...
    def invalidate_custom_mvt_vector_source_tile(
        self, source_id: str, tile_id: CanonicalTileId
    ) -> Future[CommandCompletion]: ...
    def lat_lng_bounds_for_camera(
        self, camera: CameraOptions | None = None
    ) -> Future[Any]: ...
    def lat_lng_bounds_for_camera_unwrapped(
        self, camera: CameraOptions | None = None
    ) -> Future[Any]: ...
    def lat_lng_for_pixel(self, point: ScreenPoint) -> Future[Any]: ...
    def lat_lng_for_pixel_unwrapped(self, point: ScreenPoint) -> Future[Any]: ...
    def lat_lngs_for_pixels(self, points: tuple[ScreenPoint, ...]) -> Future[Any]: ...
    def lat_lngs_for_pixels_unwrapped(
        self, points: tuple[ScreenPoint, ...]
    ) -> Future[Any]: ...
    def list_style_layer_ids(self) -> Future[Any]: ...
    def list_style_layers(self) -> Future[Any]: ...
    def list_style_source_ids(self) -> Future[Any]: ...
    def loaded_style_json(self) -> Future[Any]: ...
    def meters_per_pixel_at_latitude(self, latitude: float) -> Future[Any]: ...
    def move_style_layer(
        self, layer_id: str, before_layer_id: str | None = None
    ) -> Future[CommandCompletion]: ...
    def pixel_for_lat_lng(self, coordinate: LatLng) -> Future[Any]: ...
    def pixels_for_lat_lngs(self, coordinates: tuple[LatLng, ...]) -> Future[Any]: ...
    def projection_create(self) -> Future[Any]: ...
    def close(self) -> Future[None]: ...
    def remove_feature_state(
        self, selector: FeatureStateSelector
    ) -> Future[CommandCompletion]: ...
    def remove_style_image(self, image_id: str) -> Future[CommandCompletion]: ...
    def remove_style_layer(self, layer_id: str) -> Future[CommandCompletion]: ...
    def remove_style_source(self, source_id: str) -> Future[CommandCompletion]: ...
    def request_repaint(self) -> Future[CommandCompletion]: ...
    def request_still_image(self) -> Future[None]: ...
    def resize(self, extent: LogicalExtent) -> Future[CommandCompletion]: ...
    def set_bounds(
        self, options: BoundOptions | None = None
    ) -> Future[CommandCompletion]: ...
    def set_custom_geometry_source_tile_data(
        self, source_id: str, tile_id: CanonicalTileId, data: bytes
    ) -> Future[CommandCompletion]: ...
    def set_custom_mvt_vector_source_tile_data(
        self, source_id: str, tile_id: CanonicalTileId, data: bytes
    ) -> Future[CommandCompletion]: ...
    def set_custom_mvt_vector_source_tile_error(
        self, source_id: str, tile_id: CanonicalTileId, message: str
    ) -> Future[CommandCompletion]: ...
    def set_debug_options(
        self, options: MapDebugOption
    ) -> Future[CommandCompletion]: ...
    def set_event_mask(self, mask: RuntimeEventMask) -> Future[CommandCompletion]: ...
    def set_feature_state(
        self, selector: FeatureStateSelector, input_state: bytes
    ) -> Future[CommandCompletion]: ...
    def set_free_camera_options(
        self, options: FreeCameraOptions | None = None
    ) -> Future[CommandCompletion]: ...
    def set_geojson_source_data(
        self, source_id: str, data: _GeojsonSourceDataHandle
    ) -> Future[CommandCompletion]: ...
    def set_geojson_source_synchronous_tiling(
        self, source_id: str, enabled: bool
    ) -> Future[CommandCompletion]: ...
    def set_geojson_source_url(
        self, source_id: str, url: str
    ) -> Future[CommandCompletion]: ...
    def set_global_state_property(
        self, property_name: str, value: bytes
    ) -> Future[CommandCompletion]: ...
    def set_image_source_coordinates(
        self, source_id: str, coordinates: tuple[LatLng, ...]
    ) -> Future[CommandCompletion]: ...
    def set_image_source_image(
        self, source_id: str, image: PremultipliedRgba8Image | None = None
    ) -> Future[CommandCompletion]: ...
    def set_image_source_url(
        self, source_id: str, url: str
    ) -> Future[CommandCompletion]: ...
    def set_layer_filter(
        self, layer_id: str, filter: bytes | None = None
    ) -> Future[CommandCompletion]: ...
    def set_layer_max_zoom(
        self, layer_id: str, max_zoom: float
    ) -> Future[CommandCompletion]: ...
    def set_layer_min_zoom(
        self, layer_id: str, min_zoom: float
    ) -> Future[CommandCompletion]: ...
    def set_layer_property(
        self, layer_id: str, property_name: str, value: bytes
    ) -> Future[CommandCompletion]: ...
    def set_layer_source_id(
        self, layer_id: str, source_id: str
    ) -> Future[CommandCompletion]: ...
    def set_layer_source_layer(
        self, layer_id: str, source_layer: str | None = None
    ) -> Future[CommandCompletion]: ...
    def set_layer_visibility(
        self, layer_id: str, visibility: StyleLayerVisibility
    ) -> Future[CommandCompletion]: ...
    def set_location_indicator_accuracy_radius(
        self, layer_id: str, radius: float
    ) -> Future[CommandCompletion]: ...
    def set_location_indicator_bearing(
        self, layer_id: str, bearing: float
    ) -> Future[CommandCompletion]: ...
    def set_location_indicator_image_name(
        self, layer_id: str, image_kind: LocationIndicatorImageKind, image_id: str
    ) -> Future[CommandCompletion]: ...
    def set_location_indicator_location(
        self, layer_id: str, coordinate: LatLng, altitude: float
    ) -> Future[CommandCompletion]: ...
    def set_projection_mode(
        self, mode: ProjectionMode | None = None
    ) -> Future[CommandCompletion]: ...
    def set_rendering_stats_view_enabled(
        self, enabled: bool
    ) -> Future[CommandCompletion]: ...
    def set_style_image(
        self,
        image_id: str,
        image: PremultipliedRgba8Image | None = None,
        options: StyleImageOptions | None = None,
    ) -> Future[CommandCompletion]: ...
    def set_style_json(self, json: bytes) -> Future[CommandCompletion]: ...
    def set_style_light_json(self, light_json: bytes) -> Future[CommandCompletion]: ...
    def set_style_light_property(
        self, property_name: str, value: bytes
    ) -> Future[CommandCompletion]: ...
    def set_style_source_volatile(
        self, source_id: str, is_volatile: bool
    ) -> Future[CommandCompletion]: ...
    def set_style_transition_options(
        self, options: StyleTransitionOptions | None = None
    ) -> Future[CommandCompletion]: ...
    def set_style_url(self, url: str) -> Future[CommandCompletion]: ...
    def set_tile_options(
        self, options: MapTileOptions | None = None
    ) -> Future[CommandCompletion]: ...
    def set_viewport_options(
        self, options: MapViewportOptions | None = None
    ) -> Future[CommandCompletion]: ...
    def snapshot_get(self) -> Any: ...
    def style_url(self) -> Future[Any]: ...
    def update_camera(
        self, update: CameraUpdate | None = None
    ) -> Future[CommandCompletion]: ...
    def metal_borrowed_texture_attach(
        self,
        descriptor: MetalBorrowedTextureDescriptor | None = None,
        options: RenderSessionAttachOptions | None = None,
    ) -> dict[str, Any]: ...
    def metal_owned_texture_attach(
        self,
        descriptor: MetalOwnedTextureDescriptor | None = None,
        options: RenderSessionAttachOptions | None = None,
    ) -> dict[str, Any]: ...
    def metal_surface_attach(
        self,
        descriptor: MetalSurfaceDescriptor | None = None,
        options: RenderSessionAttachOptions | None = None,
    ) -> dict[str, Any]: ...
    def opengl_borrowed_texture_attach(
        self,
        descriptor: OpenglBorrowedTextureDescriptor | None = None,
        options: RenderSessionAttachOptions | None = None,
    ) -> dict[str, Any]: ...
    def opengl_owned_texture_attach(
        self,
        descriptor: OpenglOwnedTextureDescriptor | None = None,
        options: RenderSessionAttachOptions | None = None,
    ) -> dict[str, Any]: ...
    def opengl_surface_attach(
        self,
        descriptor: OpenglSurfaceDescriptor | None = None,
        options: RenderSessionAttachOptions | None = None,
    ) -> dict[str, Any]: ...
    def vulkan_borrowed_texture_attach(
        self,
        descriptor: VulkanBorrowedTextureDescriptor | None = None,
        options: RenderSessionAttachOptions | None = None,
    ) -> dict[str, Any]: ...
    def vulkan_owned_texture_attach(
        self,
        descriptor: VulkanOwnedTextureDescriptor | None = None,
        options: RenderSessionAttachOptions | None = None,
    ) -> dict[str, Any]: ...
    def vulkan_surface_attach(
        self,
        descriptor: VulkanSurfaceDescriptor | None = None,
        options: RenderSessionAttachOptions | None = None,
    ) -> dict[str, Any]: ...
    def webgpu_borrowed_texture_attach(
        self,
        descriptor: WebgpuBorrowedTextureDescriptor | None = None,
        options: RenderSessionAttachOptions | None = None,
    ) -> dict[str, Any]: ...
    def webgpu_owned_texture_attach(
        self,
        descriptor: WebgpuOwnedTextureDescriptor | None = None,
        options: RenderSessionAttachOptions | None = None,
    ) -> dict[str, Any]: ...
    def webgpu_surface_attach(
        self,
        descriptor: WebgpuSurfaceDescriptor | None = None,
        options: RenderSessionAttachOptions | None = None,
    ) -> dict[str, Any]: ...

class _MapProjectionHandle:
    closed: bool
    id: int
    def close(self) -> Any: ...
    def get_camera(self) -> Any: ...
    def lat_lng_for_pixel(self, point: ScreenPoint) -> Any: ...
    def lat_lng_for_pixel_unwrapped(self, point: ScreenPoint) -> Any: ...
    def meters_per_pixel_at_latitude(self, latitude: float) -> Any: ...
    def pixel_for_lat_lng(self, coordinate: LatLng) -> Any: ...
    def set_camera(self, camera: CameraOptions | None = None) -> Any: ...
    def set_visible_coordinates(
        self, coordinates: tuple[LatLng, ...], padding: EdgeInsets
    ) -> Any: ...
    def set_visible_geometry(self, geometry: bytes, padding: EdgeInsets) -> Any: ...

class _RenderFrameBatchHandle:
    closed: bool
    id: int
    def count(self) -> Any: ...
    def get(self, index: int) -> Any: ...
    def close(self) -> Any: ...

class _RenderSessionHandle:
    closed: bool
    id: int
    def metal_borrowed_texture_set_target(
        self, descriptor: MetalBorrowedTextureDescriptor | None = None
    ) -> Future[None]: ...
    def metal_surface_set_target(
        self, descriptor: MetalSurfaceDescriptor | None = None
    ) -> Future[None]: ...
    def opengl_borrowed_texture_set_target(
        self, descriptor: OpenglBorrowedTextureDescriptor | None = None
    ) -> Future[None]: ...
    def opengl_surface_set_target(
        self, descriptor: OpenglSurfaceDescriptor | None = None
    ) -> Future[None]: ...
    def abandon(self) -> Any: ...
    def acquire_frame(self) -> Any: ...
    def barrier(self) -> Future[None]: ...
    def clear_data(self) -> Future[None]: ...
    def close(self) -> Any: ...
    def detach(self) -> Future[None]: ...
    def drain_frame_results(self) -> Any: ...
    def dump_debug_logs(self) -> Future[None]: ...
    def get_capabilities(self) -> Any: ...
    def get_snapshot(self) -> Any: ...
    def projection_create(self) -> Any: ...
    def query_feature_extensions(
        self,
        source_id: str,
        feature: bytes,
        extension: str,
        extension_field: str,
        arguments: bytes | None = None,
    ) -> Future[Any]: ...
    def query_rendered_features(
        self,
        geometry: RenderedQueryGeometry,
        options: RenderedFeatureQueryOptions | None = None,
    ) -> Future[Any]: ...
    def query_source_features(
        self, source_id: str, options: SourceFeatureQueryOptions | None = None
    ) -> Future[Any]: ...
    def reduce_memory_use(self) -> Future[None]: ...
    def request_frame(self, demand: FrameDemand | None = None) -> Any: ...
    def resize(self, extent: RenderTargetExtent) -> Future[CommandCompletion]: ...
    def service_driver_work(self, max_work: int) -> Any: ...
    def texture_read_premultiplied_rgba8(self) -> Future[Any]: ...
    def vulkan_borrowed_texture_set_target(
        self, descriptor: VulkanBorrowedTextureDescriptor | None = None
    ) -> Future[None]: ...
    def vulkan_surface_set_target(
        self, descriptor: VulkanSurfaceDescriptor | None = None
    ) -> Future[None]: ...
    def webgpu_borrowed_texture_set_target(
        self, descriptor: WebgpuBorrowedTextureDescriptor | None = None
    ) -> Future[None]: ...
    def webgpu_surface_set_target(
        self, descriptor: WebgpuSurfaceDescriptor | None = None
    ) -> Future[None]: ...

class _ResourceRequestHandle:
    closed: bool
    id: int
    def cancelled(self) -> Any: ...
    def complete(self, response: ResourceResponse) -> Any: ...
    def close(self) -> None: ...
    def set_cancel_callback(self, callback: Callable[[], None]) -> bool: ...
    def wait_until_retired(self) -> Any: ...

class _ResourceTransformResponseScope:
    closed: bool
    id: int
    def set_url(self, url: str) -> Any: ...

class _RuntimeHandle:
    closed: bool
    id: int
    def map_create(self, options: MapOptions | None = None) -> Future[Any]: ...
    def barrier(self) -> Future[None]: ...
    def clear_http_header_transform(self) -> Future[None]: ...
    def clear_resource_provider(self) -> Future[None]: ...
    def clear_resource_transform(self) -> Future[None]: ...
    def drain_events(self) -> Any: ...
    def get_event_mask(self) -> Any: ...
    def offline_region_create(
        self, definition: OfflineRegionDefinition, metadata: bytes
    ) -> Future[Any]: ...
    def offline_region_delete(self, region_id: int) -> Future[None]: ...
    def offline_region_get(self, region_id: int) -> Future[Any]: ...
    def offline_region_get_status(self, region_id: int) -> Future[Any]: ...
    def offline_region_invalidate(self, region_id: int) -> Future[None]: ...
    def offline_region_set_download_state(
        self, region_id: int, input_state: OfflineRegionDownloadState
    ) -> Future[None]: ...
    def offline_region_set_observed(
        self, region_id: int, observed: bool
    ) -> Future[None]: ...
    def offline_region_update_metadata(
        self, region_id: int, metadata: bytes
    ) -> Future[Any]: ...
    def offline_regions_list(self) -> Future[Any]: ...
    def offline_regions_merge_database(
        self, side_database_path: str
    ) -> Future[Any]: ...
    def close(self) -> Future[None]: ...
    def run_ambient_cache_operation(
        self, operation: AmbientCacheOperation
    ) -> Future[None]: ...
    def set_event_mask(self, mask: RuntimeEventMask) -> Any: ...
    def set_http_header_transform(
        self, transform: HttpHeaderTransform
    ) -> Future[None]: ...
    def set_maximum_ambient_cache_size(self, size: int) -> Future[None]: ...
    def set_resource_provider(self, provider: ResourceProvider) -> Future[None]: ...
    def set_resource_transform(self, transform: ResourceTransform) -> Future[None]: ...

def android_init(jni_env: int, jni_class: int, context: int) -> Any: ...
def c_version() -> Any: ...
def geojson_source_data_create(
    data: bytes, options: GeojsonSourceOptions | None = None
) -> Any: ...
def lat_lng_for_projected_meters(meters: ProjectedMeters) -> Any: ...
def log_clear_callback() -> Any: ...
def log_set_async_severity_mask(mask: LogSeverityMask) -> Any: ...
def log_set_callback(
    callback: Callable[[LogSeverity, LogEvent, int, str], int] | None = None,
) -> None: ...
def network_status_get() -> Any: ...
def network_status_set(input_status: NetworkStatus) -> Any: ...
def opengl_supported_context_provider_mask() -> Any: ...
def plugin_get_register_function_v1() -> Any: ...
def projected_meters_for_lat_lng(coordinate: LatLng) -> Any: ...
def render_target_extent_physical_size(extent: RenderTargetExtent) -> Any: ...
def rendered_query_geometry_box(input_box: ScreenBox) -> Any: ...
def rendered_query_geometry_line_string(points: tuple[ScreenPoint, ...]) -> Any: ...
def rendered_query_geometry_point(point: ScreenPoint) -> Any: ...
def runtime_create(options: RuntimeOptions | None = None) -> Any: ...
def supported_render_backend_mask() -> Any: ...
def _default_animation_options() -> Any: ...
def _default_bound_options() -> Any: ...
def _default_camera_delta() -> Any: ...
def _default_camera_fit_options() -> Any: ...
def _default_camera_options() -> Any: ...
def _default_camera_update() -> Any: ...
def _default_custom_geometry_source_options() -> Any: ...
def _default_custom_mvt_vector_source_options() -> Any: ...
def _default_frame_demand() -> Any: ...
def _default_free_camera_options() -> Any: ...
def _default_geojson_source_options() -> Any: ...
def _default_gpu_sync() -> Any: ...
def _default_map_options() -> Any: ...
def _default_map_tile_options() -> Any: ...
def _default_map_viewport_options() -> Any: ...
def _default_metal_borrowed_texture_descriptor() -> Any: ...
def _default_metal_owned_texture_descriptor() -> Any: ...
def _default_metal_surface_descriptor() -> Any: ...
def _default_opengl_borrowed_texture_descriptor() -> Any: ...
def _default_opengl_owned_texture_descriptor() -> Any: ...
def _default_opengl_surface_descriptor() -> Any: ...
def _default_premultiplied_rgba8_image() -> Any: ...
def _default_projection_mode() -> Any: ...
def _default_render_session_attach_options() -> Any: ...
def _default_rendered_feature_query_options() -> Any: ...
def _default_runtime_options() -> Any: ...
def _default_source_feature_query_options() -> Any: ...
def _default_style_image_info() -> Any: ...
def _default_style_image_options() -> Any: ...
def _default_style_tile_source_options() -> Any: ...
def _default_style_transition_options() -> Any: ...
def _default_texture_image_info() -> Any: ...
def _default_vulkan_borrowed_texture_descriptor() -> Any: ...
def _default_vulkan_owned_texture_descriptor() -> Any: ...
def _default_vulkan_surface_descriptor() -> Any: ...
def _default_webgpu_borrowed_texture_descriptor() -> Any: ...
def _default_webgpu_owned_texture_descriptor() -> Any: ...
def _default_webgpu_surface_descriptor() -> Any: ...
