// Generated by tools/bindgen. Do not edit.
package org.maplibre.nativeffi.internal.javacpp;

import org.bytedeco.javacpp.Pointer;
import org.bytedeco.javacpp.annotation.Cast;
import org.bytedeco.javacpp.annotation.Name;
import org.bytedeco.javacpp.annotation.Platform;
import org.bytedeco.javacpp.annotation.Properties;

@Properties(
    inherit = MaplibreNativeCConfig.class,
    value = @Platform(include = "callback_bridge_generated.h"))
public final class GeneratedCallbackBridge {
  private GeneratedCallbackBridge() {}

  @Name("mln_android_custom_geometry_source_options_has_callbacks")
  public static native boolean hasCustomGeometrySourceOptionsCallbacks(
      @Cast("const mln_custom_geometry_source_options*") Pointer source);

  @Name("mln_android_custom_mvt_vector_source_options_has_callbacks")
  public static native boolean hasCustomMvtVectorSourceOptionsCallbacks(
      @Cast("const mln_custom_mvt_vector_source_options*") Pointer source);

  @Name("mln_android_wake_has_callbacks")
  public static native boolean hasWakeCallbacks(@Cast("const mln_wake*") Pointer source);
}
