// Code generated by tools/bindgen; DO NOT EDIT.
#include "generated_callbacks.h"
extern void mlnGoCallbackRelease(void*);
extern uint64_t mlnGoCallbackOwner(void*);
void binding_release(void* p) { mlnGoCallbackRelease(p); }
void binding_release_forbid(void* p) {
  binding_policy policy = {0};
  binding_policy_enter(&policy);
  mlnGoCallbackRelease(p);
  binding_policy_leave(&policy);
}
extern uint32_t mlnGo_mln_log_set_callback_registration_callback(
  void* user_data, uint32_t severity, uint32_t event, int64_t code,
  char* message
);
uint32_t binding_mln_log_set_callback_registration_callback(
  void* user_data, uint32_t severity, uint32_t event, int64_t code,
  const char* message
) {
  static const uint32_t operations[] = {0};
  binding_policy policy = {NULL, operations, 0, 0};
  binding_policy_enter(&policy);
  uint32_t result = mlnGo_mln_log_set_callback_registration_callback(
    (void*)user_data, severity, event, code, (char*)message
  );
  binding_policy_leave(&policy);
  return result;
}
extern void mlnGo_mln_custom_geometry_source_options_fetch_tile(
  void* user_data, mln_canonical_tile_id tile_id
);
void binding_mln_custom_geometry_source_options_fetch_tile(
  void* user_data, mln_canonical_tile_id tile_id
) {
  mlnGo_mln_custom_geometry_source_options_fetch_tile(
    (void*)user_data, tile_id
  );
}
extern void mlnGo_mln_custom_geometry_source_options_cancel_tile(
  void* user_data, mln_canonical_tile_id tile_id
);
void binding_mln_custom_geometry_source_options_cancel_tile(
  void* user_data, mln_canonical_tile_id tile_id
) {
  mlnGo_mln_custom_geometry_source_options_cancel_tile(
    (void*)user_data, tile_id
  );
}
extern void mlnGo_mln_custom_mvt_vector_source_options_fetch_tile(
  void* user_data, mln_canonical_tile_id tile_id
);
void binding_mln_custom_mvt_vector_source_options_fetch_tile(
  void* user_data, mln_canonical_tile_id tile_id
) {
  mlnGo_mln_custom_mvt_vector_source_options_fetch_tile(
    (void*)user_data, tile_id
  );
}
extern void mlnGo_mln_custom_mvt_vector_source_options_cancel_tile(
  void* user_data, mln_canonical_tile_id tile_id
);
void binding_mln_custom_mvt_vector_source_options_cancel_tile(
  void* user_data, mln_canonical_tile_id tile_id
) {
  mlnGo_mln_custom_mvt_vector_source_options_cancel_tile(
    (void*)user_data, tile_id
  );
}
extern void mlnGo_mln_wake_callback(void* user_data);
void binding_mln_wake_callback(void* user_data) {
  mlnGo_mln_wake_callback((void*)user_data);
}
extern void mlnGo_mln_queue_lock_lock(void* user_data);
void binding_mln_queue_lock_lock(void* user_data) {
  static const uint32_t operations[] = {0};
  binding_policy policy = {NULL, operations, 0, 0};
  binding_policy_enter(&policy);
  mlnGo_mln_queue_lock_lock((void*)user_data);
  binding_policy_leave(&policy);
}
extern void mlnGo_mln_queue_lock_unlock(void* user_data);
void binding_mln_queue_lock_unlock(void* user_data) {
  static const uint32_t operations[] = {0};
  binding_policy policy = {NULL, operations, 0, 0};
  binding_policy_enter(&policy);
  mlnGo_mln_queue_lock_unlock((void*)user_data);
  binding_policy_leave(&policy);
}
extern void
mlnGo_mln_resource_request_set_cancel_callback_registration_callback(
  void* user_data
);
void binding_mln_resource_request_set_cancel_callback_registration_callback(
  void* user_data
) {
  static const uint32_t operations[] = {
    binding_operation_mln_resource_request_complete,
    binding_operation_mln_resource_request_cancelled,
    binding_operation_mln_resource_request_set_cancel_callback,
    binding_operation_mln_resource_request_release
  };
  binding_policy policy = {NULL, operations, 4, mlnGoCallbackOwner(user_data)};
  binding_policy_enter(&policy);
  mlnGo_mln_resource_request_set_cancel_callback_registration_callback(
    (void*)user_data
  );
  binding_policy_leave(&policy);
}
extern mln_status mlnGo_mln_http_header_transform_callback(
  void* user_data, uint32_t kind, char* url,
  mln_http_header_transform_response* out_response
);
mln_status binding_mln_http_header_transform_callback(
  void* user_data, uint32_t kind, const char* url,
  mln_http_header_transform_response* out_response
) {
  static const uint32_t operations[] = {
    binding_operation_mln_http_header_transform_response_set
  };
  binding_policy policy = {
    NULL, operations, 1, (uint64_t)(uintptr_t)out_response
  };
  binding_policy_enter(&policy);
  mln_status result = mlnGo_mln_http_header_transform_callback(
    (void*)user_data, kind, (char*)url,
    (mln_http_header_transform_response*)out_response
  );
  binding_policy_leave(&policy);
  return result;
}
extern uint32_t mlnGo_mln_resource_provider_callback(
  void* user_data, mln_resource_request* request,
  mln_resource_request_handle handle
);
uint32_t binding_mln_resource_provider_callback(
  void* user_data, const mln_resource_request* request,
  mln_resource_request_handle handle
) {
  static const uint32_t operations[] = {
    binding_operation_mln_resource_request_complete,
    binding_operation_mln_resource_request_cancelled,
    binding_operation_mln_resource_request_set_cancel_callback,
    binding_operation_mln_resource_request_release
  };
  binding_policy policy = {NULL, operations, 4, (uint64_t)(uintptr_t)handle};
  binding_policy_enter(&policy);
  uint32_t result = mlnGo_mln_resource_provider_callback(
    (void*)user_data, (mln_resource_request*)request, handle
  );
  binding_policy_leave(&policy);
  return result;
}
extern mln_status mlnGo_mln_resource_transform_callback(
  void* user_data, uint32_t kind, char* url,
  mln_resource_transform_response* out_response
);
mln_status binding_mln_resource_transform_callback(
  void* user_data, uint32_t kind, const char* url,
  mln_resource_transform_response* out_response
) {
  static const uint32_t operations[] = {
    binding_operation_mln_resource_transform_response_set_url
  };
  binding_policy policy = {
    NULL, operations, 1, (uint64_t)(uintptr_t)out_response
  };
  binding_policy_enter(&policy);
  mln_status result = mlnGo_mln_resource_transform_callback(
    (void*)user_data, kind, (char*)url,
    (mln_resource_transform_response*)out_response
  );
  binding_policy_leave(&policy);
  return result;
}