// Code generated by tools/bindgen; DO NOT EDIT.
#ifndef MLN_GO_GENERATED_CALLBACKS_H
#define MLN_GO_GENERATED_CALLBACKS_H
#include "binding_callback.h"
#include "maplibre_native_c.h"
void binding_release(void*);
void binding_release_forbid(void*);
uint32_t binding_mln_log_set_callback_registration_callback(
  void* user_data, uint32_t severity, uint32_t event, int64_t code,
  const char* message
);
void binding_mln_custom_geometry_source_options_fetch_tile(
  void* user_data, mln_canonical_tile_id tile_id
);
void binding_mln_custom_geometry_source_options_cancel_tile(
  void* user_data, mln_canonical_tile_id tile_id
);
void binding_mln_custom_mvt_vector_source_options_fetch_tile(
  void* user_data, mln_canonical_tile_id tile_id
);
void binding_mln_custom_mvt_vector_source_options_cancel_tile(
  void* user_data, mln_canonical_tile_id tile_id
);
void binding_mln_wake_callback(void* user_data);
void binding_mln_queue_lock_lock(void* user_data);
void binding_mln_queue_lock_unlock(void* user_data);
void binding_mln_resource_request_set_cancel_callback_registration_callback(
  void* user_data
);
mln_status binding_mln_http_header_transform_callback(
  void* user_data, uint32_t kind, const char* url,
  mln_http_header_transform_response* out_response
);
uint32_t binding_mln_resource_provider_callback(
  void* user_data, const mln_resource_request* request,
  mln_resource_request_handle handle
);
mln_status binding_mln_resource_transform_callback(
  void* user_data, uint32_t kind, const char* url,
  mln_resource_transform_response* out_response
);
enum { binding_operation_mln_acquired_frame_dispose = 1 };
enum { binding_operation_mln_acquired_frame_get_metal_texture = 2 };
enum { binding_operation_mln_acquired_frame_get_opengl_texture = 3 };
enum { binding_operation_mln_acquired_frame_get_producer_sync = 4 };
enum { binding_operation_mln_acquired_frame_get_result = 5 };
enum { binding_operation_mln_acquired_frame_get_vulkan_texture = 6 };
enum { binding_operation_mln_acquired_frame_get_webgpu_texture = 7 };
enum { binding_operation_mln_acquired_frame_release = 8 };
enum { binding_operation_mln_android_init = 9 };
enum { binding_operation_mln_animation_options_default = 10 };
enum { binding_operation_mln_bound_options_default = 11 };
enum { binding_operation_mln_buffer_destroy = 12 };
enum { binding_operation_mln_buffer_get = 13 };
enum { binding_operation_mln_c_version = 14 };
enum { binding_operation_mln_camera_delta_default = 15 };
enum { binding_operation_mln_camera_fit_options_default = 16 };
enum { binding_operation_mln_camera_options_default = 17 };
enum { binding_operation_mln_camera_update_default = 18 };
enum { binding_operation_mln_custom_geometry_source_options_default = 19 };
enum { binding_operation_mln_custom_mvt_vector_source_options_default = 20 };
enum { binding_operation_mln_event_batch_get = 21 };
enum { binding_operation_mln_event_batch_release = 22 };
enum { binding_operation_mln_frame_demand_default = 23 };
enum { binding_operation_mln_free_camera_options_default = 24 };
enum { binding_operation_mln_geojson_source_data_create = 25 };
enum { binding_operation_mln_geojson_source_data_destroy = 26 };
enum { binding_operation_mln_geojson_source_options_default = 27 };
enum { binding_operation_mln_gpu_sync_default = 28 };
enum { binding_operation_mln_http_header_transform_response_set = 29 };
enum { binding_operation_mln_lat_lng_for_projected_meters = 30 };
enum { binding_operation_mln_log_clear_callback = 31 };
enum { binding_operation_mln_log_set_async_severity_mask = 32 };
enum { binding_operation_mln_log_set_callback = 33 };
enum { binding_operation_mln_logical_extent_physical_size = 34 };
enum { binding_operation_mln_map_add_color_relief_layer = 35 };
enum { binding_operation_mln_map_add_custom_geometry_source = 36 };
enum { binding_operation_mln_map_add_custom_mvt_vector_source = 37 };
enum { binding_operation_mln_map_add_geojson_source_data = 38 };
enum { binding_operation_mln_map_add_geojson_source_url = 39 };
enum { binding_operation_mln_map_add_hillshade_layer = 40 };
enum { binding_operation_mln_map_add_image_source_image = 41 };
enum { binding_operation_mln_map_add_image_source_url = 42 };
enum { binding_operation_mln_map_add_location_indicator_layer = 43 };
enum { binding_operation_mln_map_add_raster_dem_source_tiles = 44 };
enum { binding_operation_mln_map_add_raster_dem_source_url = 45 };
enum { binding_operation_mln_map_add_raster_source_tiles = 46 };
enum { binding_operation_mln_map_add_raster_source_url = 47 };
enum { binding_operation_mln_map_add_style_layer_json = 48 };
enum { binding_operation_mln_map_add_style_source_json = 49 };
enum { binding_operation_mln_map_add_vector_source_tiles = 50 };
enum { binding_operation_mln_map_add_vector_source_url = 51 };
enum { binding_operation_mln_map_apply_camera_delta = 52 };
enum { binding_operation_mln_map_camera_for_geometry = 53 };
enum { binding_operation_mln_map_camera_for_lat_lng_bounds = 54 };
enum { binding_operation_mln_map_camera_for_lat_lngs = 55 };
enum { binding_operation_mln_map_camera_query = 56 };
enum { binding_operation_mln_map_cancel_transitions = 57 };
enum { binding_operation_mln_map_copy_layer_source_id = 58 };
enum { binding_operation_mln_map_copy_layer_source_layer = 59 };
enum { binding_operation_mln_map_copy_style_image_premultiplied_rgba8 = 60 };
enum { binding_operation_mln_map_copy_style_image_stretches = 61 };
enum { binding_operation_mln_map_copy_style_source_attribution = 62 };
enum { binding_operation_mln_map_copy_style_source_url = 63 };
enum { binding_operation_mln_map_create = 64 };
enum { binding_operation_mln_map_dispose = 65 };
enum { binding_operation_mln_map_dump_debug_logs = 66 };
enum { binding_operation_mln_map_get_feature_state = 67 };
enum { binding_operation_mln_map_get_global_state = 68 };
enum { binding_operation_mln_map_get_image_source_coordinates = 69 };
enum { binding_operation_mln_map_get_layer_filter = 70 };
enum { binding_operation_mln_map_get_layer_property = 71 };
enum { binding_operation_mln_map_get_style_image_info = 72 };
enum { binding_operation_mln_map_get_style_layer_info = 73 };
enum { binding_operation_mln_map_get_style_layer_json = 74 };
enum { binding_operation_mln_map_get_style_light_property = 75 };
enum { binding_operation_mln_map_get_style_source_info = 76 };
enum { binding_operation_mln_map_get_style_source_tile_urls = 77 };
enum { binding_operation_mln_map_get_style_transition_options = 78 };
enum {
  binding_operation_mln_map_invalidate_custom_geometry_source_region = 79
};
enum { binding_operation_mln_map_invalidate_custom_geometry_source_tile = 80 };
enum {
  binding_operation_mln_map_invalidate_custom_mvt_vector_source_tile = 81
};
enum { binding_operation_mln_map_lat_lng_bounds_for_camera = 82 };
enum { binding_operation_mln_map_lat_lng_bounds_for_camera_unwrapped = 83 };
enum { binding_operation_mln_map_lat_lng_for_pixel = 84 };
enum { binding_operation_mln_map_lat_lng_for_pixel_unwrapped = 85 };
enum { binding_operation_mln_map_lat_lngs_for_pixels = 86 };
enum { binding_operation_mln_map_lat_lngs_for_pixels_unwrapped = 87 };
enum { binding_operation_mln_map_list_style_layer_ids = 88 };
enum { binding_operation_mln_map_list_style_layers = 89 };
enum { binding_operation_mln_map_list_style_source_ids = 90 };
enum { binding_operation_mln_map_loaded_style_json = 91 };
enum { binding_operation_mln_map_meters_per_pixel_at_latitude = 92 };
enum { binding_operation_mln_map_move_style_layer = 93 };
enum { binding_operation_mln_map_options_default = 94 };
enum { binding_operation_mln_map_pixel_for_lat_lng = 95 };
enum { binding_operation_mln_map_pixels_for_lat_lngs = 96 };
enum { binding_operation_mln_map_projection_close = 97 };
enum { binding_operation_mln_map_projection_create = 98 };
enum { binding_operation_mln_map_projection_get_camera = 99 };
enum { binding_operation_mln_map_projection_lat_lng_for_pixel = 100 };
enum { binding_operation_mln_map_projection_lat_lng_for_pixel_unwrapped = 101 };
enum {
  binding_operation_mln_map_projection_meters_per_pixel_at_latitude = 102
};
enum { binding_operation_mln_map_projection_pixel_for_lat_lng = 103 };
enum { binding_operation_mln_map_projection_set_camera = 104 };
enum { binding_operation_mln_map_projection_set_visible_coordinates = 105 };
enum { binding_operation_mln_map_projection_set_visible_geometry = 106 };
enum { binding_operation_mln_map_release = 107 };
enum { binding_operation_mln_map_remove_feature_state = 108 };
enum { binding_operation_mln_map_remove_style_image = 109 };
enum { binding_operation_mln_map_remove_style_layer = 110 };
enum { binding_operation_mln_map_remove_style_source = 111 };
enum { binding_operation_mln_map_request_repaint = 112 };
enum { binding_operation_mln_map_request_still_image = 113 };
enum { binding_operation_mln_map_resize = 114 };
enum { binding_operation_mln_map_set_bounds = 115 };
enum { binding_operation_mln_map_set_custom_geometry_source_tile_data = 116 };
enum { binding_operation_mln_map_set_custom_mvt_vector_source_tile_data = 117 };
enum {
  binding_operation_mln_map_set_custom_mvt_vector_source_tile_error = 118
};
enum { binding_operation_mln_map_set_debug_options = 119 };
enum { binding_operation_mln_map_set_event_mask = 120 };
enum { binding_operation_mln_map_set_feature_state = 121 };
enum { binding_operation_mln_map_set_free_camera_options = 122 };
enum { binding_operation_mln_map_set_geojson_source_data = 123 };
enum { binding_operation_mln_map_set_geojson_source_synchronous_tiling = 124 };
enum { binding_operation_mln_map_set_geojson_source_url = 125 };
enum { binding_operation_mln_map_set_global_state_property = 126 };
enum { binding_operation_mln_map_set_image_source_coordinates = 127 };
enum { binding_operation_mln_map_set_image_source_image = 128 };
enum { binding_operation_mln_map_set_image_source_url = 129 };
enum { binding_operation_mln_map_set_layer_filter = 130 };
enum { binding_operation_mln_map_set_layer_max_zoom = 131 };
enum { binding_operation_mln_map_set_layer_min_zoom = 132 };
enum { binding_operation_mln_map_set_layer_property = 133 };
enum { binding_operation_mln_map_set_layer_source_id = 134 };
enum { binding_operation_mln_map_set_layer_source_layer = 135 };
enum { binding_operation_mln_map_set_layer_visibility = 136 };
enum { binding_operation_mln_map_set_location_indicator_accuracy_radius = 137 };
enum { binding_operation_mln_map_set_location_indicator_bearing = 138 };
enum { binding_operation_mln_map_set_location_indicator_image_name = 139 };
enum { binding_operation_mln_map_set_location_indicator_location = 140 };
enum { binding_operation_mln_map_set_projection_mode = 141 };
enum { binding_operation_mln_map_set_rendering_stats_view_enabled = 142 };
enum { binding_operation_mln_map_set_style_image = 143 };
enum { binding_operation_mln_map_set_style_json = 144 };
enum { binding_operation_mln_map_set_style_light_json = 145 };
enum { binding_operation_mln_map_set_style_light_property = 146 };
enum { binding_operation_mln_map_set_style_source_volatile = 147 };
enum { binding_operation_mln_map_set_style_transition_options = 148 };
enum { binding_operation_mln_map_set_style_url = 149 };
enum { binding_operation_mln_map_set_tile_options = 150 };
enum { binding_operation_mln_map_set_viewport_options = 151 };
enum { binding_operation_mln_map_snapshot_get = 152 };
enum { binding_operation_mln_map_style_url = 153 };
enum { binding_operation_mln_map_tile_options_default = 154 };
enum { binding_operation_mln_map_update_camera = 155 };
enum { binding_operation_mln_map_viewport_options_default = 156 };
enum { binding_operation_mln_metal_borrowed_texture_attach = 157 };
enum { binding_operation_mln_metal_borrowed_texture_descriptor_default = 158 };
enum { binding_operation_mln_metal_borrowed_texture_set_target = 159 };
enum { binding_operation_mln_metal_owned_texture_attach = 160 };
enum { binding_operation_mln_metal_owned_texture_descriptor_default = 161 };
enum { binding_operation_mln_metal_surface_attach = 162 };
enum { binding_operation_mln_metal_surface_descriptor_default = 163 };
enum { binding_operation_mln_metal_surface_set_target = 164 };
enum { binding_operation_mln_network_status_get = 165 };
enum { binding_operation_mln_network_status_set = 166 };
enum { binding_operation_mln_opengl_borrowed_texture_attach = 167 };
enum { binding_operation_mln_opengl_borrowed_texture_descriptor_default = 168 };
enum { binding_operation_mln_opengl_borrowed_texture_set_target = 169 };
enum { binding_operation_mln_opengl_owned_texture_attach = 170 };
enum { binding_operation_mln_opengl_owned_texture_descriptor_default = 171 };
enum { binding_operation_mln_opengl_supported_context_provider_mask = 172 };
enum { binding_operation_mln_opengl_surface_attach = 173 };
enum { binding_operation_mln_opengl_surface_descriptor_default = 174 };
enum { binding_operation_mln_opengl_surface_set_target = 175 };
enum { binding_operation_mln_plugin_get_register_function_v1 = 176 };
enum { binding_operation_mln_premultiplied_rgba8_image_default = 177 };
enum { binding_operation_mln_projected_meters_for_lat_lng = 178 };
enum { binding_operation_mln_projection_mode_default = 179 };
enum { binding_operation_mln_render_frame_batch_count = 180 };
enum { binding_operation_mln_render_frame_batch_get = 181 };
enum { binding_operation_mln_render_frame_batch_release = 182 };
enum { binding_operation_mln_render_session_abandon = 183 };
enum { binding_operation_mln_render_session_acquire_frame = 184 };
enum { binding_operation_mln_render_session_attach_options_default = 185 };
enum { binding_operation_mln_render_session_barrier = 186 };
enum { binding_operation_mln_render_session_clear_data = 187 };
enum { binding_operation_mln_render_session_destroy = 188 };
enum { binding_operation_mln_render_session_detach = 189 };
enum { binding_operation_mln_render_session_dispose = 190 };
enum { binding_operation_mln_render_session_drain_frame_results = 191 };
enum { binding_operation_mln_render_session_dump_debug_logs = 192 };
enum { binding_operation_mln_render_session_get_capabilities = 193 };
enum { binding_operation_mln_render_session_get_snapshot = 194 };
enum { binding_operation_mln_render_session_projection_create = 195 };
enum { binding_operation_mln_render_session_query_feature_extensions = 196 };
enum { binding_operation_mln_render_session_query_rendered_features = 197 };
enum { binding_operation_mln_render_session_query_source_features = 198 };
enum { binding_operation_mln_render_session_reduce_memory_use = 199 };
enum { binding_operation_mln_render_session_request_frame = 200 };
enum { binding_operation_mln_render_session_resize = 201 };
enum { binding_operation_mln_render_session_service_driver_work = 202 };
enum { binding_operation_mln_rendered_feature_query_options_default = 203 };
enum { binding_operation_mln_rendered_query_geometry_box = 204 };
enum { binding_operation_mln_rendered_query_geometry_line_string = 205 };
enum { binding_operation_mln_rendered_query_geometry_point = 206 };
enum { binding_operation_mln_resource_request_cancelled = 207 };
enum { binding_operation_mln_resource_request_complete = 208 };
enum { binding_operation_mln_resource_request_release = 209 };
enum { binding_operation_mln_resource_request_set_cancel_callback = 210 };
enum { binding_operation_mln_resource_request_wait_until_retired = 211 };
enum { binding_operation_mln_resource_transform_response_set_url = 212 };
enum { binding_operation_mln_runtime_barrier = 213 };
enum { binding_operation_mln_runtime_clear_http_header_transform = 214 };
enum { binding_operation_mln_runtime_clear_resource_provider = 215 };
enum { binding_operation_mln_runtime_clear_resource_transform = 216 };
enum { binding_operation_mln_runtime_create = 217 };
enum { binding_operation_mln_runtime_dispose = 218 };
enum { binding_operation_mln_runtime_drain_events = 219 };
enum { binding_operation_mln_runtime_get_event_mask = 220 };
enum { binding_operation_mln_runtime_offline_region_create = 221 };
enum { binding_operation_mln_runtime_offline_region_delete = 222 };
enum { binding_operation_mln_runtime_offline_region_get = 223 };
enum { binding_operation_mln_runtime_offline_region_get_status = 224 };
enum { binding_operation_mln_runtime_offline_region_invalidate = 225 };
enum { binding_operation_mln_runtime_offline_region_set_download_state = 226 };
enum { binding_operation_mln_runtime_offline_region_set_observed = 227 };
enum { binding_operation_mln_runtime_offline_region_update_metadata = 228 };
enum { binding_operation_mln_runtime_offline_regions_list = 229 };
enum { binding_operation_mln_runtime_offline_regions_merge_database = 230 };
enum { binding_operation_mln_runtime_options_default = 231 };
enum { binding_operation_mln_runtime_release = 232 };
enum { binding_operation_mln_runtime_run_ambient_cache_operation = 233 };
enum { binding_operation_mln_runtime_set_event_mask = 234 };
enum { binding_operation_mln_runtime_set_http_header_transform = 235 };
enum { binding_operation_mln_runtime_set_maximum_ambient_cache_size = 236 };
enum { binding_operation_mln_runtime_set_resource_provider = 237 };
enum { binding_operation_mln_runtime_set_resource_transform = 238 };
enum { binding_operation_mln_source_feature_query_options_default = 239 };
enum { binding_operation_mln_style_image_info_default = 240 };
enum { binding_operation_mln_style_image_options_default = 241 };
enum { binding_operation_mln_style_tile_source_options_default = 242 };
enum { binding_operation_mln_style_transition_options_default = 243 };
enum { binding_operation_mln_supported_render_backend_mask = 244 };
enum { binding_operation_mln_texture_image_info_default = 245 };
enum { binding_operation_mln_texture_read_premultiplied_rgba8 = 246 };
enum { binding_operation_mln_vulkan_borrowed_texture_attach = 247 };
enum { binding_operation_mln_vulkan_borrowed_texture_descriptor_default = 248 };
enum { binding_operation_mln_vulkan_borrowed_texture_set_target = 249 };
enum { binding_operation_mln_vulkan_owned_texture_attach = 250 };
enum { binding_operation_mln_vulkan_owned_texture_descriptor_default = 251 };
enum { binding_operation_mln_vulkan_surface_attach = 252 };
enum { binding_operation_mln_vulkan_surface_descriptor_default = 253 };
enum { binding_operation_mln_vulkan_surface_set_target = 254 };
enum { binding_operation_mln_webgpu_borrowed_texture_attach = 255 };
enum { binding_operation_mln_webgpu_borrowed_texture_descriptor_default = 256 };
enum { binding_operation_mln_webgpu_borrowed_texture_set_target = 257 };
enum { binding_operation_mln_webgpu_owned_texture_attach = 258 };
enum { binding_operation_mln_webgpu_owned_texture_descriptor_default = 259 };
enum { binding_operation_mln_webgpu_surface_attach = 260 };
enum { binding_operation_mln_webgpu_surface_descriptor_default = 261 };
enum { binding_operation_mln_webgpu_surface_set_target = 262 };
#endif
