[tasks.build]
depends = ["//:ensure-native-library"]
run = 'swift build --scratch-path ".build/$MISE_ENV"'

[tasks.test]
depends = ["//:ensure-native-library"]
run = 'swift test --scratch-path ".build/$MISE_ENV"'

[tasks.ci]
depends = ["test"]
run = 'swift package describe --type json >/dev/null'
