// Generated by tools/bindgen. Do not edit.
package org.maplibre.nativeffi.internal.c

/**
 * The C functions the binding calls, over primitive carriers: an address or a 64-bit integer is a
 * Long, and a record C takes by value crosses as the address of a copy. A record C returns by value
 * is written to the trailing `returned` address.
 */
internal expect object C {
  fun mln_acquired_frame_dispose(frame: Long, outDiagnostic: Long): Int

  fun mln_acquired_frame_get_metal_texture(frame: Long, outFrame: Long, outDiagnostic: Long): Int

  fun mln_acquired_frame_get_opengl_texture(frame: Long, outFrame: Long, outDiagnostic: Long): Int

  fun mln_acquired_frame_get_producer_sync(frame: Long, outSync: Long, outDiagnostic: Long): Int

  fun mln_acquired_frame_get_result(frame: Long, outResult: Long, outDiagnostic: Long): Int

  fun mln_acquired_frame_get_vulkan_texture(frame: Long, outFrame: Long, outDiagnostic: Long): Int

  fun mln_acquired_frame_get_webgpu_texture(frame: Long, outFrame: Long, outDiagnostic: Long): Int

  fun mln_acquired_frame_release(frame: Long, consumerCompletion: Long, outDiagnostic: Long): Int

  fun mln_acquired_frame_view_begin(frame: Long, outScope: Long, outDiagnostic: Long): Int

  fun mln_acquired_frame_view_end(scope: Long): Unit

  fun mln_android_init(jniEnv: Long, jniClass: Long, context: Long, outDiagnostic: Long): Int

  fun mln_animation_options_default(returned: Long): Unit

  fun mln_bound_options_default(returned: Long): Unit

  fun mln_buffer_destroy(buffer: Long): Unit

  fun mln_buffer_get(buffer: Long, outView: Long, outDiagnostic: Long): Int

  fun mln_c_version(): Int

  fun mln_camera_delta_default(returned: Long): Unit

  fun mln_camera_fit_options_default(returned: Long): Unit

  fun mln_camera_options_default(returned: Long): Unit

  fun mln_camera_update_default(returned: Long): Unit

  fun mln_custom_geometry_source_options_default(returned: Long): Unit

  fun mln_custom_mvt_vector_source_options_default(returned: Long): Unit

  fun mln_event_batch_get(batch: Long, outView: Long, outDiagnostic: Long): Int

  fun mln_event_batch_release(batch: Long): Unit

  fun mln_frame_demand_default(returned: Long): Unit

  fun mln_free_camera_options_default(returned: Long): Unit

  fun mln_geojson_source_data_create(
    data: Long,
    options: Long,
    outData: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_geojson_source_data_destroy(data: Long): Unit

  fun mln_geojson_source_options_default(returned: Long): Unit

  fun mln_gpu_sync_default(returned: Long): Unit

  fun mln_http_header_transform_response_set(
    response: Long,
    name: Long,
    nameSize: Long,
    value: Long,
    valueSize: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_lat_lng_for_projected_meters(meters: Long, outCoordinate: Long, outDiagnostic: Long): Int

  fun mln_log_clear_callback(outDiagnostic: Long): Int

  fun mln_log_set_async_severity_mask(mask: Int, outDiagnostic: Long): Int

  fun mln_log_set_callback(
    callback: Long,
    userData: Long,
    releaseUserData: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_logical_extent_physical_size(
    extent: Long,
    outWidth: Long,
    outHeight: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_color_relief_layer(
    map: Long,
    layerId: Long,
    sourceId: Long,
    beforeLayerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_custom_geometry_source(
    map: Long,
    sourceId: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_custom_mvt_vector_source(
    map: Long,
    sourceId: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_geojson_source_data(
    map: Long,
    sourceId: Long,
    data: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_geojson_source_url(
    map: Long,
    sourceId: Long,
    url: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_hillshade_layer(
    map: Long,
    layerId: Long,
    sourceId: Long,
    beforeLayerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_image_source_image(
    map: Long,
    sourceId: Long,
    coordinates: Long,
    coordinateCount: Long,
    image: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_image_source_url(
    map: Long,
    sourceId: Long,
    coordinates: Long,
    coordinateCount: Long,
    url: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_location_indicator_layer(
    map: Long,
    layerId: Long,
    beforeLayerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_raster_dem_source_tiles(
    map: Long,
    sourceId: Long,
    tiles: Long,
    tileCount: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_raster_dem_source_url(
    map: Long,
    sourceId: Long,
    url: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_raster_source_tiles(
    map: Long,
    sourceId: Long,
    tiles: Long,
    tileCount: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_raster_source_url(
    map: Long,
    sourceId: Long,
    url: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_style_layer_json(
    map: Long,
    layerJson: Long,
    beforeLayerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_style_source_json(
    map: Long,
    sourceId: Long,
    sourceJson: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_vector_source_tiles(
    map: Long,
    sourceId: Long,
    tiles: Long,
    tileCount: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_add_vector_source_url(
    map: Long,
    sourceId: Long,
    url: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_apply_camera_delta(map: Long, delta: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_camera_for_geometry(
    map: Long,
    geometry: Long,
    fitOptions: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_camera_for_lat_lng_bounds(
    map: Long,
    bounds: Long,
    fitOptions: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_camera_for_lat_lngs(
    map: Long,
    coordinates: Long,
    coordinateCount: Long,
    fitOptions: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_camera_query(map: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_cancel_transitions(map: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_copy_layer_source_id(
    map: Long,
    layerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_copy_layer_source_layer(
    map: Long,
    layerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_copy_style_image_premultiplied_rgba8(
    map: Long,
    imageId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_copy_style_image_stretches(
    map: Long,
    imageId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_copy_style_source_attribution(
    map: Long,
    sourceId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_copy_style_source_url(
    map: Long,
    sourceId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_create(runtime: Long, options: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_dispose(map: Long, outDiagnostic: Long): Int

  fun mln_map_dump_debug_logs(map: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_get_feature_state(
    map: Long,
    selector: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_get_global_state(map: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_get_image_source_coordinates(
    map: Long,
    sourceId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_get_layer_filter(map: Long, layerId: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_get_layer_property(
    map: Long,
    layerId: Long,
    propertyName: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_get_style_image_info(
    map: Long,
    imageId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_get_style_layer_info(
    map: Long,
    layerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_get_style_layer_json(
    map: Long,
    layerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_get_style_light_property(
    map: Long,
    propertyName: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_get_style_source_info(
    map: Long,
    sourceId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_get_style_source_tile_urls(
    map: Long,
    sourceId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_get_style_transition_options(map: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_invalidate_custom_geometry_source_region(
    map: Long,
    sourceId: Long,
    bounds: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_invalidate_custom_geometry_source_tile(
    map: Long,
    sourceId: Long,
    tileId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_invalidate_custom_mvt_vector_source_tile(
    map: Long,
    sourceId: Long,
    tileId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_lat_lng_bounds_for_camera(
    map: Long,
    camera: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_lat_lng_bounds_for_camera_unwrapped(
    map: Long,
    camera: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_lat_lng_for_pixel(map: Long, point: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_lat_lng_for_pixel_unwrapped(
    map: Long,
    point: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_lat_lngs_for_pixels(
    map: Long,
    points: Long,
    pointCount: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_lat_lngs_for_pixels_unwrapped(
    map: Long,
    points: Long,
    pointCount: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_list_style_layer_ids(map: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_list_style_layers(map: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_list_style_source_ids(map: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_loaded_style_json(map: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_meters_per_pixel_at_latitude(
    map: Long,
    latitude: Double,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_move_style_layer(
    map: Long,
    layerId: Long,
    beforeLayerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_options_default(returned: Long): Unit

  fun mln_map_pixel_for_lat_lng(
    map: Long,
    coordinate: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_pixels_for_lat_lngs(
    map: Long,
    coordinates: Long,
    coordinateCount: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_projection_close(projection: Long, outDiagnostic: Long): Int

  fun mln_map_projection_create(map: Long, outProjection: Long, outDiagnostic: Long): Int

  fun mln_map_projection_get_camera(projection: Long, outCamera: Long, outDiagnostic: Long): Int

  fun mln_map_projection_lat_lng_for_pixel(
    projection: Long,
    point: Long,
    outCoordinate: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_projection_lat_lng_for_pixel_unwrapped(
    projection: Long,
    point: Long,
    outCoordinate: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_projection_meters_per_pixel_at_latitude(
    projection: Long,
    latitude: Double,
    outMetersPerPixel: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_projection_pixel_for_lat_lng(
    projection: Long,
    coordinate: Long,
    outPoint: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_projection_set_camera(projection: Long, camera: Long, outDiagnostic: Long): Int

  fun mln_map_projection_set_visible_coordinates(
    projection: Long,
    coordinates: Long,
    coordinateCount: Long,
    padding: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_projection_set_visible_geometry(
    projection: Long,
    geometry: Long,
    padding: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_release(map: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_remove_feature_state(
    map: Long,
    selector: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_remove_style_image(
    map: Long,
    imageId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_remove_style_layer(
    map: Long,
    layerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_remove_style_source(
    map: Long,
    sourceId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_request_repaint(map: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_request_still_image(map: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_resize(map: Long, extent: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_set_bounds(map: Long, options: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_set_custom_geometry_source_tile_data(
    map: Long,
    sourceId: Long,
    tileId: Long,
    data: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_custom_mvt_vector_source_tile_data(
    map: Long,
    sourceId: Long,
    tileId: Long,
    data: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_custom_mvt_vector_source_tile_error(
    map: Long,
    sourceId: Long,
    tileId: Long,
    message: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_debug_options(map: Long, options: Int, completion: Long, outDiagnostic: Long): Int

  fun mln_map_set_event_mask(map: Long, mask: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_set_feature_state(
    map: Long,
    selector: Long,
    state: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_free_camera_options(
    map: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_geojson_source_data(
    map: Long,
    sourceId: Long,
    data: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_geojson_source_synchronous_tiling(
    map: Long,
    sourceId: Long,
    enabled: Boolean,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_geojson_source_url(
    map: Long,
    sourceId: Long,
    url: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_global_state_property(
    map: Long,
    propertyName: Long,
    value: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_image_source_coordinates(
    map: Long,
    sourceId: Long,
    coordinates: Long,
    coordinateCount: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_image_source_image(
    map: Long,
    sourceId: Long,
    image: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_image_source_url(
    map: Long,
    sourceId: Long,
    url: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_layer_filter(
    map: Long,
    layerId: Long,
    filter: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_layer_max_zoom(
    map: Long,
    layerId: Long,
    maxZoom: Double,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_layer_min_zoom(
    map: Long,
    layerId: Long,
    minZoom: Double,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_layer_property(
    map: Long,
    layerId: Long,
    propertyName: Long,
    value: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_layer_source_id(
    map: Long,
    layerId: Long,
    sourceId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_layer_source_layer(
    map: Long,
    layerId: Long,
    sourceLayer: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_layer_visibility(
    map: Long,
    layerId: Long,
    visibility: Int,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_location_indicator_accuracy_radius(
    map: Long,
    layerId: Long,
    radius: Double,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_location_indicator_bearing(
    map: Long,
    layerId: Long,
    bearing: Double,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_location_indicator_image_name(
    map: Long,
    layerId: Long,
    imageKind: Int,
    imageId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_location_indicator_location(
    map: Long,
    layerId: Long,
    coordinate: Long,
    altitude: Double,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_projection_mode(map: Long, mode: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_set_rendering_stats_view_enabled(
    map: Long,
    enabled: Boolean,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_style_image(
    map: Long,
    imageId: Long,
    image: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_style_json(map: Long, json: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_set_style_light_json(
    map: Long,
    lightJson: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_style_light_property(
    map: Long,
    propertyName: Long,
    value: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_style_source_volatile(
    map: Long,
    sourceId: Long,
    isVolatile: Boolean,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_style_transition_options(
    map: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_set_style_url(map: Long, url: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_set_tile_options(map: Long, options: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_set_viewport_options(
    map: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_map_snapshot_get(map: Long, outSnapshot: Long, outDiagnostic: Long): Int

  fun mln_map_style_url(map: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_tile_options_default(returned: Long): Unit

  fun mln_map_update_camera(map: Long, update: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_map_viewport_options_default(returned: Long): Unit

  fun mln_metal_borrowed_texture_attach(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_metal_borrowed_texture_descriptor_default(returned: Long): Unit

  fun mln_metal_borrowed_texture_set_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_metal_owned_texture_attach(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_metal_owned_texture_descriptor_default(returned: Long): Unit

  fun mln_metal_surface_attach(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_metal_surface_descriptor_default(returned: Long): Unit

  fun mln_metal_surface_set_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_network_status_get(outStatus: Long, outDiagnostic: Long): Int

  fun mln_network_status_set(status: Int, outDiagnostic: Long): Int

  fun mln_opengl_borrowed_texture_attach(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_opengl_borrowed_texture_descriptor_default(returned: Long): Unit

  fun mln_opengl_borrowed_texture_set_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_opengl_owned_texture_attach(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_opengl_owned_texture_descriptor_default(returned: Long): Unit

  fun mln_opengl_supported_context_provider_mask(): Int

  fun mln_opengl_surface_attach(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_opengl_surface_descriptor_default(returned: Long): Unit

  fun mln_opengl_surface_set_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_plugin_get_register_function_v1(): Long

  fun mln_premultiplied_rgba8_image_default(returned: Long): Unit

  fun mln_projected_meters_for_lat_lng(coordinate: Long, outMeters: Long, outDiagnostic: Long): Int

  fun mln_projection_mode_default(returned: Long): Unit

  fun mln_render_frame_batch_count(batch: Long, outCount: Long, outDiagnostic: Long): Int

  fun mln_render_frame_batch_get(
    batch: Long,
    index: Long,
    outResult: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_render_frame_batch_release(batch: Long): Unit

  fun mln_render_session_abandon(session: Long, outResult: Long, outDiagnostic: Long): Int

  fun mln_render_session_acquire_frame(session: Long, outFrame: Long, outDiagnostic: Long): Int

  fun mln_render_session_attach_options_default(returned: Long): Unit

  fun mln_render_session_barrier(session: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_render_session_clear_data(session: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_render_session_destroy(session: Long, outDiagnostic: Long): Int

  fun mln_render_session_detach(session: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_render_session_dispose(session: Long, outDiagnostic: Long): Int

  fun mln_render_session_drain_frame_results(
    session: Long,
    outBatch: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_render_session_dump_debug_logs(session: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_render_session_get_capabilities(
    session: Long,
    outCapabilities: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_render_session_get_snapshot(session: Long, outSnapshot: Long, outDiagnostic: Long): Int

  fun mln_render_session_projection_create(
    session: Long,
    outProjection: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_render_session_query_feature_extensions(
    session: Long,
    sourceId: Long,
    feature: Long,
    extension: Long,
    extensionField: Long,
    arguments: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_render_session_query_rendered_features(
    session: Long,
    geometry: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_render_session_query_source_features(
    session: Long,
    sourceId: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_render_session_reduce_memory_use(
    session: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_render_session_request_frame(session: Long, demand: Long, outDiagnostic: Long): Int

  fun mln_render_session_resize(
    session: Long,
    extent: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_render_session_service_driver_work(
    session: Long,
    maxWork: Long,
    outServiced: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_rendered_feature_query_options_default(returned: Long): Unit

  fun mln_rendered_query_geometry_box(box: Long, returned: Long): Unit

  fun mln_rendered_query_geometry_line_string(points: Long, pointCount: Long, returned: Long): Unit

  fun mln_rendered_query_geometry_point(point: Long, returned: Long): Unit

  fun mln_resource_request_cancelled(handle: Long, outCancelled: Long, outDiagnostic: Long): Int

  fun mln_resource_request_complete(handle: Long, response: Long, outDiagnostic: Long): Int

  fun mln_resource_request_release(handle: Long): Unit

  fun mln_resource_request_set_cancel_callback(
    handle: Long,
    callback: Long,
    userData: Long,
    releaseUserData: Long,
    outCancelled: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_resource_request_wait_until_retired(handle: Long, outDiagnostic: Long): Int

  fun mln_resource_transform_response_set_url(
    response: Long,
    url: Long,
    urlSize: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_barrier(runtime: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_runtime_clear_http_header_transform(
    runtime: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_clear_resource_provider(runtime: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_runtime_clear_resource_transform(
    runtime: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_create(options: Long, outRuntime: Long, outDiagnostic: Long): Int

  fun mln_runtime_dispose(runtime: Long, outDiagnostic: Long): Int

  fun mln_runtime_drain_events(runtime: Long, outBatch: Long, outDiagnostic: Long): Int

  fun mln_runtime_get_event_mask(runtime: Long, outMask: Long, outDiagnostic: Long): Int

  fun mln_runtime_offline_region_create(
    runtime: Long,
    definition: Long,
    metadata: Long,
    metadataSize: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_offline_region_delete(
    runtime: Long,
    regionId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_offline_region_get(
    runtime: Long,
    regionId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_offline_region_get_status(
    runtime: Long,
    regionId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_offline_region_invalidate(
    runtime: Long,
    regionId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_offline_region_set_download_state(
    runtime: Long,
    regionId: Long,
    state: Int,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_offline_region_set_observed(
    runtime: Long,
    regionId: Long,
    observed: Boolean,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_offline_region_update_metadata(
    runtime: Long,
    regionId: Long,
    metadata: Long,
    metadataSize: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_offline_regions_list(runtime: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_runtime_offline_regions_merge_database(
    runtime: Long,
    sideDatabasePath: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_options_default(returned: Long): Unit

  fun mln_runtime_release(runtime: Long, completion: Long, outDiagnostic: Long): Int

  fun mln_runtime_run_ambient_cache_operation(
    runtime: Long,
    operation: Int,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_set_event_mask(runtime: Long, mask: Long, outDiagnostic: Long): Int

  fun mln_runtime_set_http_header_transform(
    runtime: Long,
    transform: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_set_maximum_ambient_cache_size(
    runtime: Long,
    size: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_set_resource_provider(
    runtime: Long,
    provider: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_runtime_set_resource_transform(
    runtime: Long,
    transform: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_source_feature_query_options_default(returned: Long): Unit

  fun mln_style_image_info_default(returned: Long): Unit

  fun mln_style_image_options_default(returned: Long): Unit

  fun mln_style_tile_source_options_default(returned: Long): Unit

  fun mln_style_transition_options_default(returned: Long): Unit

  fun mln_supported_render_backend_mask(): Int

  fun mln_texture_image_info_default(returned: Long): Unit

  fun mln_texture_read_premultiplied_rgba8(
    session: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_vulkan_borrowed_texture_attach(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_vulkan_borrowed_texture_descriptor_default(returned: Long): Unit

  fun mln_vulkan_borrowed_texture_set_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_vulkan_owned_texture_attach(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_vulkan_owned_texture_descriptor_default(returned: Long): Unit

  fun mln_vulkan_surface_attach(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_vulkan_surface_descriptor_default(returned: Long): Unit

  fun mln_vulkan_surface_set_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_webgpu_borrowed_texture_attach(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_webgpu_borrowed_texture_descriptor_default(returned: Long): Unit

  fun mln_webgpu_borrowed_texture_set_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_webgpu_owned_texture_attach(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_webgpu_owned_texture_descriptor_default(returned: Long): Unit

  fun mln_webgpu_surface_attach(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int

  fun mln_webgpu_surface_descriptor_default(returned: Long): Unit

  fun mln_webgpu_surface_set_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int
}
