// Generated by tools/bindgen. Do not edit.
package org.maplibre.nativeffi.internal.c

import org.maplibre.nativeffi.internal.memory.w

internal object CompletionLayout {
  val SIZEOF: Int = w(16, 32)
  val SIZE: Int = 0
  val CALLBACK: Int = w(4, 8)
  val USER_DATA: Int = w(8, 16)
  val RELEASE_USER_DATA: Int = w(12, 24)
}

internal object CompletionResultLayout {
  val SIZEOF: Int = w(40, 56)
  val SIZE: Int = 0
  val STATUS: Int = 4
  val DISPOSITION: Int = 8
  val VALUE_SIZE: Int = 12
  val GENERATION: Int = 16
  val DIAGNOSTIC: Int = 24
  val VALUE: Int = w(32, 40)
  val VALUE_COUNT: Int = w(36, 48)
}

internal object DiagnosticLayout {
  val SIZEOF: Int = 4100
  val SIZE: Int = 0
  val MESSAGE: Int = 4
}
