// Generated by tools/bindgen. Do not edit.
package org.maplibre.nativeffi.internal.c

import kotlin.jvm.JvmStatic
import org.maplibre.nativeffi.generated.*
import org.maplibre.nativeffi.internal.async.CompletionBridge
import org.maplibre.nativeffi.internal.callback.CallbackRoots
import org.maplibre.nativeffi.internal.callback.contain
import org.maplibre.nativeffi.internal.callback.upcall
import org.maplibre.nativeffi.internal.memory.*

/** The Kotlin side of each C function pointer the binding hands to native. */
internal object Upcalls {
  @JvmStatic
  fun completion(userData: Long, result: Long): Unit =
    contain("mln_completion_callback", Unit) { CompletionBridge.complete(userData, result) }

  @JvmStatic
  fun completionRelease(userData: Long): Unit =
    contain("mln_user_data_release", Unit) { CompletionBridge.release(userData) }

  @JvmStatic
  fun releaseRoot(userData: Long): Unit =
    contain("release_user_data", Unit) { CallbackRoots.release(userData) }

  @JvmStatic
  fun logHandlerCallback(
    userData: Long,
    severity: Int,
    event: Int,
    code: Long,
    message: Long,
  ): Int =
    upcall<LogHandler, Int>("mln_log_callback", userData, 0, setOf()) { value, scope ->
      value
        .callback(
          LogSeverity(severity.toUInt()),
          LogEvent(event.toUInt()),
          code,
          readCString(message),
        )
        .toInt()
    }

  @JvmStatic
  fun customGeometrySourceOptionsFetchTile(userData: Long, tileId: Long): Unit =
    upcall<CustomGeometrySourceOptions, Unit>(
      "mln_custom_source_tile_callback",
      userData,
      Unit,
      null,
    ) { value, scope ->
      val invoke = value.fetchTile ?: return@upcall Unit
      invoke(readCanonicalTileId(tileId))
    }

  @JvmStatic
  fun customGeometrySourceOptionsCancelTile(userData: Long, tileId: Long): Unit =
    upcall<CustomGeometrySourceOptions, Unit>(
      "mln_custom_source_tile_callback",
      userData,
      Unit,
      null,
    ) { value, scope ->
      val invoke = value.cancelTile ?: return@upcall Unit
      invoke(readCanonicalTileId(tileId))
    }

  @JvmStatic
  fun customMvtVectorSourceOptionsFetchTile(userData: Long, tileId: Long): Unit =
    upcall<CustomMvtVectorSourceOptions, Unit>(
      "mln_custom_source_tile_callback",
      userData,
      Unit,
      null,
    ) { value, scope ->
      val invoke = value.fetchTile ?: return@upcall Unit
      invoke(readCanonicalTileId(tileId))
    }

  @JvmStatic
  fun customMvtVectorSourceOptionsCancelTile(userData: Long, tileId: Long): Unit =
    upcall<CustomMvtVectorSourceOptions, Unit>(
      "mln_custom_source_tile_callback",
      userData,
      Unit,
      null,
    ) { value, scope ->
      val invoke = value.cancelTile ?: return@upcall Unit
      invoke(readCanonicalTileId(tileId))
    }

  @JvmStatic
  fun resourceRequestCancelHandlerCallback(userData: Long): Unit =
    upcall<ResourceRequestCancelHandler, Unit>(
      "mln_resource_request_cancel_callback",
      userData,
      Unit,
      setOf(
        "mln_resource_request_complete",
        "mln_resource_request_is_cancelled",
        "mln_resource_request_set_cancel_callback",
        "mln_resource_request_release",
      ),
      { it.owner },
    ) { value, scope ->
      value.callback()
    }

  @JvmStatic
  fun httpHeaderTransformCallback(userData: Long, kind: Int, url: Long, outResponse: Long): Int =
    upcall<HttpHeaderTransform, Int>(
      "mln_http_header_transform_callback",
      userData,
      -5,
      setOf("mln_http_header_transform_response_set_header"),
      { outResponse },
    ) { value, scope ->
      value.callback(
        ResourceKind(kind.toUInt()),
        readCString(url),
        HttpHeaderTransformResponse(outResponse, scope),
      )
      0
    }

  @JvmStatic
  fun resourceProviderCallback(userData: Long, request: Long, handle: Long): Int =
    upcall<ResourceProvider, Int>(
      "mln_resource_provider_callback",
      userData,
      0,
      setOf(
        "mln_resource_request_complete",
        "mln_resource_request_is_cancelled",
        "mln_resource_request_set_cancel_callback",
        "mln_resource_request_release",
      ),
      { handle },
    ) { value, scope ->
      val decisionOwner = ResourceRequestHandle(handle)
      decisionOwner.binding
        .decide(decisionOwner, "mln_resource_provider_callback") {
          value.callback(readResourceRequest(request), decisionOwner).rawValue
        }
        .toInt()
    }

  @JvmStatic
  fun resourceTransformCallback(userData: Long, kind: Int, url: Long, outResponse: Long): Int =
    upcall<ResourceTransform, Int>(
      "mln_resource_transform_callback",
      userData,
      -5,
      setOf("mln_resource_transform_response_set_url"),
      { outResponse },
    ) { value, scope ->
      value.callback(
        ResourceKind(kind.toUInt()),
        readCString(url),
        ResourceTransformResponse(outResponse, scope),
      )
      0
    }

  @JvmStatic
  fun wakeCallback(userData: Long): Unit =
    upcall<Wake, Unit>("mln_wake_callback", userData, Unit, null) { value, scope ->
      val invoke = value.callback ?: return@upcall Unit
      invoke()
    }

  @JvmStatic
  fun queueLockLock(userData: Long): Unit =
    upcall<QueueLock, Unit>("mln_queue_lock_callback", userData, Unit, setOf()) { value, scope ->
      val invoke = value.lock ?: return@upcall Unit
      invoke()
    }

  @JvmStatic
  fun queueLockUnlock(userData: Long): Unit =
    upcall<QueueLock, Unit>("mln_queue_lock_callback", userData, Unit, setOf()) { value, scope ->
      val invoke = value.unlock ?: return@upcall Unit
      invoke()
    }

  @JvmStatic
  fun cameraTransitionHandlerCallback(userData: Long, end: Long): Unit =
    upcall<CameraTransitionHandler, Unit>(
      "mln_camera_transition_end_callback",
      userData,
      Unit,
      null,
    ) { value, scope ->
      val invoke = value.callback ?: return@upcall Unit
      invoke(readCameraTransitionEnd(end))
    }
}

/** The C function pointer that calls each [Upcalls] method. */
internal expect object UpcallStubs {
  val completion: Long
  val completionRelease: Long
  val releaseRoot: Long
  val logHandlerCallback: Long
  val customGeometrySourceOptionsFetchTile: Long
  val customGeometrySourceOptionsCancelTile: Long
  val customMvtVectorSourceOptionsFetchTile: Long
  val customMvtVectorSourceOptionsCancelTile: Long
  val resourceRequestCancelHandlerCallback: Long
  val httpHeaderTransformCallback: Long
  val resourceProviderCallback: Long
  val resourceTransformCallback: Long
  val wakeCallback: Long
  val queueLockLock: Long
  val queueLockUnlock: Long
  val cameraTransitionHandlerCallback: Long
}
