[package]
name = "maplibre-native-ffi-python"
version = "0.0.0"
build = "build.rs"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib"]
test = false

[dependencies]
maplibre-native-ffi-core = { path = "../rust/crates/maplibre-native-ffi-core" }
maplibre-native-ffi-sys = { path = "../rust/crates/maplibre-native-ffi-sys" }
pyo3 = { version = "0.29.0", features = ["abi3-py314"] }
