"""The generate command's exit status drives CI, so each flag's result matters."""

import contextlib
import io
import shutil
import sys
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest.mock import patch

from support import ROOT, parse, protocol_header

from tools.bindgen import __main__ as cli

# Formatting belongs to the language tools. These tests keep emitted text as is.
UNFORMATTED = patch.object(cli, "format_outputs", lambda outputs, _staging: outputs)
UNFORMATTED_HEADER = patch.object(
    cli, "dprint_format", lambda source, _extension: source
)


class GenerateCommandTests(unittest.TestCase):
    def generate(self, root, groups, *, check=False, require_complete=False):
        """Run generate under `root`, returning its status and diagnostics."""
        errors = io.StringIO()
        with (
            UNFORMATTED,
            contextlib.redirect_stdout(io.StringIO()),
            contextlib.redirect_stderr(errors),
        ):
            status = cli.generate(
                parse(groups=groups), check, require_complete, root=root
            )
        return status, errors.getvalue()

    def test_check_passes_only_when_committed_output_matches(self):
        with TemporaryDirectory() as directory:
            root = Path(directory)
            self.assertEqual(self.generate(root, ("keywords",)), (0, ""))
            self.assertEqual(self.generate(root, ("keywords",), check=True), (0, ""))

            generated = root / "bindings/go/generated_api.go"
            generated.write_text(generated.read_text() + "// edited\n")
            status, errors = self.generate(root, ("keywords",), check=True)
            self.assertEqual(status, 1)
            self.assertIn("regeneration required: bindings/go/generated_api.go", errors)
            # A check reports differences without repairing them.
            self.assertTrue(generated.read_text().endswith("// edited\n"))

            self.assertEqual(self.generate(root, ("keywords",)), (0, ""))
            self.assertFalse(generated.read_text().endswith("// edited\n"))
            self.assertEqual(self.generate(root, ("keywords",), check=True), (0, ""))

    def test_previous_outputs_that_are_no_longer_generated_are_stale(self):
        # The conventions group adds a record that the dotnet emitter writes
        # to a file of its own.
        removed = "bindings/dotnet/src/Maplibre.NativeFfi/Api/Label.g.cs"
        # Only the previous run's output list decides what is stale, never a
        # file's header line.
        handwritten = "bindings/rust/src/handwritten.rs"
        with TemporaryDirectory() as directory:
            root = Path(directory)
            self.assertEqual(self.generate(root, ("keywords", "conventions"))[0], 0)
            self.assertTrue((root / removed).is_file())
            (root / handwritten).parent.mkdir(parents=True, exist_ok=True)
            (root / handwritten).write_text(
                "// Generated by tools/bindgen; DO NOT EDIT.\n"
            )

            status, errors = self.generate(root, ("keywords",), check=True)
            self.assertEqual(status, 1)
            self.assertIn(f"stale generated file: {removed}", errors)
            self.assertNotIn(handwritten, errors)
            self.assertTrue((root / removed).is_file())

            self.assertEqual(self.generate(root, ("keywords",)), (0, ""))
            self.assertFalse((root / removed).exists())
            self.assertTrue((root / handwritten).is_file())
            self.assertEqual(self.generate(root, ("keywords",), check=True), (0, ""))

    def test_a_conflicted_output_list_keeps_the_outputs_of_every_side(self):
        # A merge leaves conflict markers in the report whenever two branches
        # change its output list, and generation then resolves the conflict.
        removed = "bindings/dotnet/src/Maplibre.NativeFfi/Api/Label.g.cs"
        theirs = "bindings/rust/src/theirs.rs"
        with TemporaryDirectory() as directory:
            root = Path(directory)
            self.assertEqual(self.generate(root, ("keywords", "conventions"))[0], 0)
            (root / theirs).parent.mkdir(parents=True, exist_ok=True)
            (root / theirs).write_text("// generated on the other branch\n")
            manifest = root / cli.COVERAGE
            entry = f'    "{removed}",\n'
            self.assertIn(entry, manifest.read_text())
            manifest.write_text(
                manifest.read_text().replace(
                    entry,
                    f'<<<<<<< ours\n{entry}=======\n    "{theirs}",\n>>>>>>> theirs\n',
                )
            )

            status, errors = self.generate(root, ("keywords",), check=True)
            self.assertEqual(status, 1)
            self.assertIn(f"stale generated file: {removed}", errors)
            self.assertIn(f"stale generated file: {theirs}", errors)

            self.assertEqual(self.generate(root, ("keywords",)), (0, ""))
            self.assertFalse((root / removed).exists())
            self.assertFalse((root / theirs).exists())
            self.assertEqual(self.generate(root, ("keywords",), check=True), (0, ""))

    def test_an_unreadable_output_list_fails_before_writing_output(self):
        with TemporaryDirectory() as directory:
            root = Path(directory)
            manifest = root / cli.COVERAGE
            manifest.parent.mkdir(parents=True)
            manifest.write_text("<<<<<<< ours\n{}\n=======\n>>>>>>> theirs\n")
            with self.assertRaisesRegex(cli.ModelError, "resolve or restore"):
                self.generate(root, ("keywords",))
            self.assertEqual(sorted(root.rglob("*")), [manifest.parent, manifest])

    def test_require_complete_fails_while_a_declaration_is_unsupported(self):
        # The values group declares a nullable counted input that some emitters
        # report unsupported.
        with TemporaryDirectory() as directory:
            root = Path(directory)
            self.assertEqual(self.generate(root, ("values",))[0], 0)
            status, _ = self.generate(root, ("values",), require_complete=True)
            self.assertEqual(status, 1)
            status, _ = self.generate(root, ("keywords",), require_complete=True)
            self.assertEqual(status, 0)

    def test_one_run_settles_a_stale_generated_header(self):
        # Outputs declare the generated header's contents, so a run that read
        # the stale header would leave outputs that the next check rejects.
        with TemporaryDirectory() as directory:
            root = Path(directory)
            include = root / "include"
            shutil.copytree(ROOT / "include", include)
            header = include / cli.native_capture.HEADER
            header.write_text(
                header.read_text().replace(
                    "} mln_adapter_deferred_callback;",
                    "  MLN_ADAPTER_DEFERRED_STALE = 7U,\n} mln_adapter_deferred_callback;",
                )
            )
            renders = []
            generate = cli.generate

            def run(*options):
                arguments = ["bindgen", "generate", "--include", str(include)]
                with (
                    UNFORMATTED,
                    UNFORMATTED_HEADER,
                    patch.object(sys, "argv", [*arguments, *options]),
                    patch.object(
                        cli,
                        "generate",
                        lambda *args: (
                            renders.append(args) or generate(*args, root=root)
                        ),
                    ),
                    contextlib.redirect_stdout(io.StringIO()),
                ):
                    return cli.main()

            self.assertEqual(run(), 0)
            self.assertEqual(len(renders), 1)
            self.assertEqual(run("--check"), 0)

    def test_invalid_headers_fail_before_writing_output(self):
        with TemporaryDirectory() as directory:
            include = Path(directory)
            (include / "api.h").write_text(
                protocol_header("mln_typo mln_broken(void);")
            )
            arguments = ["bindgen", "generate", "--include", str(include), "--check"]
            errors = io.StringIO()
            with (
                patch.object(sys, "argv", arguments),
                patch.object(cli, "generate") as generate,
                contextlib.redirect_stderr(errors),
            ):
                self.assertEqual(cli.main(), 1)
            generate.assert_not_called()
            self.assertIn("unknown type name", errors.getvalue())


if __name__ == "__main__":
    unittest.main()
