"""The generate command's exit status drives CI, so each flag's result matters."""

import contextlib
import io
import sys
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest.mock import patch

from support import parse, protocol_header

from tools.bindgen import __main__ as cli

# Formatting belongs to the language tools. These tests keep emitted text as is.
UNFORMATTED = patch.object(cli, "format_outputs", lambda outputs, _staging: outputs)


class GenerateCommandTests(unittest.TestCase):
    def generate(self, root, groups, *, check=False, require_complete=False):
        """Run generate under `root`, returning its status and diagnostics."""
        errors = io.StringIO()
        with (
            UNFORMATTED,
            contextlib.redirect_stdout(io.StringIO()),
            contextlib.redirect_stderr(errors),
        ):
            status = cli.generate(
                parse(groups=groups), check, require_complete, root=root
            )
        return status, errors.getvalue()

    def test_check_passes_only_when_committed_output_matches(self):
        with TemporaryDirectory() as directory:
            root = Path(directory)
            self.assertEqual(self.generate(root, ("keywords",)), (0, ""))
            self.assertEqual(self.generate(root, ("keywords",), check=True), (0, ""))

            generated = root / "bindings/go/generated_api.go"
            generated.write_text(generated.read_text() + "// edited\n")
            stale = root / "bindings/rust/removed.rs"
            stale.write_text("// Generated by tools/bindgen; DO NOT EDIT.\n")
            status, errors = self.generate(root, ("keywords",), check=True)
            self.assertEqual(status, 1)
            self.assertIn("regeneration required: bindings/go/generated_api.go", errors)
            self.assertIn("stale generated file: bindings/rust/removed.rs", errors)
            # A check reports differences without repairing them.
            self.assertTrue(generated.read_text().endswith("// edited\n"))
            self.assertTrue(stale.exists())

            self.assertEqual(self.generate(root, ("keywords",)), (0, ""))
            self.assertFalse(generated.read_text().endswith("// edited\n"))
            self.assertFalse(stale.exists())
            self.assertEqual(self.generate(root, ("keywords",), check=True), (0, ""))

    def test_require_complete_fails_while_a_declaration_is_unsupported(self):
        # Some emitters cannot yet represent a nullable counted input.
        with TemporaryDirectory() as directory:
            root = Path(directory)
            self.assertEqual(self.generate(root, ("values",))[0], 0)
            status, _ = self.generate(root, ("values",), require_complete=True)
            self.assertEqual(status, 1)
            status, _ = self.generate(root, ("keywords",), require_complete=True)
            self.assertEqual(status, 0)

    def test_invalid_headers_fail_before_writing_output(self):
        with TemporaryDirectory() as directory:
            include = Path(directory)
            (include / "api.h").write_text(
                protocol_header("mln_typo mln_broken(void);")
            )
            arguments = ["bindgen", "generate", "--include", str(include), "--check"]
            errors = io.StringIO()
            with (
                patch.object(sys, "argv", arguments),
                patch.object(cli, "generate") as generate,
                contextlib.redirect_stderr(errors),
            ):
                self.assertEqual(cli.main(), 1)
            generate.assert_not_called()
            self.assertIn("unknown type name", errors.getvalue())


if __name__ == "__main__":
    unittest.main()
