from collections.abc import Callable, Sequence
from typing import Any, TypeAlias

# PyO3 currently documents hand-maintained .pyi files as the stable path for
# typing extension modules, while generated stubs remain under active
# development and only support inline Rust modules. This module is still exposed
# through a function-style #[pymodule], so keep this stub explicit until we can
# evaluate a generated-stub workflow.
# https://pyo3.rs/main/python-typing-hints
# https://pyo3.rs/main/type-stub

_Point: TypeAlias = tuple[float, float]
_Vec3: TypeAlias = tuple[float, float, float]
_Quat: TypeAlias = tuple[float, float, float, float]
_Insets: TypeAlias = tuple[float, float, float, float]
_Bounds: TypeAlias = tuple[_Point, _Point]
_Animation: TypeAlias = tuple[float | None, float | None, float | None, _Insets | None]
_WireDict: TypeAlias = dict[str, Any]

class _RuntimeHandle:
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def run_once(self) -> None: ...
    def run_ambient_cache_operation_start(self, operation: int) -> int: ...
    def offline_region_create_start(
        self, definition: object, metadata: bytes
    ) -> int: ...
    def offline_region_get_start(self, region_id: int) -> int: ...
    def offline_regions_list_start(self) -> int: ...
    def offline_regions_merge_database_start(self, side_database_path: str) -> int: ...
    def offline_region_update_metadata_start(
        self, region_id: int, metadata: bytes
    ) -> int: ...
    def offline_region_get_status_start(self, region_id: int) -> int: ...
    def offline_region_set_observed_start(
        self, region_id: int, observed: bool
    ) -> int: ...
    def offline_region_set_download_state_start(
        self, region_id: int, state: int
    ) -> int: ...
    def offline_region_invalidate_start(self, region_id: int) -> int: ...
    def offline_region_delete_start(self, region_id: int) -> int: ...
    def offline_region_create_take_result(self, operation_id: int) -> _WireDict: ...
    def offline_region_get_take_result(self, operation_id: int) -> _WireDict | None: ...
    def offline_regions_list_take_result(
        self, operation_id: int
    ) -> list[_WireDict]: ...
    def offline_regions_merge_database_take_result(
        self, operation_id: int
    ) -> list[_WireDict]: ...
    def offline_region_update_metadata_take_result(
        self, operation_id: int
    ) -> _WireDict: ...
    def offline_region_get_status_take_result(self, operation_id: int) -> _WireDict: ...
    def offline_operation_discard(self, operation_id: int) -> None: ...
    def set_resource_provider(
        self,
        callback: Callable[[_WireDict, "_ResourceRequestHandle"], int],
        max_pending_callbacks: int,
    ) -> None: ...
    def set_resource_transform(
        self, callback: Callable[[_WireDict], str | None], max_pending_callbacks: int
    ) -> None: ...
    def clear_resource_transform(self) -> None: ...
    def poll_event(self) -> _WireDict | None: ...

class _MapHandle:
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def address(self) -> int: ...
    def request_repaint(self) -> None: ...
    def request_still_image(self) -> None: ...
    def dump_debug_logs(self) -> None: ...
    def set_debug_options(self, options: int) -> None: ...
    def get_debug_options(self) -> int: ...
    def set_rendering_stats_view_enabled(self, enabled: bool) -> None: ...
    def get_rendering_stats_view_enabled(self) -> bool: ...
    def is_fully_loaded(self) -> bool: ...
    def get_viewport_options(self) -> _WireDict: ...
    def set_viewport_options(
        self,
        north_orientation: int | None,
        constrain_mode: int | None,
        viewport_mode: int | None,
        frustum_offset: _Insets | None,
    ) -> None: ...
    def get_tile_options(self) -> _WireDict: ...
    def set_tile_options(
        self,
        prefetch_zoom_delta: int | None,
        lod_min_radius: float | None,
        lod_scale: float | None,
        lod_pitch_threshold: float | None,
        lod_zoom_shift: float | None,
        lod_mode: int | None,
    ) -> None: ...
    def create_projection(self) -> "_MapProjectionHandle": ...
    def set_style_url(self, url: str) -> None: ...
    def set_style_json(self, json: str) -> None: ...
    def get_camera(self) -> _WireDict: ...
    def jump_to(
        self,
        center: _Point | None,
        zoom: float | None,
        bearing: float | None,
        pitch: float | None,
        center_altitude: float | None,
        padding: _Insets | None,
        anchor: _Point | None,
        roll: float | None,
        field_of_view: float | None,
    ) -> None: ...
    def ease_to(
        self,
        center: _Point | None,
        zoom: float | None,
        bearing: float | None,
        pitch: float | None,
        center_altitude: float | None,
        padding: _Insets | None,
        anchor: _Point | None,
        roll: float | None,
        field_of_view: float | None,
        animation: _Animation | None,
    ) -> None: ...
    def fly_to(
        self,
        center: _Point | None,
        zoom: float | None,
        bearing: float | None,
        pitch: float | None,
        center_altitude: float | None,
        padding: _Insets | None,
        anchor: _Point | None,
        roll: float | None,
        field_of_view: float | None,
        animation: _Animation | None,
    ) -> None: ...
    def camera_for_lat_lng_bounds(
        self,
        southwest: _Point,
        northeast: _Point,
        fit_padding: _Insets | None,
        fit_bearing: float | None,
        fit_pitch: float | None,
    ) -> _WireDict: ...
    def camera_for_lat_lngs(
        self,
        coordinates: Sequence[_Point],
        fit_padding: _Insets | None,
        fit_bearing: float | None,
        fit_pitch: float | None,
    ) -> _WireDict: ...
    def camera_for_geometry(
        self,
        geometry: object,
        fit_padding: _Insets | None,
        fit_bearing: float | None,
        fit_pitch: float | None,
    ) -> _WireDict: ...
    def lat_lng_bounds_for_camera(
        self,
        center: _Point | None,
        zoom: float | None,
        bearing: float | None,
        pitch: float | None,
        center_altitude: float | None,
        padding: _Insets | None,
        anchor: _Point | None,
        roll: float | None,
        field_of_view: float | None,
        unwrapped: bool,
    ) -> _WireDict: ...
    def get_bounds(self) -> _WireDict: ...
    def set_bounds(
        self,
        bounds: _Bounds | None,
        min_zoom: float | None,
        max_zoom: float | None,
        min_pitch: float | None,
        max_pitch: float | None,
    ) -> None: ...
    def move_by(self, delta_x: float, delta_y: float) -> None: ...
    def move_by_animated(
        self, delta_x: float, delta_y: float, animation: _Animation | None
    ) -> None: ...
    def scale_by(self, scale: float, anchor: _Point | None) -> None: ...
    def scale_by_animated(
        self, scale: float, anchor: _Point | None, animation: _Animation | None
    ) -> None: ...
    def rotate_by(self, first: _Point, second: _Point) -> None: ...
    def rotate_by_animated(
        self, first: _Point, second: _Point, animation: _Animation | None
    ) -> None: ...
    def pitch_by(self, pitch: float) -> None: ...
    def pitch_by_animated(self, pitch: float, animation: _Animation | None) -> None: ...
    def cancel_transitions(self) -> None: ...
    def get_free_camera_options(self) -> _WireDict: ...
    def set_free_camera_options(
        self, position: _Vec3 | None, orientation: _Quat | None
    ) -> None: ...
    def get_projection_mode(self) -> _WireDict: ...
    def set_projection_mode(
        self, axonometric: bool | None, x_skew: float | None, y_skew: float | None
    ) -> None: ...
    def pixel_for_lat_lng(self, latitude: float, longitude: float) -> _WireDict: ...
    def lat_lng_for_pixel(self, x: float, y: float) -> _WireDict: ...
    def pixels_for_lat_lngs(self, coordinates: Sequence[_Point]) -> list[_WireDict]: ...
    def lat_lngs_for_pixels(self, points: Sequence[_Point]) -> list[_WireDict]: ...
    def add_style_source_json(self, source_id: str, source_json: object) -> None: ...
    def add_geojson_source_url(self, source_id: str, url: str) -> None: ...
    def add_geojson_source_data(self, source_id: str, data: object) -> None: ...
    def set_geojson_source_url(self, source_id: str, url: str) -> None: ...
    def set_geojson_source_data(self, source_id: str, data: object) -> None: ...
    def add_vector_source_url(
        self,
        source_id: str,
        url: str,
        min_zoom: float | None,
        max_zoom: float | None,
        attribution: str | None,
        scheme: int | None,
        bounds: _Bounds | None,
        tile_size: int | None,
        vector_encoding: int | None,
        raster_dem_encoding: int | None,
    ) -> None: ...
    def add_raster_source_url(
        self,
        source_id: str,
        url: str,
        min_zoom: float | None,
        max_zoom: float | None,
        attribution: str | None,
        scheme: int | None,
        bounds: _Bounds | None,
        tile_size: int | None,
        vector_encoding: int | None,
        raster_dem_encoding: int | None,
    ) -> None: ...
    def add_raster_dem_source_url(
        self,
        source_id: str,
        url: str,
        min_zoom: float | None,
        max_zoom: float | None,
        attribution: str | None,
        scheme: int | None,
        bounds: _Bounds | None,
        tile_size: int | None,
        vector_encoding: int | None,
        raster_dem_encoding: int | None,
    ) -> None: ...
    def add_vector_source_tiles(
        self,
        source_id: str,
        tiles: Sequence[str],
        min_zoom: float | None,
        max_zoom: float | None,
        attribution: str | None,
        scheme: int | None,
        bounds: _Bounds | None,
        tile_size: int | None,
        vector_encoding: int | None,
        raster_dem_encoding: int | None,
    ) -> None: ...
    def add_raster_source_tiles(
        self,
        source_id: str,
        tiles: Sequence[str],
        min_zoom: float | None,
        max_zoom: float | None,
        attribution: str | None,
        scheme: int | None,
        bounds: _Bounds | None,
        tile_size: int | None,
        vector_encoding: int | None,
        raster_dem_encoding: int | None,
    ) -> None: ...
    def add_raster_dem_source_tiles(
        self,
        source_id: str,
        tiles: Sequence[str],
        min_zoom: float | None,
        max_zoom: float | None,
        attribution: str | None,
        scheme: int | None,
        bounds: _Bounds | None,
        tile_size: int | None,
        vector_encoding: int | None,
        raster_dem_encoding: int | None,
    ) -> None: ...
    def remove_style_source(self, source_id: str) -> bool: ...
    def style_source_exists(self, source_id: str) -> bool: ...
    def get_style_source_type(self, source_id: str) -> int | None: ...
    def get_style_source_info(self, source_id: str) -> _WireDict | None: ...
    def list_style_source_ids(self) -> list[str]: ...
    def add_hillshade_layer(
        self, layer_id: str, source_id: str, before_layer_id: str | None
    ) -> None: ...
    def add_color_relief_layer(
        self, layer_id: str, source_id: str, before_layer_id: str | None
    ) -> None: ...
    def add_location_indicator_layer(
        self, layer_id: str, before_layer_id: str | None
    ) -> None: ...
    def set_location_indicator_location(
        self, layer_id: str, latitude: float, longitude: float, altitude: float
    ) -> None: ...
    def set_location_indicator_bearing(self, layer_id: str, bearing: float) -> None: ...
    def set_location_indicator_accuracy_radius(
        self, layer_id: str, radius: float
    ) -> None: ...
    def set_location_indicator_image_name(
        self, layer_id: str, image_kind: int, image_id: str
    ) -> None: ...
    def add_style_layer_json(
        self, layer_json: object, before_layer_id: str | None
    ) -> None: ...
    def get_style_layer_json(self, layer_id: str) -> object | None: ...
    def set_style_light_json(self, light_json: object) -> None: ...
    def set_style_light_property(self, property_name: str, value: object) -> None: ...
    def get_style_light_property(self, property_name: str) -> object | None: ...
    def set_layer_property(
        self, layer_id: str, property_name: str, value: object
    ) -> None: ...
    def get_layer_property(
        self, layer_id: str, property_name: str
    ) -> object | None: ...
    def set_layer_filter(self, layer_id: str, filter: object | None) -> None: ...
    def get_layer_filter(self, layer_id: str) -> object | None: ...
    def remove_style_layer(self, layer_id: str) -> bool: ...
    def style_layer_exists(self, layer_id: str) -> bool: ...
    def get_style_layer_type(self, layer_id: str) -> str | None: ...
    def list_style_layer_ids(self) -> list[str]: ...
    def move_style_layer(self, layer_id: str, before_layer_id: str | None) -> None: ...
    def set_style_image(
        self,
        image_id: str,
        width: int,
        height: int,
        stride: int,
        pixels: bytes,
        pixel_ratio: float | None,
        sdf: bool | None,
    ) -> None: ...
    def remove_style_image(self, image_id: str) -> bool: ...
    def style_image_exists(self, image_id: str) -> bool: ...
    def get_style_image_info(self, image_id: str) -> _WireDict | None: ...
    def copy_style_image_premultiplied_rgba8(
        self, image_id: str
    ) -> _WireDict | None: ...
    def add_image_source_url(
        self, source_id: str, coordinates: Sequence[_Point], url: str
    ) -> None: ...
    def add_image_source_image(
        self,
        source_id: str,
        coordinates: Sequence[_Point],
        width: int,
        height: int,
        stride: int,
        pixels: bytes,
    ) -> None: ...
    def set_image_source_url(self, source_id: str, url: str) -> None: ...
    def set_image_source_image(
        self, source_id: str, width: int, height: int, stride: int, pixels: bytes
    ) -> None: ...
    def set_image_source_coordinates(
        self, source_id: str, coordinates: Sequence[_Point]
    ) -> None: ...
    def get_image_source_coordinates(
        self, source_id: str
    ) -> list[_WireDict] | None: ...
    def add_custom_geometry_source(
        self,
        source_id: str,
        max_queued_events: int,
        min_zoom: float | None,
        max_zoom: float | None,
        tolerance: float | None,
        tile_size: int | None,
        buffer: int | None,
        clip: bool | None,
        wrap: bool | None,
        has_cancel_tile: bool,
    ) -> "_CustomGeometrySourceHandle": ...
    def set_custom_geometry_source_tile_data(
        self, source_id: str, z: int, x: int, y: int, data: object
    ) -> None: ...
    def invalidate_custom_geometry_source_tile(
        self, source_id: str, z: int, x: int, y: int
    ) -> None: ...
    def invalidate_custom_geometry_source_region(
        self, source_id: str, southwest: _Point, northeast: _Point
    ) -> None: ...

class _MapProjectionHandle:
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def get_camera(self) -> _WireDict: ...
    def set_camera(
        self,
        center: _Point | None,
        zoom: float | None,
        bearing: float | None,
        pitch: float | None,
        center_altitude: float | None,
        padding: _Insets | None,
        anchor: _Point | None,
        roll: float | None,
        field_of_view: float | None,
    ) -> None: ...
    def set_visible_coordinates(
        self, coordinates: Sequence[_Point], padding: _Insets
    ) -> None: ...
    def set_visible_geometry(self, geometry: object, padding: _Insets) -> None: ...
    def pixel_for_lat_lng(self, latitude: float, longitude: float) -> _WireDict: ...
    def lat_lng_for_pixel(self, x: float, y: float) -> _WireDict: ...

class _RenderSessionHandle:
    @property
    def closed(self) -> bool: ...
    @property
    def detached(self) -> bool: ...
    def close(self) -> None: ...
    def resize(self, width: int, height: int, scale_factor: float) -> None: ...
    def render_update(self) -> None: ...
    def detach(self) -> "_DetachedRenderSessionHandle": ...
    def reduce_memory_use(self) -> None: ...
    def clear_data(self) -> None: ...
    def dump_debug_logs(self) -> None: ...
    def query_rendered_features(
        self, geometry: object, layer_ids: Sequence[str] | None, filter: object
    ) -> list[_WireDict]: ...
    def query_source_features(
        self, source_id: str, source_layer_ids: Sequence[str] | None, filter: object
    ) -> list[_WireDict]: ...
    def query_feature_extensions(
        self,
        source_id: str,
        feature: object,
        extension: str,
        extension_field: str,
        arguments: object,
    ) -> _WireDict: ...
    def set_feature_state(
        self,
        source_id: str,
        source_layer_id: str | None,
        feature_id: str | None,
        state_key: str | None,
        state_value: object,
    ) -> None: ...
    def get_feature_state(
        self,
        source_id: str,
        source_layer_id: str | None,
        feature_id: str | None,
        state_key: str | None,
    ) -> object: ...
    def remove_feature_state(
        self,
        source_id: str,
        source_layer_id: str | None,
        feature_id: str | None,
        state_key: str | None,
    ) -> None: ...
    def texture_image_info(self) -> _WireDict: ...
    def read_premultiplied_rgba8(self) -> _WireDict: ...
    def read_premultiplied_rgba8_into(self, buffer: object) -> _WireDict: ...
    def acquire_metal_owned_texture_frame(self) -> "_MetalOwnedTextureFrameHandle": ...
    def acquire_vulkan_owned_texture_frame(
        self,
    ) -> "_VulkanOwnedTextureFrameHandle": ...
    def acquire_opengl_owned_texture_frame(
        self,
    ) -> "_OpenGLOwnedTextureFrameHandle": ...

class _DetachedRenderSessionHandle:
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...

class _MetalOwnedTextureFrameHandle:
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def frame(self) -> _WireDict: ...
    def texture_address(self) -> int: ...
    def device_address(self) -> int: ...

class _VulkanOwnedTextureFrameHandle:
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def frame(self) -> _WireDict: ...
    def image_address(self) -> int: ...
    def image_view_address(self) -> int: ...
    def device_address(self) -> int: ...

class _OpenGLOwnedTextureFrameHandle:
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def frame(self) -> _WireDict: ...
    def texture(self) -> int: ...

class _ResourceRequestHandle:
    def validate_completion_response(self, response: object) -> None: ...
    def complete(self, response: object) -> None: ...
    def is_cancelled(self) -> bool: ...
    def close(self) -> None: ...

class _LogReceiver:
    @property
    def dropped_record_count(self) -> int: ...
    def poll_record(self) -> _WireDict | None: ...

class _CustomGeometrySourceHandle:
    @property
    def closed(self) -> bool: ...
    @property
    def dropped_event_count(self) -> int: ...
    def close(self) -> None: ...
    def poll_event(self) -> _WireDict | None: ...
    def push_fetch_for_test(self, z: int, x: int, y: int) -> None: ...
    def push_cancel_for_test(self, z: int, x: int, y: int) -> None: ...

def expected_c_abi_version() -> int: ...
def c_version() -> int: ...
def supported_render_backends_raw() -> int: ...
def supported_opengl_context_providers_raw() -> int: ...
def network_status_raw() -> int: ...
def set_network_status_raw(raw_status: int) -> None: ...
def set_network_status_raw_unchecked_for_test(raw_status: int) -> None: ...
def status_error_for_test(raw_status: int, diagnostic: str) -> None: ...
def status_error_after_support_call_for_test(
    raw_status: int, diagnostic: str
) -> None: ...
def create_runtime_with_abi_version_for_test(
    actual_abi_version: int,
    asset_path: str | None,
    cache_path: str | None,
    maximum_cache_size: int | None,
) -> _RuntimeHandle: ...
def runtime_event_payload_wire_shapes_for_test() -> dict[str, _WireDict]: ...
def projected_meters_for_lat_lng(latitude: float, longitude: float) -> _WireDict: ...
def lat_lng_for_projected_meters(northing: float, easting: float) -> _WireDict: ...
def set_log_callback(max_queued_records: int, consume: bool) -> _LogReceiver: ...
def clear_log_callback() -> None: ...
def set_async_log_severity_mask(mask: int) -> None: ...
def create_runtime(
    asset_path: str | None, cache_path: str | None, maximum_cache_size: int | None
) -> _RuntimeHandle: ...
def create_map(
    runtime: _RuntimeHandle, width: int, height: int, scale_factor: float, map_mode: int
) -> _MapHandle: ...
def attach_metal_surface(
    map: _MapHandle,
    width: int,
    height: int,
    scale_factor: float,
    device_address: int,
    layer_address: int,
) -> _RenderSessionHandle: ...
def attach_vulkan_surface(
    map: _MapHandle,
    width: int,
    height: int,
    scale_factor: float,
    instance_address: int,
    physical_device_address: int,
    device_address: int,
    graphics_queue_address: int,
    graphics_queue_family_index: int,
    get_instance_proc_addr: int,
    get_device_proc_addr: int,
    surface_address: int,
) -> _RenderSessionHandle: ...
def attach_metal_owned_texture(
    map: _MapHandle, width: int, height: int, scale_factor: float, device_address: int
) -> _RenderSessionHandle: ...
def attach_metal_borrowed_texture(
    map: _MapHandle, width: int, height: int, scale_factor: float, texture_address: int
) -> _RenderSessionHandle: ...
def attach_vulkan_owned_texture(
    map: _MapHandle,
    width: int,
    height: int,
    scale_factor: float,
    instance_address: int,
    physical_device_address: int,
    device_address: int,
    graphics_queue_address: int,
    graphics_queue_family_index: int,
    get_instance_proc_addr: int,
    get_device_proc_addr: int,
) -> _RenderSessionHandle: ...
def attach_vulkan_borrowed_texture(
    map: _MapHandle,
    width: int,
    height: int,
    scale_factor: float,
    instance_address: int,
    physical_device_address: int,
    device_address: int,
    graphics_queue_address: int,
    graphics_queue_family_index: int,
    get_instance_proc_addr: int,
    get_device_proc_addr: int,
    image_address: int,
    image_view_address: int,
    format: int,
    initial_layout: int,
    final_layout: int,
) -> _RenderSessionHandle: ...
def attach_opengl_surface(
    map: _MapHandle,
    width: int,
    height: int,
    scale_factor: float,
    context_platform: int,
    context_address_1: int,
    context_address_2: int,
    share_context_address: int,
    get_proc_address: int,
    surface_address: int,
) -> _RenderSessionHandle: ...
def attach_opengl_owned_texture(
    map: _MapHandle,
    width: int,
    height: int,
    scale_factor: float,
    context_platform: int,
    context_address_1: int,
    context_address_2: int,
    share_context_address: int,
    get_proc_address: int,
) -> _RenderSessionHandle: ...
def attach_opengl_borrowed_texture(
    map: _MapHandle,
    width: int,
    height: int,
    scale_factor: float,
    context_platform: int,
    context_address_1: int,
    context_address_2: int,
    share_context_address: int,
    get_proc_address: int,
    texture: int,
    target: int,
) -> _RenderSessionHandle: ...
