// Generated by tools/bindgen. Do not edit.
package org.maplibre.nativeffi.internal.c

internal actual object UpcallStubs {
  actual val completion: Long = Jni.upcallStub(0)
  actual val completionRelease: Long = Jni.upcallStub(1)
  actual val releaseRoot: Long = Jni.upcallStub(2)
  actual val logCallback: Long = Jni.upcallStub(3)
  actual val resourceRequestCancelCallback: Long = Jni.upcallStub(4)
  actual val customGeometrySourceOptionsFetchTile: Long = Jni.upcallStub(5)
  actual val customGeometrySourceOptionsCancelTile: Long = Jni.upcallStub(6)
  actual val customMvtVectorSourceOptionsFetchTile: Long = Jni.upcallStub(7)
  actual val customMvtVectorSourceOptionsCancelTile: Long = Jni.upcallStub(8)
  actual val httpHeaderTransformCallback: Long = Jni.upcallStub(9)
  actual val resourceProviderCallback: Long = Jni.upcallStub(10)
  actual val resourceTransformCallback: Long = Jni.upcallStub(11)
  actual val wakeCallback: Long = Jni.upcallStub(12)
  actual val queueLockLock: Long = Jni.upcallStub(13)
  actual val queueLockUnlock: Long = Jni.upcallStub(14)
}
