"""Generate bindings and report the declarations that still need lowering rules."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

from . import copy_cases
from .compiler import compile_api
from .frontend import parse_headers
from .model import Api, ModelError
from .schema import validate

ROOT = Path(__file__).resolve().parents[2]


def render(api: Api, staging: Path) -> tuple[dict[str, str], dict]:
    from . import native_capture
    from .emitters import dart, dotnet, go, kotlin, python, rust, swift, zig

    bound = compile_api(api)
    if bound.diagnostics:
        raise ModelError(list(bound.diagnostics))
    source_api = api
    outputs = native_capture.generate(bound)
    outputs.update(copy_cases.generate(bound))
    outputs.update(
        {f"bindings/go/{path}": source for path, source in go.generate(bound).items()}
    )
    outputs.update(
        {
            f"bindings/dotnet/src/Maplibre.NativeFfi/{path}": source
            for path, source in dotnet.generate(bound).items()
        }
    )
    outputs.update(
        {
            f"bindings/rust/{path}": source
            for path, source in rust.generate(bound).items()
        }
    )
    outputs.update(
        {
            f"bindings/python/{path}": source
            for path, source in python.generate(bound).items()
        }
    )
    outputs.update(
        {
            f"bindings/swift/Sources/MaplibreNativeFFI/{path}": source
            for path, source in swift.generate(bound).items()
        }
    )
    outputs["bindings/dart/lib/src/runtime/generated_operations.dart"] = dart.generate(
        bound
    )
    outputs["bindings/dart/lib/src/generated_values.dart"] = dart.generate_values(bound)
    outputs.update(
        {
            f"bindings/kotlin/{path}": source
            for path, source in kotlin.generate(bound).items()
        }
    )
    outputs.update(
        {
            f"bindings/zig/src/{path}": source
            for path, source in zig.generate(bound).items()
        }
    )
    reports = {
        language: emitter.coverage(bound)
        for language, emitter in {
            "dotnet": dotnet,
            "go": go,
            "rust": rust,
            "python": python,
            "swift": swift,
            "dart": dart,
            "kotlin": kotlin,
            "zig": zig,
        }.items()
    }
    outputs = format_outputs(outputs, staging)
    empty = [path for path, text in outputs.items() if not text.strip()]
    if empty:
        raise ModelError(
            [f"{path}: formatter produced empty generated output" for path in empty]
        )
    generated_binding_paths = {
        path.removeprefix("bindings/")
        for path in outputs
        if path.startswith("bindings/")
    }
    generated_binding_paths.update({".gitattributes", "generated-coverage.json"})
    outputs["bindings/.gitattributes"] = (
        "# Generated by tools/bindgen. Do not edit.\n"
        + "".join(
            f"/{path} linguist-generated=true\n"
            for path in sorted(generated_binding_paths)
        )
    )
    report = {
        "schema_version": source_api.schema_version,
        "function_count": len(source_api.functions),
        "public_function_count": len(source_api.public_functions),
        "runtime_exports": list(source_api.runtime_exports),
        "semantic": {
            "resolved_operations": len(bound.operations),
            "resolved_callbacks": len(bound.callbacks),
            "support_relations": {
                plan.name: plan.support_for
                for plan in bound.operations
                if plan.role == "support"
            },
        },
        "files": sorted(outputs),
        "languages": reports,
    }
    outputs["bindings/generated-coverage.json"] = (
        json.dumps(report, indent=2, sort_keys=True) + "\n"
    )
    return outputs, report


def format_outputs(outputs: dict[str, str], staging: Path) -> dict[str, str]:
    """Run each language's formatter over the outputs in a staging directory."""
    for path, source in outputs.items():
        target = staging / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(source)
    native_files = [path for path in outputs if path.endswith((".h", ".inc", ".c"))]
    for path in native_files:
        target = staging / path
        formatted = subprocess.run(
            [
                "mise",
                "exec",
                "--no-deps",
                "--",
                "dprint",
                "fmt",
                "--stdin",
                "cpp" if target.suffix == ".inc" else "h",
            ],
            cwd=ROOT,
            input=target.read_text(),
            capture_output=True,
            text=True,
            check=True,
        )
        target.write_text(formatted.stdout)
    subprocess.run(
        [
            "mise",
            "exec",
            "--no-deps",
            "--",
            "gofumpt",
            "-w",
            str(staging / "bindings/go/generated_api.go"),
        ],
        cwd=ROOT / "bindings/go",
        check=True,
    )
    csharp = [str(staging / path) for path in outputs if path.endswith(".cs")]
    if csharp:
        csharp_ignore = staging / "csharpier.ignore"
        csharp_ignore.write_text("")
        subprocess.run(
            [
                "mise",
                "exec",
                "--no-deps",
                "--",
                "dotnet",
                "tool",
                "restore",
                "--tool-manifest",
                str(ROOT / ".config/dotnet-tools.json"),
                "--verbosity",
                "quiet",
            ],
            cwd=ROOT / "bindings/dotnet",
            check=True,
            stdout=subprocess.DEVNULL,
        )
        subprocess.run(
            [
                "mise",
                "exec",
                "--no-deps",
                "--",
                "python",
                "-c",
                "import os, sys; os.chdir(sys.argv[1]); os.execvp(sys.argv[2], sys.argv[2:])",
                str(ROOT),
                "dotnet",
                "tool",
                "run",
                "csharpier",
                "format",
                "--include-generated",
                "--no-cache",
                "--ignore-path",
                str(csharp_ignore),
                *csharp,
            ],
            cwd=ROOT / "bindings/dotnet",
            check=True,
            stdout=subprocess.DEVNULL,
        )
    rust_files = [str(staging / path) for path in outputs if path.endswith(".rs")]
    subprocess.run(
        [
            "mise",
            "exec",
            "--no-deps",
            "--",
            "rustfmt",
            "--edition",
            "2024",
            *rust_files,
        ],
        cwd=ROOT,
        check=True,
    )
    python_files = [
        str(staging / path) for path in outputs if path.endswith((".py", ".pyi"))
    ]
    subprocess.run(
        [
            "mise",
            "exec",
            "--no-deps",
            "--",
            "uv",
            "run",
            "--no-sync",
            "ruff",
            "check",
            "--fix",
            *python_files,
        ],
        cwd=ROOT,
        check=True,
        stdout=subprocess.DEVNULL,
    )
    subprocess.run(
        [
            "mise",
            "exec",
            "--no-deps",
            "--",
            "uv",
            "run",
            "--no-sync",
            "ruff",
            "format",
            *python_files,
        ],
        cwd=ROOT,
        check=True,
        stdout=subprocess.DEVNULL,
    )
    subprocess.run(
        [
            "mise",
            "exec",
            "--no-deps",
            "--",
            "swiftformat",
            "--indent",
            "2",
            "--max-width",
            "80",
            "--quiet",
            str(staging / "bindings/swift/Sources/MaplibreNativeFFI/Generated"),
        ],
        cwd=ROOT,
        check=True,
    )
    subprocess.run(
        [
            "mise",
            "exec",
            "--no-deps",
            "--",
            "dart",
            "format",
            *(str(staging / path) for path in outputs if path.endswith(".dart")),
        ],
        cwd=ROOT / "bindings/dart",
        check=True,
        stdout=subprocess.DEVNULL,
    )
    java_files = [str(staging / path) for path in outputs if path.endswith(".java")]
    if java_files:
        subprocess.run(
            [
                "mise",
                "exec",
                "--no-deps",
                "--",
                "bash",
                str(ROOT / ".mise/bin/dprint-java"),
                "--replace",
                *java_files,
            ],
            cwd=ROOT / "bindings/kotlin",
            check=True,
        )
    kotlin_files = [str(staging / path) for path in outputs if path.endswith(".kt")]
    subprocess.run(
        [
            "mise",
            "exec",
            "--no-deps",
            "--",
            "env",
            "MLN_FFI_DPRINT_SCOPED_TOOLS=1",
            "bash",
            str(ROOT / ".mise/bin/dprint-ktfmt"),
            "--google-style",
            *kotlin_files,
        ],
        cwd=ROOT / "bindings/kotlin",
        check=True,
        stdout=subprocess.DEVNULL,
    )
    zig_files = [str(staging / path) for path in outputs if path.endswith(".zig")]
    subprocess.run(
        ["mise", "exec", "--no-deps", "--", "zig", "fmt", *zig_files],
        cwd=ROOT / "bindings/zig",
        check=True,
        stdout=subprocess.DEVNULL,
    )
    return {path: (staging / path).read_text() for path in outputs}


def generated_files(root: Path = ROOT) -> set[str]:
    """Discover stale owned outputs without trusting an old coverage manifest."""
    candidates = [
        root / "bindings/.gitattributes",
        root / "bindings/go/generated_api.go",
        root / "bindings/go/generated_callbacks.h",
        root / "bindings/go/generated_callbacks.c",
        root / "include/maplibre_native_c/callback_capture_generated.h",
        root / "src/c_api/callback_capture_generated.inc",
        root / "src/c_api/callback_port_generated.inc",
        root / copy_cases.PATH,
    ]
    candidates.extend((root / "bindings/dotnet/src").rglob("*.g.cs"))
    for language in ("rust", "python", "swift", "dart", "kotlin", "zig"):
        candidates.extend(
            path
            for path in (root / "bindings" / language).rglob("*")
            if path.suffix in {".rs", ".swift", ".dart", ".py", ".pyi", ".kt", ".zig"}
            and not any(
                part in {"build", ".build", ".dart_tool", ".venv", "target"}
                for part in path.parts
            )
        )
    return {
        path.relative_to(root).as_posix()
        for path in candidates
        if path.is_file() and "tools/bindgen" in path.read_text()[:160].split("\n")[0]
    }


def generate(api: Api, check: bool, require_complete: bool, root: Path = ROOT) -> int:
    """Write or check the outputs under `root` and return the exit status."""
    (root / "build").mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(
        prefix="bindgen-", dir=root / "build"
    ) as directory:
        outputs, report = render(api, Path(directory))
    stale = generated_files(root) - outputs.keys()
    different = [
        path
        for path, source in outputs.items()
        if not (root / path).is_file() or (root / path).read_text() != source
    ]
    if check:
        for path in sorted(stale):
            print(f"stale generated file: {path}", file=sys.stderr)
        for path in sorted(different):
            print(f"regeneration required: {path}", file=sys.stderr)
    else:
        for path in stale:
            (root / path).unlink()
        for path in different:
            target = root / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(outputs[path])
    incomplete = False
    for language, coverage in sorted(report["languages"].items()):
        missing = len(coverage["unsupported"])
        incomplete |= missing > 0
        print(
            f"{language}: {len(coverage['generated'])}/{len(api.public_functions)} generated; "
            f"{missing} declarations require implementation"
        )
    return int(
        (check and bool(stale or different)) or (require_complete and incomplete)
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("inventory", "validate", "generate"))
    parser.add_argument("--include", type=Path, default=ROOT / "include")
    parser.add_argument(
        "--native-include",
        type=Path,
        default=ROOT / "third_party/maplibre-native/include",
    )
    parser.add_argument("--clang", default="clang")
    parser.add_argument("--clang-arg", action="append", default=[])
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--require-complete", action="store_true")
    args = parser.parse_args()
    try:
        api = parse_headers(
            args.include,
            clang=args.clang,
            clang_args=(f"-I{args.native_include.resolve()}", *args.clang_arg),
        )
        if args.command != "inventory":
            validate(api)
            bound = compile_api(api)
            if bound.diagnostics:
                raise ModelError(list(bound.diagnostics))
        if args.command == "generate":
            return generate(api, args.check, args.require_complete)
        if args.output:
            args.output.write_text(api.to_json())
        elif args.command == "inventory":
            sys.stdout.write(api.to_json())
        else:
            print(f"validated {len(api.functions)} functions")
    except (ModelError, OSError, subprocess.CalledProcessError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
