"""Generate bindings and report the declarations that lack lowering rules."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

from . import copy_cases
from .compiler import compile_api
from .frontend import parse_headers
from .model import Api, ModelError
from .schema import validate
from .semantic import support_relation

ROOT = Path(__file__).resolve().parents[2]
# The coverage report also lists every output, so the next run finds stale ones.
COVERAGE = "bindings/generated-coverage.json"


def render(api: Api, staging: Path) -> tuple[dict[str, str], dict]:
    from . import native_capture
    from .emitters import (
        dart,
        dart_native,
        dotnet,
        go,
        kotlin,
        python,
        rust,
        swift,
        zig,
    )

    bound = compile_api(api)
    if bound.diagnostics:
        raise ModelError(list(bound.diagnostics))
    outputs = native_capture.generate(bound)
    outputs.update(copy_cases.generate(bound))
    for directory, emitter in (
        ("bindings/go", go),
        ("bindings/dotnet/src/Maplibre.NativeFfi", dotnet),
        ("bindings/rust", rust),
        ("bindings/python", python),
        ("bindings/swift/Sources/MaplibreNativeFFI", swift),
        ("bindings/kotlin", kotlin),
        ("bindings/zig/src", zig),
    ):
        outputs.update(
            {
                f"{directory}/{path}": source
                for path, source in emitter.generate(bound).items()
            }
        )
    outputs["bindings/dart/lib/src/runtime/generated_operations.dart"] = dart.generate(
        bound
    )
    outputs["bindings/dart/lib/src/generated_values.dart"] = dart.generate_values(bound)
    outputs[dart_native.PATH] = dart_native.generate(bound)
    reports = {
        language: emitter.coverage(bound)
        for language, emitter in {
            "dotnet": dotnet,
            "go": go,
            "rust": rust,
            "python": python,
            "swift": swift,
            "dart": dart,
            "kotlin": kotlin,
            "zig": zig,
        }.items()
    }
    outputs = format_outputs(outputs, staging)
    empty = [path for path, text in outputs.items() if not text.strip()]
    if empty:
        raise ModelError(
            [f"{path}: formatter produced empty generated output" for path in empty]
        )
    generated_binding_paths = {
        path.removeprefix("bindings/")
        for path in outputs
        if path.startswith("bindings/")
    }
    generated_binding_paths.update({".gitattributes", "generated-coverage.json"})
    outputs["bindings/.gitattributes"] = (
        "# Generated by tools/bindgen. Do not edit.\n"
        + "".join(
            f"/{path} linguist-generated=true\n"
            for path in sorted(generated_binding_paths)
        )
    )
    report = {
        "schema_version": api.schema_version,
        "function_count": len(api.functions),
        "public_function_count": len(api.public_functions),
        "runtime_exports": list(api.runtime_exports),
        "semantic": {
            "resolved_operations": len(bound.operations),
            "resolved_callbacks": len(bound.callbacks),
            "support_relations": {
                plan.name: support_relation(plan)
                for plan in bound.operations
                if plan.support
            },
        },
        "files": sorted(outputs),
        "languages": reports,
    }
    outputs[COVERAGE] = dprint_format(
        json.dumps(report, indent=2, sort_keys=True) + "\n", "json"
    )
    return outputs, report


def run_tool(*command: str, cwd: Path = ROOT, quiet: bool = False, **options):
    """Run a repository tool through mise and fail on a nonzero exit."""
    if quiet:
        options["stdout"] = subprocess.DEVNULL
    return subprocess.run(
        ["mise", "exec", "--no-deps", "--", *command], cwd=cwd, check=True, **options
    )


def dprint_format(source: str, extension: str) -> str:
    """Format a source with the formatter dprint routes the extension to."""
    return run_tool(
        "dprint",
        "fmt",
        "--stdin",
        extension,
        input=source,
        capture_output=True,
        text=True,
    ).stdout


def format_outputs(outputs: dict[str, str], staging: Path) -> dict[str, str]:
    """Run each language's formatter over the outputs in a staging directory."""
    for path, source in outputs.items():
        target = staging / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(source)

    def staged(*suffixes: str) -> list[str]:
        return [str(staging / path) for path in outputs if path.endswith(suffixes)]

    for path in outputs:
        if not path.endswith((".h", ".inc", ".c")):
            continue
        target = staging / path
        extension = "cpp" if target.suffix == ".inc" else "h"
        target.write_text(dprint_format(target.read_text(), extension))
    run_tool(
        "gofumpt",
        "-w",
        str(staging / "bindings/go/generated_api.go"),
        cwd=ROOT / "bindings/go",
    )
    if csharp := staged(".cs"):
        csharp_ignore = staging / "csharpier.ignore"
        csharp_ignore.write_text("")
        dotnet = ROOT / "bindings/dotnet"
        run_tool(
            "dotnet",
            "tool",
            "restore",
            "--tool-manifest",
            str(ROOT / ".config/dotnet-tools.json"),
            "--verbosity",
            "quiet",
            cwd=dotnet,
            quiet=True,
        )
        run_tool(
            "python",
            "-c",
            "import os, sys; os.chdir(sys.argv[1]); os.execvp(sys.argv[2], sys.argv[2:])",
            str(ROOT),
            "dotnet",
            "tool",
            "run",
            "csharpier",
            "format",
            "--include-generated",
            "--no-cache",
            "--ignore-path",
            str(csharp_ignore),
            *csharp,
            cwd=dotnet,
            quiet=True,
        )
    run_tool("rustfmt", "--edition", "2024", *staged(".rs"))
    python_files = staged(".py", ".pyi")
    run_tool(
        "uv", "run", "--no-sync", "ruff", "check", "--fix", *python_files, quiet=True
    )
    run_tool("uv", "run", "--no-sync", "ruff", "format", *python_files, quiet=True)
    run_tool(
        "swiftformat",
        "--indent",
        "2",
        "--max-width",
        "80",
        "--quiet",
        str(staging / "bindings/swift/Sources/MaplibreNativeFFI/Generated"),
    )
    run_tool("dart", "format", *staged(".dart"), cwd=ROOT / "bindings/dart", quiet=True)
    run_tool(
        "env",
        "MLN_FFI_DPRINT_SCOPED_TOOLS=1",
        "bash",
        str(ROOT / ".mise/bin/dprint-ktfmt"),
        "--google-style",
        *staged(".kt"),
        cwd=ROOT / "bindings/kotlin",
        quiet=True,
    )
    run_tool("zig", "fmt", *staged(".zig"), cwd=ROOT / "bindings/zig", quiet=True)
    return {path: (staging / path).read_text() for path in outputs}


CONFLICT_MARKERS = ("<<<<<<<", "|||||||", "=======", ">>>>>>>")


def recorded_files(text: str) -> list[str] | None:
    """Return the `files` entries of a coverage report, or None without one.

    A report that a merge left with conflict markers is not JSON, so this
    reads the one entry per line that the report holds instead, and keeps the
    entries from every side of each conflict.
    """
    try:
        recorded = json.loads(text)
    except ValueError:
        pass
    else:
        files = recorded.get("files") if isinstance(recorded, dict) else None
        if isinstance(files, list) and all(isinstance(path, str) for path in files):
            return files
        return None
    lines = iter(text.splitlines())
    if not any(line.strip() == '"files": [' for line in lines):
        return None
    files = []
    for line in lines:
        entry = line.strip()
        if entry in ("]", "],"):
            return files
        if entry.startswith(CONFLICT_MARKERS):
            continue
        try:
            path = json.loads(entry.removesuffix(","))
        except ValueError:
            return None
        if not isinstance(path, str):
            return None
        files.append(path)
    return None


def previous_outputs(root: Path) -> set[str]:
    """Read the outputs that the last run recorded in its coverage report."""
    manifest = root / COVERAGE
    if not manifest.is_file():
        return set()
    files = recorded_files(manifest.read_text())
    if files is None:
        message = "cannot read the previous output list; resolve or restore the file"
        raise ModelError([f"{COVERAGE}: {message}, then regenerate"])
    unsafe = [
        path for path in files if Path(path).is_absolute() or ".." in Path(path).parts
    ]
    if unsafe:
        raise ModelError(
            [
                f"{COVERAGE}: output path outside the repository: {path}"
                for path in unsafe
            ]
        )
    return set(files)


def generate(api: Api, check: bool, require_complete: bool, root: Path = ROOT) -> int:
    """Write or check the outputs under `root` and return the exit status.

    A file that the previous run recorded and this run no longer writes is
    stale: a check reports it, and a generation deletes it.
    """
    previous = previous_outputs(root)
    (root / "build").mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(
        prefix="bindgen-", dir=root / "build"
    ) as directory:
        outputs, report = render(api, Path(directory))
    stale = {path for path in previous - outputs.keys() if (root / path).is_file()}
    different = [
        path
        for path, source in outputs.items()
        if not (root / path).is_file() or (root / path).read_text() != source
    ]
    if check:
        for path in sorted(stale):
            print(f"stale generated file: {path}", file=sys.stderr)
        for path in sorted(different):
            print(f"regeneration required: {path}", file=sys.stderr)
    else:
        for path in stale:
            (root / path).unlink()
        for path in different:
            target = root / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(outputs[path])
    incomplete = False
    for language, coverage in sorted(report["languages"].items()):
        missing = len(coverage["unsupported"])
        incomplete |= missing > 0
        print(
            f"{language}: {len(coverage['generated'])}/{len(api.public_functions)} generated; "
            f"{missing} declarations require implementation"
        )
    return int(
        (check and bool(stale or different)) or (require_complete and incomplete)
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("inventory", "validate", "generate"))
    parser.add_argument("--include", type=Path, default=ROOT / "include")
    parser.add_argument(
        "--native-include",
        type=Path,
        default=ROOT / "third_party/maplibre-native/include",
    )
    parser.add_argument("--clang", default="clang")
    parser.add_argument("--clang-arg", action="append", default=[])
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--require-complete", action="store_true")
    args = parser.parse_args()
    try:
        api = parse_headers(
            args.include,
            clang=args.clang,
            clang_args=(f"-I{args.native_include.resolve()}", *args.clang_arg),
        )
        if args.command != "inventory":
            validate(api)
            bound = compile_api(api)
            if bound.diagnostics:
                raise ModelError(list(bound.diagnostics))
        if args.command == "generate":
            return generate(api, args.check, args.require_complete)
        if args.output:
            args.output.write_text(api.to_json())
        elif args.command == "inventory":
            sys.stdout.write(api.to_json())
        else:
            print(f"validated {len(api.functions)} functions")
    except (ModelError, OSError, subprocess.CalledProcessError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
