"""Emit one synthesized completion result per adapter copy kind.

C adapter tests can pass each result through its completion copy and compare
the copy with the source. A synthesized result sets every presence bit, picks
the first variant of each union, and gives every array two elements, so the
copy has to follow every pointer the kind declares.
"""

from __future__ import annotations

import json

from .compiler import compile_api
from .model import Api
from .native_capture import capture_roots, copy_kind
from .semantic import BoundApi, ValuePlan

PATH = "tests/native/abi/adapter/adapter_copy_cases_generated.inc"
ARRAY_LENGTH = 2

PRELUDE = """\
// Generated by tools/bindgen. Do not edit.
//
// One synthesized completion result for each mln_adapter_completion_copy_kind.
// Every pointer in a result refers to static storage, every presence bit is
// set, and every array holds two elements. matches() reports whether a copy
// holds the source's content in storage of its own.
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include "maplibre_native_c.h"
#include "maplibre_native_c/callback_adapter.h"

typedef struct mln_adapter_copy_case {
  uint32_t kind;
  const char* type;
  size_t element_size;
  const void* (*value)(size_t* count);
  bool (*matches)(const void* copy, const void* source, size_t count);
} mln_adapter_copy_case;

static inline bool mln_adapter_copy_case_bytes(
  const void* copy, const void* source, size_t size
) {
  if (size == 0) return true;
  return copy != NULL && copy != source && memcmp(copy, source, size) == 0;
}

static inline bool mln_adapter_copy_case_view(
  mln_buffer_view copy, mln_buffer_view source
) {
  return copy.size == source.size &&
    mln_adapter_copy_case_bytes(copy.data, source.data, source.size);
}

static inline bool mln_adapter_copy_case_string(
  const char* copy, const char* source
) {
  if (source == NULL) return copy == NULL;
  return copy != NULL && copy != source && strcmp(copy, source) == 0;
}
"""


class Synthesizer:
    """Writes statements that fill one result and statements that compare it."""

    def __init__(self, name: str):
        self.name = name
        self.storage: list[str] = []
        self.counter = 0

    def unique(self, stem: str) -> str:
        self.counter += 1
        return f"{stem}_{self.counter}"

    def number(self) -> int:
        self.counter += 1
        return self.counter

    def text(self, path: str) -> str:
        """Static text whose content names where it sits in the result."""
        name = self.unique("text")
        self.storage.append(f"  static const char {name}[] = {json.dumps(path)};")
        return name

    def fill(self, plan: ValuePlan, target: str, parent: str, path: str) -> list[str]:
        if plan.kind == "enum":
            return [f"  {target} = {plan.enum_values[0][0]};"]
        if plan.kind in {"scalar", "handle"}:
            spelling = plan.ctype.canonical
            if spelling in {"bool", "_Bool"}:
                return [f"  {target} = true;"]
            value = self.number()
            if spelling in {"float", "double"}:
                return [f"  {target} = {value}.5;"]
            return [f"  {target} = {value};"]
        if plan.kind == "native_pointer":
            return [f"  {target} = NULL;"]
        if plan.kind == "buffer":
            text = self.text(path)
            if plan.buffer_form == "view":
                return [
                    f"  {target}.data = {text};",
                    f"  {target}.size = sizeof({text}) - 1;",
                ]
            if plan.length == "nul":
                return [f"  {target} = {text};"]
            return [
                f"  {target} = ({plan.ctype.spelling}){text};",
                f"  {parent}.{plan.length} = sizeof({text}) - 1;",
            ]
        if plan.kind == "record":
            return self.fill_record(plan, target, path)
        if plan.kind in {"array", "reference"}:
            element = plan.element
            if plan.ctype.kind == "array":
                lines = []
                for index in range(int(plan.length)):
                    lines += self.fill(
                        element, f"{target}[{index}]", parent, f"{path}[{index}]"
                    )
                return lines
            count = ARRAY_LENGTH if plan.kind == "array" else 1
            storage = self.unique("items")
            self.storage.append(
                f"  static {element.ctype.canonical.removeprefix('const ')} {storage}[{count}];"
            )
            lines = []
            for index in range(count):
                lines += self.fill(
                    element, f"{storage}[{index}]", parent, f"{path}[{index}]"
                )
            lines.append(f"  {target} = {storage};")
            if plan.kind == "array":
                lines.append(f"  {parent}.{plan.length} = {count};")
            return lines
        raise ValueError(f"{self.name}: cannot synthesize {plan.kind} at {path}")

    def fill_record(self, plan: ValuePlan, target: str, path: str) -> list[str]:
        derived = derived_fields(plan)
        lines = []
        for field in plan.fields:
            member = f"{target}.{field.name}"
            if field.role == "size":
                lines.append(f"  {member} = sizeof({member.rsplit('.', 1)[0]});")
                continue
            if field.name in derived or field.role in {"reserved", "presence_mask"}:
                continue
            presence = field.presence
            value = field.value
            if value.kind == "union":
                tag = presence.tag if presence and presence.tag else value.tag
                variant = value.fields[0]
                lines.append(f"  {target}.{tag} = {variant.presence.variant};")
                lines += self.fill(
                    variant.value,
                    f"{member}.{variant.name}",
                    member,
                    f"{path}.{field.name}.{variant.name}",
                )
                continue
            if presence and presence.mask:
                mask = f"{target}.{presence.mask}"
                lines.append(
                    f"  {mask} |= {presence.bit};"
                    if presence.bit
                    else f"  {mask} = true;"
                )
            lines += self.fill(value, member, target, f"{path}.{field.name}")
        return lines

    def compare(
        self, plan: ValuePlan, copy: str, source: str, parent: str
    ) -> list[str]:
        """Statements that return false unless `copy` matches `source`."""
        if plan.kind in {"scalar", "enum", "handle", "native_pointer"}:
            return [f"  if ({copy} != {source}) return false;"]
        if plan.kind == "buffer":
            if plan.buffer_form == "view":
                return [
                    f"  if (!mln_adapter_copy_case_view({copy}, {source})) return false;"
                ]
            if plan.length == "nul":
                return [
                    f"  if (!mln_adapter_copy_case_string({copy}, {source})) return false;"
                ]
            return [
                f"  if (!mln_adapter_copy_case_bytes({copy}, {source}, {parent}.{plan.length})) return false;"
            ]
        if plan.kind == "record":
            return self.compare_record(plan, copy, source)
        if plan.kind in {"array", "reference"}:
            if plan.ctype.kind == "array":
                lines = []
                for index in range(int(plan.length)):
                    lines += self.compare(
                        plan.element, f"{copy}[{index}]", f"{source}[{index}]", parent
                    )
                return lines
            count = f"{parent}.{plan.length}" if plan.kind == "array" else "1"
            index = self.unique("index")
            return [
                f"  if ({count} != 0 && ({copy} == NULL || {copy} == {source})) return false;",
                f"  for (size_t {index} = 0; {index} < {count}; ++{index}) {{",
                *(
                    "  " + line
                    for line in self.compare(
                        plan.element,
                        f"{copy}[{index}]",
                        f"{source}[{index}]",
                        parent,
                    )
                ),
                "  }",
            ]
        raise ValueError(f"{self.name}: cannot compare {plan.kind}")

    def compare_record(self, plan: ValuePlan, copy: str, source: str) -> list[str]:
        lines = []
        for field in plan.fields:
            value = field.value
            if field.role in {"size", "reserved"}:
                continue
            presence = field.presence
            if value.kind == "union":
                tag = presence.tag if presence and presence.tag else value.tag
                variant = value.fields[0]
                lines.append(
                    f"  if ({copy}.{tag} != {variant.presence.variant}) return false;"
                )
                lines += self.compare(
                    variant.value,
                    f"{copy}.{field.name}.{variant.name}",
                    f"{source}.{field.name}.{variant.name}",
                    f"{source}.{field.name}",
                )
                continue
            lines += self.compare(
                value, f"{copy}.{field.name}", f"{source}.{field.name}", source
            )
        return lines


def derived_fields(plan: ValuePlan) -> set[str]:
    """Fields another field of the record sets: counts, tags, and strides."""
    derived = set()
    for field in plan.fields:
        value = field.value
        if value.length and not value.length.isdigit() and value.length != "nul":
            derived.add(value.length)
        if value.stride:
            derived.add(value.stride)
        if value.kind == "union":
            tag = (
                field.presence.tag
                if field.presence and field.presence.tag
                else value.tag
            )
            derived.add(tag)
    return derived


def generate(api: Api | BoundApi) -> dict[str, str]:
    bound = compile_api(api)
    roots, arrays, _ = capture_roots(bound)
    lines = [PRELUDE]
    entries = []
    for native, plan in sorted(roots.items()):
        stem = "mln_adapter_copy_case_" + native.removeprefix("mln_")
        synthesizer = Synthesizer(native)
        count = ARRAY_LENGTH if native in arrays else 1
        fill = []
        for index in range(count):
            fill += synthesizer.fill(
                plan, f"values[{index}]", "values", f"{native}[{index}]"
            )
        compare = synthesizer.compare(
            plan, "copy[index]", "source[index]", "source[index]"
        )
        lines += [
            f"static const void* {stem}_value(size_t* count) {{",
            f"  static {native} values[{count}];",
            *synthesizer.storage,
            *fill,
            f"  *count = {count};",
            "  return values;",
            "}",
            "",
            f"static bool {stem}_matches(const void* copy_value, const void* source_value, size_t count) {{",
            f"  const {native}* copy = (const {native}*)copy_value;",
            f"  const {native}* source = (const {native}*)source_value;",
            "  for (size_t index = 0; index < count; ++index) {",
            *("  " + line for line in compare),
            "  }",
            "  return true;",
            "}",
            "",
        ]
        entries.append(
            f'  {{{copy_kind(native)}, "{native}", sizeof({native}), {stem}_value, {stem}_matches}},'
        )
    lines += [
        "static const mln_adapter_copy_case mln_adapter_copy_cases[] = {",
        *entries,
        "};",
        "",
    ]
    return {PATH: "\n".join(lines)}
