"""Emit one C test case per record default function.

Bindings that construct a record from language defaults rather than from its
native default function read each field's annotated `default=`, and treat an
unannotated field as zero. Each case calls the default function and checks that
every field holds that value, so a header and its implementation cannot drift
apart. A union and its tag vary with the build, which bindings never default,
so the cases skip them. A default marks every optional field absent, so the
cases skip those too, and check only that the presence mask is zero.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

from .compiler import compile_api
from .model import Api
from .semantic import BoundApi, FieldPlan, ValuePlan

PATH = "tests/native/abi/base/default_cases_generated.inc"

PRELUDE = """\
// Generated by tools/bindgen. Do not edit.
//
// One case for each record default function. A case checks that every field
// of the default holds its annotated `default=` value, or zero when the header
// annotates none. It skips unions and their tags, whose values vary with the
// build, and optional fields, which the zero presence mask marks absent.
// MLN_DEFAULT_CASES(X) applies X to every case.
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "maplibre_native_c.h"
#include "support/test_support.h"
"""

FLOATS = frozenset({"float", "double"})
BOOLEANS = frozenset({"bool", "_Bool"})


@dataclass(frozen=True)
class Expectation:
    """One field that a default must hold, with its C spelling."""

    path: str
    actual: str
    form: str  # "unsigned", "signed", "float", or "null"
    expected: str = "0"


SIGNED = frozenset({"signed char", "short", "int", "long", "long long"})


def signed(plan: ValuePlan) -> bool:
    """Whether a scalar or enum carries a signed integer."""
    carrier = plan.enum_underlying if plan.kind == "enum" else None
    return (carrier or plan.ctype).canonical.removeprefix("const ") in SIGNED


def expectations(
    plan: ValuePlan, actual: str, path: str, field: FieldPlan | None = None
) -> list[Expectation]:
    """The values that `actual`, a value of `plan`, holds in a default."""
    if field is not None and field.initial is not None:
        expected = field.initial.enumerator or field.initial.literal
    else:
        expected = "0"
    if plan.kind in {"scalar", "enum", "handle"}:
        canonical = plan.ctype.canonical.removeprefix("const ")
        if canonical in FLOATS:
            return [Expectation(path, actual, "float", expected)]
        if canonical in BOOLEANS:
            return [Expectation(path, actual, "unsigned", expected)]
        form = "signed" if signed(plan) else "unsigned"
        return [Expectation(path, actual, form, expected)]
    if plan.kind == "buffer" and plan.buffer_form == "view":
        return [
            Expectation(f"{path}.data", f"{actual}.data", "null"),
            Expectation(f"{path}.size", f"{actual}.size", "unsigned"),
        ]
    if plan.kind == "record":
        return record_expectations(plan, actual, path)
    if plan.ctype.kind == "array" and plan.element is not None:
        result = []
        for index in range(int(plan.length or 0)):
            result += expectations(
                plan.element, f"{actual}[{index}]", f"{path}[{index}]", field
            )
        return result
    if plan.kind in {
        "native_pointer",
        "callback",
        "buffer",
        "array",
        "reference",
    }:
        return [Expectation(path, actual, "null")]
    raise ValueError(f"{path}: cannot check a default {plan.kind}")


def record_expectations(plan: ValuePlan, actual: str, path: str) -> list[Expectation]:
    tags = {
        (
            field.presence.tag
            if field.presence and field.presence.tag
            else field.value.tag
        )
        for field in plan.fields
        if field.value.kind == "union"
    }
    result = []
    for field in plan.fields:
        member, member_path = f"{actual}.{field.name}", f"{path}.{field.name}"
        if field.value.kind == "union" or field.name in tags:
            continue
        if field.presence and field.presence.mask:
            # The default's presence mask is zero, so the field is absent, and
            # native reads its own fallback rather than the field's value.
            continue
        if field.role == "size":
            result.append(
                Expectation(member_path, member, "unsigned", f"sizeof({plan.native})")
            )
            continue
        result += expectations(field.value, member, member_path, field)
    return result


def assertion(expectation: Expectation) -> str:
    path = json.dumps(expectation.path)
    if expectation.form == "null":
        return f"  TEST_ASSERT_TRUE_MESSAGE({expectation.actual} == NULL, {path});"
    if expectation.form == "float":
        return (
            f"  TEST_ASSERT_EQUAL_DOUBLE_MESSAGE({expectation.expected}, "
            f"(double){expectation.actual}, {path});"
        )
    width = "INT64" if expectation.form == "signed" else "UINT64"
    carrier = "int64_t" if expectation.form == "signed" else "uint64_t"
    return (
        f"  TEST_ASSERT_EQUAL_{width}_MESSAGE(({carrier}){expectation.expected}, "
        f"({carrier}){expectation.actual}, {path});"
    )


def default_records(bound: BoundApi) -> list[ValuePlan]:
    """Every record that a default function returns, by name."""
    return sorted(
        (
            plan
            for plan in bound.values.values()
            if plan.kind == "record" and plan.default
        ),
        key=lambda plan: plan.native,
    )


def case_name(plan: ValuePlan) -> str:
    return f"{plan.default}_holds_its_annotated_values"


def generate(api: Api | BoundApi) -> dict[str, str]:
    bound = compile_api(api)
    lines = [PRELUDE]
    names = []
    for plan in default_records(bound):
        name = case_name(plan)
        names.append(name)
        lines += [
            f"static void {name}(void) {{",
            f"  const {plan.native} value = {plan.default}();",
            *(
                assertion(expectation)
                for expectation in record_expectations(plan, "value", plan.native)
            ),
            "}",
            "",
        ]
    lines += [
        "#define MLN_DEFAULT_CASES(X) \\",
        *(f"  X({name}) \\" for name in names),
        "",
        "",
    ]
    return {PATH: "\n".join(lines)}
