"""Identifier rules shared by the managed-language emitters."""

from .names import camel, pascal, type_name

# Reserved words of .NET and Dart. Each emitter escapes, renames, or rejects a
# public name that matches one.
KEYWORDS = {
    "dotnet": {
        "abstract",
        "as",
        "base",
        "bool",
        "break",
        "byte",
        "case",
        "catch",
        "char",
        "checked",
        "class",
        "const",
        "continue",
        "decimal",
        "default",
        "delegate",
        "do",
        "double",
        "else",
        "enum",
        "event",
        "explicit",
        "extern",
        "false",
        "finally",
        "fixed",
        "float",
        "for",
        "foreach",
        "goto",
        "if",
        "implicit",
        "in",
        "int",
        "interface",
        "internal",
        "is",
        "lock",
        "long",
        "namespace",
        "new",
        "null",
        "object",
        "operator",
        "out",
        "override",
        "params",
        "private",
        "protected",
        "public",
        "readonly",
        "ref",
        "return",
        "sbyte",
        "sealed",
        "short",
        "sizeof",
        "stackalloc",
        "static",
        "string",
        "struct",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "typeof",
        "uint",
        "ulong",
        "unchecked",
        "unsafe",
        "ushort",
        "using",
        "virtual",
        "void",
        "volatile",
        "while",
    },
    "dart": {
        "abstract",
        "as",
        "assert",
        "async",
        "await",
        "base",
        "break",
        "case",
        "catch",
        "class",
        "const",
        "continue",
        "covariant",
        "default",
        "deferred",
        "do",
        "dynamic",
        "else",
        "enum",
        "export",
        "extends",
        "extension",
        "external",
        "factory",
        "false",
        "final",
        "finally",
        "for",
        "Function",
        "get",
        "hide",
        "if",
        "implements",
        "import",
        "in",
        "interface",
        "is",
        "late",
        "library",
        "mixin",
        "new",
        "null",
        "of",
        "on",
        "operator",
        "part",
        "required",
        "rethrow",
        "return",
        "sealed",
        "set",
        "show",
        "static",
        "super",
        "switch",
        "sync",
        "this",
        "throw",
        "true",
        "try",
        "typedef",
        "var",
        "void",
        "when",
        "while",
        "with",
        "yield",
    },
}
LOCALS = {
    "completion",
    "result",
    "value",
    "values",
    "copied",
    "index",
    "arena",
    "scope",
    "cancellationToken",
    "nativeArgs",
    "bindingMapHandle",
    "handle",
    "_handle",
}


def conflicting_functions(api, language: str) -> set[str]:
    """Reject ambiguous transformed public names instead of emitting overloads."""
    owners = {}
    for function in api.functions:
        if not function.parameters:
            continue
        receiver = type_name(function.parameters[0].type)
        suffix = function.name.removeprefix(receiver + "_")
        if language == "dotnet":
            suffix = suffix.removeprefix("list_")
        name = pascal(suffix) if language == "dotnet" else camel(suffix)
        owners.setdefault((receiver, name), []).append(function.name)
    return {name for names in owners.values() if len(names) > 1 for name in names}
