"""Generate native Dart port callbacks for copyable notification descriptors."""

from __future__ import annotations

import zlib


def callback_id(record: str, field: str) -> int:
    return zlib.crc32(f"{record}.{field}".encode())


def constant(record: str, field: str) -> str:
    return (
        "MLN_ADAPTER_DART_PORT_"
        + record.removeprefix("mln_").upper()
        + "_"
        + field.upper()
    )


def flattened(value, expression):
    if (
        value.kind in {"scalar", "enum"}
        and value.native != "void"
        and value.ctype.kind not in {"float", "double"}
        and value.ctype.canonical not in {"float", "double"}
    ):
        return [expression]
    if value.kind == "record" and not value.presence_groups:
        result = []
        for field in value.fields:
            if field.role != "value" or field.presence:
                return None
            children = flattened(field.value, f"{expression}.{field.name}")
            if children is None:
                return None
            result.extend(children)
        return result
    return None


def callbacks(bound):
    result = []
    for record in sorted(bound.values.values(), key=lambda v: v.native):
        if not record.registration:
            continue
        for field in record.fields:
            if field.name not in record.registration.callbacks:
                continue
            callback = bound.callbacks[field.value.native]
            if not callback.context or callback.result.native != "void":
                continue
            payload = []
            for parameter in callback.parameters:
                if parameter.name == callback.context:
                    continue
                children = flattened(parameter.value, parameter.name)
                if parameter.direction != "in" or children is None:
                    break
                payload.extend(children)
            else:
                result.append((record, field, callback, payload))
    return result


def generate(bound):
    header = ["typedef enum mln_adapter_dart_port_callback : uint32_t {"]
    output = ["// Generated by tools/bindgen. Do not edit."]
    entries = callbacks(bound)
    for record, field, callback, payload in entries:
        name = constant(record.native, field.name)
        header.append(f"  {name} = {callback_id(record.native, field.name)}U,")
        arguments = ", ".join(
            f"{p.value.ctype.spelling} {p.name}" for p in callback.parameters
        )
        values = ", ".join(
            [name, *(f"static_cast<std::int64_t>({item})" for item in payload)]
        )
        output.extend(
            [
                f"void port_{name}({arguments}) {{",
                f"  const std::int64_t values[] = {{{values}}};",
                f"  dart_port_notify({callback.context}, values);",
                "}",
            ]
        )
    header.extend(["} mln_adapter_dart_port_callback;", ""])
    output.extend(
        [
            "auto dart_port_function(std::uint32_t id) noexcept -> void* {",
            "  switch (id) {",
        ]
    )
    for record, field, _, _ in entries:
        name = constant(record.native, field.name)
        output.append(f"    case {name}: return reinterpret_cast<void*>(&port_{name});")
    output.extend(["    default: return nullptr;", "  }", "}", ""])
    return header, "\n".join(output)
