"""Generate native Dart port callbacks for copyable notifications.

A port callback serves a void callback with a context: a descriptor field
whose record carries a release, or a direct registration that takes a release
callback.
"""

from __future__ import annotations

import zlib


def callback_id(owner: str, field: str) -> int:
    return zlib.crc32(f"{owner}.{field}".encode())


def constant(owner: str, field: str) -> str:
    return (
        "MLN_ADAPTER_DART_PORT_"
        + owner.removeprefix("mln_").upper()
        + "_"
        + field.upper()
    )


def flattened(value, expression):
    if (
        value.kind in {"scalar", "enum"}
        and value.native != "void"
        and value.ctype.kind not in {"float", "double"}
        and value.ctype.canonical not in {"float", "double"}
    ):
        return [expression]
    if value.kind == "record" and not value.presence_groups:
        result = []
        for field in value.fields:
            if field.role != "value" or field.presence:
                return None
            children = flattened(field.value, f"{expression}.{field.name}")
            if children is None:
                return None
            result.extend(children)
        return result
    return None


def payload(callback):
    """Flatten a void context callback's inputs, or return None.

    A synchronous callback has none: native code relies on its work being done
    when it returns, which a later port message cannot do.
    """
    if not callback.context or callback.result.native != "void" or callback.synchronous:
        return None
    result = []
    for parameter in callback.parameters:
        if parameter.name == callback.context:
            continue
        children = flattened(parameter.value, parameter.name)
        if parameter.direction != "in" or children is None:
            return None
        result.extend(children)
    return result


def callbacks(bound):
    result = []
    for record in sorted(bound.values.values(), key=lambda v: v.native):
        if not record.registration:
            continue
        for field in record.fields:
            if field.name not in record.registration.callbacks:
                continue
            callback = bound.callbacks[field.value.native]
            values = payload(callback)
            if values is not None:
                result.append((record, field, callback, values))
    return result


def direct_callbacks(bound):
    """Direct registrations whose callback a port delivers until native release."""
    result = []
    for plan in sorted(bound.operations, key=lambda p: p.name):
        if len(plan.direct_registrations) != 1:
            continue
        registration = plan.direct_registrations[0]
        if not registration.release_callback:
            continue
        value = next(p.value for p in plan.inputs if p.name == registration.callback)
        callback = bound.callbacks[value.native]
        values = payload(callback)
        if values is not None:
            result.append((plan, registration, callback, values))
    return result


def entries(bound):
    """Name every port callback by its owner and field."""
    return [
        *(
            (record.native, field.name, callback, values)
            for record, field, callback, values in callbacks(bound)
        ),
        *(
            (plan.name, registration.callback, callback, values)
            for plan, registration, callback, values in direct_callbacks(bound)
        ),
    ]


def generate(bound):
    header = ["typedef enum mln_adapter_dart_port_callback : uint32_t {"]
    output = ["// Generated by tools/bindgen. Do not edit."]
    ports = entries(bound)
    for owner, field, callback, values in ports:
        name = constant(owner, field)
        header.append(f"  {name} = {callback_id(owner, field)}U,")
        arguments = ", ".join(
            f"{p.value.ctype.spelling} {p.name}" for p in callback.parameters
        )
        items = ", ".join(
            [name, *(f"static_cast<std::int64_t>({item})" for item in values)]
        )
        output.extend(
            [
                f"void port_{name}({arguments}) {{",
                f"  const std::int64_t values[] = {{{items}}};",
                f"  dart_port_notify({callback.context}, values);",
                "}",
            ]
        )
    header.extend(["} mln_adapter_dart_port_callback;", ""])
    output.extend(
        [
            "auto dart_port_function(std::uint32_t id) noexcept -> void* {",
            "  switch (id) {",
        ]
    )
    for owner, field, _, _ in ports:
        name = constant(owner, field)
        output.append(f"    case {name}: return reinterpret_cast<void*>(&port_{name});")
    output.extend(["    default: return nullptr;", "  }", "}", ""])
    return header, "\n".join(output)
