"""Emit static native capture functions for deferred foreign callbacks."""

from __future__ import annotations

import zlib

from .compiler import compile_api
from .model import Api, ModelError
from .semantic import BoundApi


def copy_kind(native: str) -> str:
    return "MLN_ADAPTER_COMPLETION_COPY_" + native.removeprefix("mln_").upper()


def capture_id(native: str, ownership: str = "borrowed") -> int:
    return zlib.crc32(f"{ownership}:{native}".encode())


def generate(api: Api | BoundApi) -> dict[str, str]:
    bound = compile_api(api)
    source = bound.source
    roots = {}
    arrays = set()
    owned = {}
    for function in source.functions:
        native = function.metadata.get("result")
        if not native or native == "void":
            continue
        operation = bound.operations_by_name.get(function.name)
        if operation is None:
            raise ModelError(list(bound.unsupported[function.name]))
        plan = operation.result
        if plan is None:
            raise ModelError(
                [f"{function.name}: completion capture requires result plan"]
            )
        if function.metadata.get("shape") == "array":
            arrays.add(native)
            if plan.element is None:
                raise ModelError(
                    [f"{function.name}: capture array requires an element plan"]
                )
            plan = plan.element
        if function.metadata.get("ownership") == "owned":
            if not plan.handle or not plan.handle.dispose:
                raise ModelError(
                    [f"{function.name}: owned capture requires a disposal operation"]
                )
            owned[native] = plan
        elif native in source.records_by_name:
            roots[native] = plan
    roots.update(owned)
    for plan in roots.values():
        _validate_capture_ownership(plan)
    identities = {0: "flat"}
    for native in roots:
        identity = capture_id(native, "owned" if native in owned else "borrowed")
        if identity in identities:
            raise ModelError(
                [f"capture identity collision: {native}, {identities[identity]}"]
            )
        identities[identity] = native
    header = [
        "// Generated by tools/bindgen. Do not edit.",
        "#ifndef MAPLIBRE_NATIVE_C_CALLBACK_CAPTURE_GENERATED_H",
        "#define MAPLIBRE_NATIVE_C_CALLBACK_CAPTURE_GENERATED_H",
        "#include <stdint.h>",
        "typedef enum mln_adapter_completion_copy_kind : uint32_t {",
        "  MLN_ADAPTER_COMPLETION_COPY_FLAT = 0,",
    ]
    header.extend(
        f"  {copy_kind(native)} = {capture_id(native, 'owned' if native in owned else 'borrowed')}U,"
        for native in sorted(roots)
    )
    from . import native_ports

    port_header, port_output = native_ports.generate(bound)
    header.extend(["} mln_adapter_completion_copy_kind;", *port_header, "#endif", ""])

    output = ["// Generated by tools/bindgen. Do not edit."]
    for native, plan in sorted(roots.items()):
        body = _capture(plan, "source", "result", "", 1)
        output.extend(
            [
                "template <bool Writing>",
                f"auto capture_{native}([[maybe_unused]] Arena<Writing>& arena, {native} source) -> {native} {{",
                "  auto result = source;",
                *body,
                "  return result;",
                "}",
            ]
        )
    output.extend(
        [
            "inline auto discard(std::uint32_t kind, const mln_completion_result& result) noexcept -> void {",
            "  if (result.status != MLN_STATUS_OK || result.value == nullptr) return;",
            "  switch (kind) {",
        ]
    )
    for native, plan in sorted(owned.items()):
        assert plan.handle is not None and plan.handle.dispose is not None
        output.extend(
            [
                f"    case {copy_kind(native)}:",
                "      for (std::size_t index = 0; index < result.value_count; ++index)",
                f"        static_cast<void>({plan.handle.dispose}(static_cast<const {native}*>(result.value)[index]));",
                "      break;",
            ]
        )
    output.extend(["    default: break;", "  }", "}"])
    output.extend(
        [
            "inline auto valid_kind(std::uint32_t kind) -> bool {",
            "  switch (kind) {",
            "    case MLN_ADAPTER_COMPLETION_COPY_FLAT:",
            *(f"    case {copy_kind(native)}:" for native in sorted(roots)),
            "      return true;",
            "    default: return false;",
            "  }",
            "}",
            "template <bool Writing>",
            "auto value(Arena<Writing>& arena, const mln_completion_result& result,",
            "           std::uint32_t kind, std::size_t element_size) -> const void* {",
            "  if (result.value_count == 0) return result.value == nullptr ? nullptr : empty_pointer<std::max_align_t>();",
            '  if (result.value == nullptr) throw std::invalid_argument{"null completion result"};',
            "  switch (kind) {",
            "    case MLN_ADAPTER_COMPLETION_COPY_FLAT: {",
            "      if (element_size == 0 || result.value_count > std::numeric_limits<std::size_t>::max() / element_size)",
            '        throw std::invalid_argument{"invalid completion element size"};',
            "      const auto size = result.value_count * element_size;",
            "      constexpr auto alignment = sizeof(std::max_align_t);",
            "      const auto count = size / alignment + (size % alignment != 0);",
            "      auto* target = arena.template allocate<std::max_align_t>(count);",
            "      if constexpr (Writing) std::memcpy(target, result.value, size);",
            "      return target;",
            "    }",
        ]
    )
    for native in sorted(roots):
        output.extend(
            [
                f"    case {copy_kind(native)}:",
                *(
                    []
                    if native in arrays
                    else [
                        '      if (result.value_count != 1) throw std::invalid_argument{"invalid completion count"};'
                    ]
                ),
                f"      return span(arena, static_cast<const {native}*>(result.value), result.value_count,",
                f"        [](auto& storage, auto source) {{ return capture_{native}(storage, source); }});",
            ]
        )
    output.extend(
        [
            '    default: throw std::invalid_argument{"unknown completion capture kind"};',
            "  }",
            "}",
            "",
        ]
    )
    output.append(
        "inline auto dispose_owner(const char* native_type, std::uint64_t handle) noexcept -> mln_status {"
    )
    output.append("  if (native_type == nullptr) return MLN_STATUS_INVALID_ARGUMENT;")
    for handle in sorted(bound.handles.values(), key=lambda item: item.native):
        if not handle.dispose:
            continue
        operation = source.functions_by_name[handle.dispose]
        call = f"{handle.dispose}(static_cast<{handle.native}>(handle))"
        body = (
            f"{call}; return MLN_STATUS_OK;"
            if operation.return_type.kind == "void"
            else f"return {call};"
        )
        output.append(
            f'  if (std::strcmp(native_type, "{handle.native}") == 0) {{ {body} }}'
        )
    output.extend(["  return MLN_STATUS_INVALID_ARGUMENT;", "}", ""])
    return {
        "include/maplibre_native_c/callback_capture_generated.h": "\n".join(header),
        "src/c_api/callback_capture_generated.inc": "\n".join(output),
        "src/c_api/callback_port_generated.inc": port_output,
    }


def _validate_capture_ownership(plan, *, nested=False):
    if plan.kind == "handle" and plan.ownership == "owned" and nested:
        raise ModelError(
            [f"{plan.native}: nested owned capture requires recursive disposal"]
        )
    for field in plan.fields:
        _validate_capture_ownership(field.value, nested=True)
    if plan.element is not None:
        _validate_capture_ownership(plan.element, nested=True)


def _capture(plan, source: str, target: str, parent: str, depth: int) -> list[str]:
    indent = "  " * depth
    if plan.kind in {"scalar", "enum", "handle"}:
        if plan.kind == "handle" and plan.ownership == "owned" and parent:
            raise ModelError(
                [f"{plan.native}: nested owned capture requires recursive disposal"]
            )
        return []
    if plan.kind == "buffer":
        if plan.native == "mln_buffer_view":
            return [f"{indent}{target} = buffer(arena, {source});"]
        if plan.length == "nul":
            return [f"{indent}{target} = string(arena, {source});"]
        if plan.length:
            pointer = (
                f"static_cast<const std::byte*>({source})"
                if plan.ctype.pointee and plan.ctype.pointee.kind == "void"
                else source
            )
            return [
                f"{indent}{target} = bytes(arena, {pointer}, {parent}.{plan.length});"
            ]
        raise ModelError([f"{plan.native}: capture buffer requires length"])
    if plan.kind == "record":
        lines = []
        for field in plan.fields:
            child = field.value
            selector = field.presence
            child_source, child_target = (
                f"{source}.{field.name}",
                f"{target}.{field.name}",
            )
            if child.kind == "union":
                tag = selector.tag if selector else child.tag
                if not tag:
                    raise ModelError(
                        [f"{plan.native}.{field.name}: capture union requires tag"]
                    )
                lines.append(f"{indent}switch ({source}.{tag}) {{")
                for variant in child.fields:
                    if not variant.presence or not variant.presence.variant:
                        raise ModelError(
                            [
                                f"{plan.native}.{field.name}: capture union requires variants"
                            ]
                        )
                    lines.append(f"{indent}  case {variant.presence.variant}:")
                    lines.extend(
                        _capture(
                            variant.value,
                            f"{child_source}.{variant.name}",
                            f"{child_target}.{variant.name}",
                            child_source,
                            depth + 2,
                        )
                    )
                    lines.append(f"{indent}    break;")
                lines.extend(
                    [
                        f'{indent}  default: throw std::invalid_argument{{"unknown completion variant"}};',
                        f"{indent}}}",
                    ]
                )
            elif selector and selector.mask:
                condition = (
                    f"({source}.{selector.mask} & {selector.bit}) != 0"
                    if selector.bit
                    else f"{source}.{selector.mask}"
                )
                lines.append(f"{indent}if ({condition}) {{")
                lines.extend(
                    _capture(child, child_source, child_target, source, depth + 1)
                )
                lines.extend(
                    [
                        f"{indent}}} else {{",
                        f"{indent}  {child_target} = {{}};",
                        f"{indent}}}",
                    ]
                )
            else:
                lines.extend(_capture(child, child_source, child_target, source, depth))
        return lines
    if plan.kind in {"array", "reference"}:
        length = plan.length if plan.kind == "array" else "1"
        if length is None:
            raise ModelError([f"{plan.native}: capture array requires length"])
        count = str(length) if str(length).isdigit() else f"{parent}.{length}"
        if plan.kind == "reference" and plan.nullable:
            count = f"({source} == nullptr ? 0 : 1)"
        name = f"element_{depth}"
        if plan.ctype.kind == "array":
            lines = [
                f"{indent}for (std::size_t index_{depth} = 0; index_{depth} < {count}; ++index_{depth}) {{"
            ]
            lines.extend(
                _capture(
                    plan.element,
                    f"{source}[index_{depth}]",
                    f"{target}[index_{depth}]",
                    parent,
                    depth + 1,
                )
            )
            lines.append(f"{indent}}}")
            return lines
        if plan.element.kind in {"scalar", "enum", "handle"}:
            return [f"{indent}{target} = bytes(arena, {source}, {count});"]
        lines = [
            f"{indent}{target} = span(arena, {source}, {count}, [&]([[maybe_unused]] auto& arena, auto {name}) {{",
            f"{indent}  auto copied_{depth} = {name};",
        ]
        lines.extend(_capture(plan.element, name, f"copied_{depth}", parent, depth + 1))
        lines.extend([f"{indent}  return copied_{depth};", f"{indent}}});"])
        return lines
    raise ModelError([f"{plan.native}: native capture does not support {plan.kind}"])
