// Generated from the C headers by tools/bindgen. Do not edit.
global using Maplibre.NativeFfi.Internal;
global using Maplibre.NativeFfi.Internal.C;
global using static Maplibre.NativeFfi.Internal.C.mln_animation_option_field;
global using static Maplibre.NativeFfi.Internal.C.mln_bound_option_field;
global using static Maplibre.NativeFfi.Internal.C.mln_camera_fit_option_field;
global using static Maplibre.NativeFfi.Internal.C.mln_camera_option_field;
global using static Maplibre.NativeFfi.Internal.C.mln_custom_geometry_source_option_field;
global using static Maplibre.NativeFfi.Internal.C.mln_custom_mvt_vector_source_option_field;
global using static Maplibre.NativeFfi.Internal.C.mln_feature_state_selector_field;
global using static Maplibre.NativeFfi.Internal.C.mln_free_camera_option_field;
global using static Maplibre.NativeFfi.Internal.C.mln_geojson_source_option_field;
global using static Maplibre.NativeFfi.Internal.C.mln_map_tile_option_field;
global using static Maplibre.NativeFfi.Internal.C.mln_map_viewport_option_field;
global using static Maplibre.NativeFfi.Internal.C.mln_projection_mode_field;
global using static Maplibre.NativeFfi.Internal.C.mln_queried_feature_field;
global using static Maplibre.NativeFfi.Internal.C.mln_rendered_feature_query_option_field;
global using static Maplibre.NativeFfi.Internal.C.mln_source_feature_query_option_field;
global using static Maplibre.NativeFfi.Internal.C.mln_style_image_option_field;
global using static Maplibre.NativeFfi.Internal.C.mln_style_source_info_field;
global using static Maplibre.NativeFfi.Internal.C.mln_style_tile_source_option_field;
global using static Maplibre.NativeFfi.Internal.C.mln_style_transition_option_field;
global using Maplibre.NativeFfi.Internal.Callback;
global using Maplibre.NativeFfi.Internal.Memory;
global using Maplibre.NativeFfi.Internal.Pointer;
global using Maplibre.NativeFfi.Internal.Struct;
