[tasks.generate]
run = "scripts/generate-clangsharp.sh"

[tasks.build]
run = "dotnet build Maplibre.Native.slnx"

[tasks.test]
depends = ["//:ensure-native-library"]
run = "dotnet test Maplibre.Native.slnx"

[tasks.format]
run = "dotnet format Maplibre.Native.slnx --verify-no-changes --verbosity minimal"

[tasks.ci]
depends = [":format", ":test"]
