[tasks.build]
depends = ["//:ensure-native-library"]
run = '''
zig build -Dcmake-artifact-dir="$MLN_FFI_BUILD_DIR" -Ddependency-library-dir="$MLN_FFI_DEPENDENCY_LIBRARY_DIR" -Drender-backend="$MLN_FFI_RENDER_BACKEND"
'''

[tasks.test]
depends = ["//:ensure-native-library"]
run = '''
zig build test --summary all --verbose -Dcmake-artifact-dir="$MLN_FFI_BUILD_DIR" -Ddependency-library-dir="$MLN_FFI_DEPENDENCY_LIBRARY_DIR" -Drender-backend="$MLN_FFI_RENDER_BACKEND"
'''

[tasks.ci]
depends = [":test"]
