[tasks.build]
run = [
  { task = "//:ensure-native-library" },
  { task = ":jextract:update-includes" },
  "../../gradlew :bindings:java-ffm:assemble",
]

[tasks.test]
run = [
  { task = "//:ensure-native-library" },
  { task = ":jextract:update-includes" },
  "../../gradlew :bindings:java-ffm:check",
]
