<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableLibraryImportGenerator>true</EnableLibraryImportGenerator>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
    <PackageId>Maplibre.Native</PackageId>
    <RootNamespace>Maplibre.Native</RootNamespace>
    <AssemblyName>Maplibre.Native</AssemblyName>
  </PropertyGroup>
</Project>
