// Generated by tools/bindgen. Do not edit.
package org.maplibre.nativeffi.internal.c

import java.lang.foreign.ValueLayout.*

internal actual object UpcallStubs {
  actual val completion: Long = Ffm.upcall("completion", null, JAVA_LONG, JAVA_LONG)
  actual val completionRelease: Long = Ffm.upcall("completionRelease", null, JAVA_LONG)
  actual val releaseRoot: Long = Ffm.upcall("releaseRoot", null, JAVA_LONG)
  actual val logCallback: Long =
    Ffm.upcall("logCallback", JAVA_INT, JAVA_LONG, JAVA_INT, JAVA_INT, JAVA_LONG, JAVA_LONG)
  actual val resourceRequestCancelCallback: Long =
    Ffm.upcall("resourceRequestCancelCallback", null, JAVA_LONG)
  actual val customGeometrySourceOptionsFetchTile: Long =
    Ffm.upcall("customGeometrySourceOptionsFetchTile", null, JAVA_LONG, mln_canonical_tile_id)
  actual val customGeometrySourceOptionsCancelTile: Long =
    Ffm.upcall("customGeometrySourceOptionsCancelTile", null, JAVA_LONG, mln_canonical_tile_id)
  actual val customMvtVectorSourceOptionsFetchTile: Long =
    Ffm.upcall("customMvtVectorSourceOptionsFetchTile", null, JAVA_LONG, mln_canonical_tile_id)
  actual val customMvtVectorSourceOptionsCancelTile: Long =
    Ffm.upcall("customMvtVectorSourceOptionsCancelTile", null, JAVA_LONG, mln_canonical_tile_id)
  actual val httpHeaderTransformCallback: Long =
    Ffm.upcall("httpHeaderTransformCallback", JAVA_INT, JAVA_LONG, JAVA_INT, JAVA_LONG, JAVA_LONG)
  actual val resourceProviderCallback: Long =
    Ffm.upcall("resourceProviderCallback", JAVA_INT, JAVA_LONG, JAVA_LONG, JAVA_LONG)
  actual val resourceTransformCallback: Long =
    Ffm.upcall("resourceTransformCallback", JAVA_INT, JAVA_LONG, JAVA_INT, JAVA_LONG, JAVA_LONG)
  actual val wakeCallback: Long = Ffm.upcall("wakeCallback", null, JAVA_LONG)
}
