export {
  OfflineOperationHandle,
  type AmbientCacheOperation,
  type OfflineTilePyramidRegionDefinition,
  type OfflineGeometryRegionDefinition,
  type OfflineRegionDefinition,
  type OfflineTilePyramidRegionDefinitionValue,
  type OfflineGeometryRegionDefinitionValue,
  type OfflineUnknownRegionDefinitionValue,
  type OfflineRegionDefinitionValue,
  type OfflineRegionInfo,
  type OfflineRegionStatus,
  type OfflineOperationRef,
  type OfflineRegionDownloadState,
  type OfflineRegionDownloadStateValue,
} from "./index.cjs";
