[env]
MLN_FFI_RENDER_BACKEND = "webgpu"
MLN_FFI_OPENGL_CONTEXT_PROVIDER = ""
MLN_FFI_BUILD_DIR = "{{config_root}}/build/browser-wasm64-webgpu"
MLN_FFI_ZIG_BUILD_ARGS = "-Dtarget=wasm32-emscripten"
MLN_EMSCRIPTEN_INITIAL_MEMORY = "512MB"
MLN_EMSCRIPTEN_ALLOW_MEMORY_GROWTH = "ON"
MLN_EMSCRIPTEN_MAXIMUM_MEMORY = "2048MB"
MLN_EMSCRIPTEN_STACK_SIZE = "1MB"
MLN_EMSCRIPTEN_PTHREAD_POOL_SIZE = "16"
MLN_FFI_CMAKE_ARGS = """
-DCMAKE_TOOLCHAIN_FILE={{config_root}}/cmake/emscripten-toolchain.cmake
-DMLN_EMSCRIPTEN_USE_PTHREADS=ON
-DMLN_EMSCRIPTEN_INITIAL_MEMORY={{env.MLN_EMSCRIPTEN_INITIAL_MEMORY}}
-DMLN_EMSCRIPTEN_ALLOW_MEMORY_GROWTH={{env.MLN_EMSCRIPTEN_ALLOW_MEMORY_GROWTH}}
-DMLN_EMSCRIPTEN_MAXIMUM_MEMORY={{env.MLN_EMSCRIPTEN_MAXIMUM_MEMORY}}
-DMLN_EMSCRIPTEN_STACK_SIZE={{env.MLN_EMSCRIPTEN_STACK_SIZE}}
-DMLN_EMSCRIPTEN_PTHREAD_POOL_SIZE={{env.MLN_EMSCRIPTEN_PTHREAD_POOL_SIZE}}
"""
