[env]
_.path = [
  "{{config_root}}/.pixi/envs/default/Library/bin",
  "{{config_root}}/build/windows-x64-wgl",
]
MLN_FFI_VARIANT = "windows-x64-wgl"
MLN_FFI_TARGET_TRIPLE = "windows-x64"
MLN_FFI_RENDER_BACKEND = "opengl"
MLN_FFI_OPENGL_CONTEXT_PROVIDER = "wgl"
MLN_FFI_BUILD_DIR = "{{config_root}}/build/windows-x64-wgl"
MLN_FFI_ZIG_TARGET = "x86_64-windows-msvc"
