[env]
MLN_FFI_RENDER_BACKEND = "opengl"
MLN_FFI_BUILD_DIR = "{{config_root}}/build/linux-arm64-egl"
MLN_FFI_ZIG_BUILD_ARGS = "-Dtarget=aarch64-linux-gnu"
BINDGEN_EXTRA_CLANG_ARGS = "{% if os() == \"linux\" %}-isystem{{ exec(command='cc -print-file-name=include', cache_key='host-cc-builtin-include', cache_duration='1d') | trim }}{% endif %}"
PKG_CONFIG_PATH = "{{env.MLN_FFI_BUILD_DIR}}:{{config_root}}/.pixi/envs/default/lib/pkgconfig"
CMAKE_LIBRARY_PATH = "{{env.MLN_FFI_DEPENDENCY_LIBRARY_DIR}}"
LIBRARY_PATH = "{{env.MLN_FFI_DEPENDENCY_LIBRARY_DIR}}"
LD_LIBRARY_PATH = "{{env.MLN_FFI_BUILD_DIR}}:{{env.MLN_FFI_DEPENDENCY_LIBRARY_DIR}}"
