[env]
_.path = [
  "{{config_root}}/.pixi/envs/default/Library/bin",
  "{{config_root}}/build/windows-x64-wgl",
]
MLN_FFI_RENDER_BACKEND = "opengl"
MLN_FFI_BUILD_DIR = "{{config_root}}/build/windows-x64-wgl"
MLN_FFI_SYSTEM_ROOT = false
MLN_FFI_DEPENDENCY_INCLUDE_DIR = "{{config_root}}/.pixi/envs/default/Library/include"
MLN_FFI_DEPENDENCY_LIBRARY_DIR = "{{config_root}}/.pixi/envs/default/Library/lib"
MLN_FFI_ZIG_BUILD_ARGS = "-Dtarget=x86_64-windows-msvc -Dcmake-artifact-dir=\"{{env.MLN_FFI_BUILD_DIR}}\" -Drender-backend=opengl -Dinclude-dir=\"{{env.MLN_FFI_INCLUDE_DIR}}\" -Dinclude-dir=\"{{env.MLN_FFI_DEPENDENCY_INCLUDE_DIR}}\" -Dinclude-dir=\"{{env.MLN_FFI_VULKAN_INCLUDE_DIR}}\" -Ddependency-library-dir=\"{{env.MLN_FFI_DEPENDENCY_LIBRARY_DIR}}\""
CMAKE_PREFIX_PATH = "{{config_root}}/.pixi/envs/default/Library"
CMAKE_LIBRARY_PATH = "{{env.MLN_FFI_DEPENDENCY_LIBRARY_DIR}}"
PKG_CONFIG_PATH = "{{env.MLN_FFI_DEPENDENCY_LIBRARY_DIR}}/pkgconfig"
LIBCLANG_PATH = "{{config_root}}/.pixi/envs/default/Library/bin"
RUSTFLAGS = "-L native={{env.MLN_FFI_DEPENDENCY_LIBRARY_DIR}}"
