[env]
MLN_FFI_RENDER_BACKEND = "vulkan"
MLN_FFI_BUILD_DIR = "{{config_root}}/build/linux-arm64-vulkan"
MLN_FFI_ZIG_BUILD_ARGS = "-Dtarget=aarch64-linux-gnu"
CC = "{{config_root}}/.pixi/envs/default/bin/aarch64-conda-linux-gnu-cc"
CXX = "{{config_root}}/.pixi/envs/default/bin/aarch64-conda-linux-gnu-c++"
BINDGEN_EXTRA_CLANG_ARGS = "--target=aarch64-conda-linux-gnu --sysroot={{config_root}}/.pixi/envs/default/aarch64-conda-linux-gnu/sysroot -isystem{{config_root}}/.pixi/envs/default/lib/gcc/aarch64-conda-linux-gnu/14.3.0/include -isystem{{config_root}}/.pixi/envs/default/lib/gcc/aarch64-conda-linux-gnu/14.3.0/include-fixed -isystem{{config_root}}/.pixi/envs/default/aarch64-conda-linux-gnu/sysroot/usr/include"
PKG_CONFIG_PATH = "{{env.MLN_FFI_BUILD_DIR}}:{{config_root}}/.pixi/envs/default/lib/pkgconfig"
CMAKE_LIBRARY_PATH = "{{env.MLN_FFI_DEPENDENCY_LIBRARY_DIR}}"
LIBRARY_PATH = "{{env.MLN_FFI_DEPENDENCY_LIBRARY_DIR}}"
