[env]
CC = "clang"
CXX = "clang++"
MLN_FFI_VARIANT = "linux-x64-vulkan"
MLN_FFI_TARGET_TRIPLE = "linux-x64"
MLN_FFI_RENDER_BACKEND = "vulkan"
MLN_FFI_BUILD_DIR = "{{config_root}}/build/linux-x64-vulkan"
DYLD_LIBRARY_PATH = "{{config_root}}/build/linux-x64-vulkan"
LD_LIBRARY_PATH = "{{config_root}}/build/linux-x64-vulkan"
