[env]
MLN_FFI_VARIANT = "macos-arm64-vulkan"
MLN_FFI_TARGET_TRIPLE = "macos-arm64"
MLN_FFI_RENDER_BACKEND = "vulkan"
MLN_FFI_BUILD_DIR = "{{config_root}}/build/macos-arm64-vulkan"
MLN_FFI_VCPKG_TARGET_TRIPLET = "arm64-osx-mln"
MLN_FFI_VCPKG_INSTALLED_DIR = "{{config_root}}/build/vcpkg/installed/macos-arm64-vulkan"
MLN_FFI_MACOSX_DEPLOYMENT_TARGET = "14.3"
MLN_FFI_ZIG_TARGET = "aarch64-macos"
MLN_FFI_ZIG_BUILD_ARGS = "-Dtarget=aarch64-macos -Dcmake-artifact-dir=\"{{env.MLN_FFI_BUILD_DIR}}\" -Drender-backend=vulkan -Dinclude-dir=\"{{env.MLN_FFI_INCLUDE_DIR}}\" -Dinclude-dir=\"{{env.MLN_FFI_VULKAN_INCLUDE_DIR}}\" -Ddependency-library-dir=\"{{env.MLN_FFI_VCPKG_INSTALLED_DIR}}/{{env.MLN_FFI_VCPKG_TARGET_TRIPLET}}/lib\""
MLN_FFI_SYSTEM_ROOT = "{% if os() == \"macos\" %}{% if env.SDKROOT is defined and env.SDKROOT != \"\" %}{{ env.SDKROOT }}{% else %}{{ exec(command='xcrun --sdk macosx --show-sdk-path', cache_key='macosx-sdk-path', cache_duration='1d') | trim }}{% endif %}{% endif %}"
MACOSX_DEPLOYMENT_TARGET = "{{env.MLN_FFI_MACOSX_DEPLOYMENT_TARGET}}"
PKG_CONFIG_PATH = "{{env.MLN_FFI_VCPKG_INSTALLED_DIR}}/{{env.MLN_FFI_VCPKG_TARGET_TRIPLET}}/lib/pkgconfig{% if env.PKG_CONFIG_PATH is defined and env.PKG_CONFIG_PATH != \"\" %}:{{env.PKG_CONFIG_PATH}}{% endif %}"
RUSTFLAGS = "-C link-arg=-Wl,-rpath,{{env.MLN_FFI_BUILD_DIR}}"
