[env]
MLN_FFI_RENDER_BACKEND = "opengl"
MLN_FFI_BUILD_DIR = "{{config_root}}/build/android-arm64-egl"
MLN_FFI_NATIVE_INSTALL_DIR = "{{config_root}}/build/android-arm64-egl/install"
PKG_CONFIG_PATH = "{{config_root}}/.pixi/envs/default/lib/pkgconfig"
PKG_CONFIG_ALLOW_CROSS = "1"
ANDROID_HOME = { required = true }
ANDROID_NDK_HOME = "{% if env.ANDROID_NDK_HOME is defined %}{{ env.ANDROID_NDK_HOME }}{% elif os() == \"macos\" %}{{ exec(command='find \"$HOME/Library/Android/sdk/ndk\" -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1') | trim }}{% elif os() == \"linux\" %}{{ exec(command='find \"$HOME/Android/Sdk/ndk\" -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1') | trim }}{% elif os() == \"windows\" %}{{ exec(command='find \"$LOCALAPPDATA/Android/Sdk/ndk\" -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1') | trim }}{% endif %}"
MLN_FFI_CMAKE_ARGS = """
-DCMAKE_TOOLCHAIN_FILE={{env.ANDROID_NDK_HOME}}/build/cmake/android.toolchain.cmake
-DANDROID_ABI=arm64-v8a
-DANDROID_PLATFORM=android-24
"""
MLN_FFI_ZIG_BUILD_ARGS = "-Dtarget=aarch64-linux-android"
MLN_FFI_ZIG_NATIVE_ARGS = "-Dnative-install-dir={{config_root}}/build/android-arm64-egl/install -Drender-backend=opengl -Ddependency-include-dir={{env.MLN_FFI_DEPENDENCY_INCLUDE_DIR}} -Ddependency-include-dir={{env.MLN_FFI_VULKAN_INCLUDE_DIR}} -Ddependency-library-dir={{env.MLN_FFI_DEPENDENCY_LIBRARY_DIR}}"
CARGO_BUILD_TARGET = "aarch64-linux-android"
