[env]
_.path = [
  "{{config_root}}/.pixi/envs/default/Library/bin",
  "{{config_root}}/build/windows-arm64-wgl",
]
MLN_FFI_RENDER_BACKEND = "opengl"
MLN_FFI_BUILD_DIR = "{{config_root}}/build/windows-arm64-wgl"
MLN_FFI_SYSTEM_ROOT = false
MLN_FFI_MSVC_HOST_ARCH = "arm64"
MLN_FFI_MSVC_TARGET_ARCH = "arm64"
MLN_FFI_DEPENDENCY_INCLUDE_DIR = "{{config_root}}/.pixi/envs/default/Library/include"
MLN_FFI_DEPENDENCY_LIBRARY_DIR = "{{config_root}}/.pixi/envs/default/Library/lib"
MLN_FFI_ZIG_BUILD_ARGS = "-Dtarget=aarch64-windows-msvc"
CARGO_BUILD_TARGET = "aarch64-pc-windows-msvc"
CMAKE_PREFIX_PATH = "{{config_root}}/.pixi/envs/default/Library"
CMAKE_LIBRARY_PATH = "{{env.MLN_FFI_DEPENDENCY_LIBRARY_DIR}}"
LIBCLANG_PATH = "{{config_root}}/.pixi/envs/default/Library/bin"
