[env]
CC = "clang"
CXX = "clang++"
MLN_FFI_VARIANT = "linux-x64-opengl"
MLN_FFI_TARGET_TRIPLE = "linux-x64"
MLN_FFI_RENDER_BACKEND = "opengl"
MLN_FFI_BUILD_DIR = "{{config_root}}/build/linux-x64-opengl"
MLN_FFI_ZIG_TARGET = "x86_64-linux-gnu"
DYLD_LIBRARY_PATH = "{{config_root}}/build/linux-x64-opengl"
LD_LIBRARY_PATH = "{{config_root}}/build/linux-x64-opengl"
