[env]
MLN_FFI_VARIANT = "linux-x64-egl"
MLN_FFI_TARGET_TRIPLE = "linux-x64"
MLN_FFI_RENDER_BACKEND = "opengl"
MLN_FFI_OPENGL_CONTEXT_PROVIDER = "egl"
MLN_FFI_BUILD_DIR = "{{config_root}}/build/linux-x64-egl"
MLN_FFI_ZIG_TARGET = "x86_64-linux-gnu"
