[env]
_.path = [
  "{{config_root}}/build/windows-arm64-vulkan",
]
MLN_FFI_VARIANT = "windows-arm64-vulkan"
MLN_FFI_TARGET_TRIPLE = "windows-arm64"
MLN_FFI_RENDER_BACKEND = "vulkan"
MLN_FFI_BUILD_DIR = "{{config_root}}/build/windows-arm64-vulkan"
MLN_FFI_VCPKG_TARGET_TRIPLET = "arm64-windows"
MLN_FFI_VCPKG_INSTALLED_DIR = "{{config_root}}/build/vcpkg/installed/windows-arm64-vulkan"
MLN_FFI_ZIG_TARGET = "aarch64-windows-msvc"
MLN_FFI_SYSTEM_ROOT = false
MLN_FFI_ZIG_BUILD_ARGS = "-Dtarget=aarch64-windows-msvc -Dcmake-artifact-dir=\"{{env.MLN_FFI_BUILD_DIR}}\" -Drender-backend=vulkan -Dinclude-dir=\"{{env.MLN_FFI_INCLUDE_DIR}}\" -Dinclude-dir=\"{{env.MLN_FFI_VULKAN_INCLUDE_DIR}}\""
