#!/usr/bin/env python3
"""Emits Kotlin external declarations for the C entry points the binding calls.

Kotlin/Wasm reaches the Emscripten module through JavaScript, so every call is a
`@JsFun` import over `Module._mln_*`. Declaring each one by name is what makes
the compiler check the call: an entry point's *declared* types decide whether an
argument crosses as a JavaScript number or as a BigInt, and the lowered wasm
signature cannot say, because it spells a pointer, an enum, and a handle alike
as `i32`.

Two lowerings apply on top of the declared types, both of them clang's:
a struct passed by value crosses as the address of a copy, and a function
returning a struct takes a hidden out-pointer and returns nothing.
`scripts/check-browser-exports.py` proves both against the linked module.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import wasm_c_api

PROLOGUE = """// Generated by scripts/generate-wasm-externs.py. Edit the generator.
//
// One declaration per C entry point this binding calls, lowered for
// wasm32-unknown-emscripten. Pointers are `Int` because the target is 32-bit;
// handles are `Long` because they are 64-bit and cross as BigInt. A function
// that returns a struct by value takes `out_return` and returns nothing.

package org.maplibre.nativeffi.internal.wasm.generated"""

#: The module the host installs on the pthread Kotlin runs on. A `@JsFun` body
#: is an arrow function, so the module object has to reach it through the global.
MODULE = "globalThis.__maplibreNativeC"

#: Resolved C types that cross as a 64-bit value. Everything else scalar is
#: 32-bit on wasm32, `long` and `size_t` included.
WIDE = ("long long", "unsigned long long")

FLOAT_TYPES = {"float": "Float", "double": "Double"}

#: Kotlin and JavaScript both reject some C parameter names as identifiers.
RESERVED = {
    "as", "break", "class", "continue", "do", "else", "false", "for", "fun",
    "if", "in", "interface", "is", "null", "object", "package", "return",
    "super", "this", "throw", "true", "try", "typealias", "typeof", "val",
    "var", "when", "while", "case", "catch", "const", "default", "delete",
    "enum", "export", "extends", "function", "import", "let", "new", "switch",
    "void", "with", "yield",
}  # fmt: skip


def kotlin_type(declarations: wasm_c_api.Declarations, c_type: str) -> str:
    """Reports how one declared C type crosses, or `Unit` for an aggregate."""
    resolved = declarations.resolve(c_type)
    if resolved.endswith("*") or "(*)" in resolved:
        return "Int"
    if resolved in WIDE:
        return "Long"
    if resolved in FLOAT_TYPES:
        return FLOAT_TYPES[resolved]
    if resolved == "void":
        return "Unit"
    if resolved.startswith(("struct ", "union ")):
        return "Unit"
    if resolved.startswith(
        ("int", "unsigned", "signed", "short", "long", "char", "bool", "_Bool")
    ):
        return "Int"
    raise SystemExit(f"no wasm lowering for the C type {c_type!r} ({resolved!r})")


def declaration(declarations: wasm_c_api.Declarations, name: str) -> str:
    entry = declarations.functions[name]
    returned = kotlin_type(declarations, entry["return"])
    aggregate = declarations.resolve(entry["return"]).startswith(("struct ", "union "))

    parameters: list[tuple[str, str]] = []
    if aggregate:
        parameters.append(("out_return", "Int"))
    for index, (parameter, c_type) in enumerate(entry["parameters"]):
        crossed = kotlin_type(declarations, c_type)
        if crossed == "Unit":
            # `(void)` carries no argument; a by-value struct crosses as the
            # address of the copy clang passes.
            if declarations.resolve(c_type) == "void":
                continue
            crossed = "Int"
        argument = parameter or f"argument{index}"
        parameters.append(
            (argument + "_" if argument in RESERVED else argument, crossed)
        )

    arguments = ", ".join(argument for argument, _ in parameters)
    call = f"{MODULE}._{name}({arguments})"
    body = f"({arguments}) => " + (
        f"{{ {call} }}" if aggregate or returned == "Unit" else call
    )
    signature = ", ".join(f"{argument}: {crossed}" for argument, crossed in parameters)
    result = "" if aggregate or returned == "Unit" else f": {returned}"
    return f'@JsFun("{body}")\ninternal external fun {name}({signature}){result}'


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    wasm_c_api.add_clang_arguments(parser)
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=wasm_c_api.DEFAULT_GENERATED / "EntryPoints.kt",
    )
    arguments = parser.parse_args(argv)
    sources = arguments.sources or list(wasm_c_api.DEFAULT_SOURCES)

    clang, sysroot = wasm_c_api.resolve_toolchain(arguments)
    declarations = wasm_c_api.read_declarations(clang, sysroot, arguments.include)
    referenced = wasm_c_api.referenced_identifiers(sources)

    called = sorted(set(declarations.functions) & referenced)
    if not called:
        raise SystemExit(
            f"no {wasm_c_api.PUBLIC_PREFIX}* entry point is named under "
            f"{', '.join(str(source) for source in sources)}"
        )
    lines = [PROLOGUE]
    for name in called:
        lines.append("")
        lines.append(declaration(declarations, name))

    wasm_c_api.write_if_changed(arguments.output, "\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
