#!/usr/bin/env python3
"""Emits Kotlin field accessors for the C API's descriptor structs.

The Kotlin/Wasm binding places every descriptor into the Emscripten heap by
writing fields at byte offsets, because the two modules cannot share memory.
Those offsets are not guessable: `mln_render_target_extent` opens with a `size`
field and its `double` forces a four-byte tail pad, so its fields sit at 0, 4, 8,
and 16 rather than the 0, 4, 8 a reader of the field list would assume. Getting
one wrong produces a descriptor native misreads, not a compile error.

So clang measures them for wasm32-unknown-emscripten, and the result is checked
in the way the JVM binding checks in its jextract output.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import wasm_c_api

PROLOGUE = """// Generated by scripts/generate-wasm-struct-layouts.py. Edit the generator.
//
// Offsets and sizes are measured for wasm32-unknown-emscripten by the pinned
// Emscripten clang, and cover the descriptors this binding names.
//
// The accessors exist so that no hand-written code names a *field* offset. An
// offset alone says where four bytes are, not whether they hold an integer, an
// enum, or a pointer, and reading a descriptor at the wrong width is the failure
// this generated layer exists to prevent. Hand-written code still positions its
// own scratch -- an out-parameter placed after a descriptor, say -- and those
// offsets belong to the caller rather than to any C struct.

package org.maplibre.nativeffi.internal.wasm.generated

import org.maplibre.nativeffi.internal.wasm.Heap
import org.maplibre.nativeffi.internal.wasm.HeapPointer"""

#: How each resolved C type is read and written through the Emscripten heap.
#: A type absent from this map gets no accessor: nested structs, arrays, and
#: function pointers are placed by their own object or by the caller, and
#: emitting a wrong-width accessor for one would be worse than emitting none.
#:
#: `long` and `unsigned long` are four bytes on wasm32, which is why they share
#: the 32-bit reader with `int`.
SCALAR_ACCESSORS = {
    # C23 spells it `bool`, and a header included from C++ spells it `_Bool`.
    "bool": (
        "Boolean",
        "Heap.loadByte({p}) != 0.toByte()",
        "Heap.storeByte({p}, if ({v}) 1 else 0)",
    ),
    "_Bool": (
        "Boolean",
        "Heap.loadByte({p}) != 0.toByte()",
        "Heap.storeByte({p}, if ({v}) 1 else 0)",
    ),
    "char": ("Int", "Heap.loadByte({p}).toInt()", "Heap.storeByte({p}, {v}.toByte())"),
    "signed char": (
        "Int",
        "Heap.loadByte({p}).toInt()",
        "Heap.storeByte({p}, {v}.toByte())",
    ),
    "unsigned char": (
        "Int",
        "Heap.loadByte({p}).toInt() and 0xFF",
        "Heap.storeByte({p}, {v}.toByte())",
    ),
    "short": ("Int", "Heap.loadShort({p})", "Heap.storeShort({p}, {v})"),
    "unsigned short": ("Int", "Heap.loadUShort({p})", "Heap.storeShort({p}, {v})"),
    "int": ("Int", "Heap.loadInt({p})", "Heap.storeInt({p}, {v})"),
    "unsigned int": ("Int", "Heap.loadInt({p})", "Heap.storeInt({p}, {v})"),
    "long": ("Int", "Heap.loadInt({p})", "Heap.storeInt({p}, {v})"),
    "unsigned long": ("Int", "Heap.loadInt({p})", "Heap.storeInt({p}, {v})"),
    "long long": ("Long", "Heap.loadLong({p})", "Heap.storeLong({p}, {v})"),
    "unsigned long long": ("Long", "Heap.loadLong({p})", "Heap.storeLong({p}, {v})"),
    "float": ("Float", "Heap.loadFloat({p})", "Heap.storeFloat({p}, {v})"),
    "double": ("Double", "Heap.loadDouble({p})", "Heap.storeDouble({p}, {v})"),
}


def accessor(field: str, resolved: str, offset: int) -> str:
    """Emits one field's getter and setter, or nothing for a type it cannot place."""
    name = wasm_c_api.member_name(field)
    capitalized = name[0].upper() + name[1:]
    if resolved.endswith("*"):
        return (
            f"  fun {name}(base: HeapPointer): HeapPointer = "
            f"HeapPointer(Heap.loadInt(base + {offset}))\n"
            f"  fun set{capitalized}(base: HeapPointer, value: HeapPointer) {{ "
            f"Heap.storeInt(base + {offset}, value.address) }}"
        )
    if resolved not in SCALAR_ACCESSORS:
        return ""
    kotlin_type, load, store = SCALAR_ACCESSORS[resolved]
    getter = load.format(p=f"base + {offset}")
    setter = store.format(p=f"base + {offset}", v="value")
    return (
        f"  fun {name}(base: HeapPointer): {kotlin_type} = {getter}\n"
        f"  fun set{capitalized}(base: HeapPointer, value: {kotlin_type}) {{ "
        f"{setter} }}"
    )


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    wasm_c_api.add_clang_arguments(parser)
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=wasm_c_api.DEFAULT_GENERATED / "StructLayouts.kt",
    )
    arguments = parser.parse_args(argv)
    sources = arguments.sources or list(wasm_c_api.DEFAULT_SOURCES)

    clang, sysroot = wasm_c_api.resolve_toolchain(arguments)
    declarations = wasm_c_api.read_declarations(clang, sysroot, arguments.include)
    layouts = wasm_c_api.read_layouts(clang, sysroot, arguments.include, declarations)
    referenced = wasm_c_api.referenced_identifiers(sources)

    lines = [PROLOGUE]

    # The header's own enum values, so a binding never writes `1 shl 5` beside a
    # field name. A bit that moves in the headers moves here.
    for name in sorted(declarations.enums):
        constants = declarations.enums[name]
        kotlin = wasm_c_api.object_name(name)
        if not constants or kotlin not in referenced:
            continue
        lines.append("")
        lines.append(f"/** Values of `enum {name}`. */")
        lines.append(f"internal object {kotlin} {{")
        for constant, value in sorted(constants.items(), key=lambda entry: entry[1]):
            # Kotlin has no unsigned Int literal, so a flag on bit 31 arrives as
            # its two's-complement value. The bits are what native compares.
            signed = value - (1 << 32) if value >= (1 << 31) else value
            lines.append(f"  const val {constant}: Int = {signed}")
        lines.append("}")

    # One accessor object per struct, so a caller writes a named field rather
    # than an offset and a width.
    for name in sorted(layouts):
        kotlin = wasm_c_api.object_name(name)
        if kotlin not in referenced:
            continue
        members = []
        for field, declared, offset in layouts[name]["fields"]:
            if not field:
                continue
            emitted = accessor(field, declarations.resolve(declared), offset)
            # A field with an accessor publishes no offset. Publishing one would
            # let a caller reach past the width-safe setter and store the wrong
            # size at the right place. A nested struct, union, array, or function
            # pointer has no accessor, and the offset is how a caller reaches it
            # and hands it to that struct's own object.
            members.append(
                emitted or f"  const val OFFSET_{field.upper()}: Int = {offset}"
            )
        if not members:
            continue
        lines.append("")
        tag = declarations.records[name]["tag"]
        lines.append(f"/** Fields of `{tag} {name}`. */")
        lines.append(f"internal object {kotlin} {{")
        lines.append(f"  const val SIZEOF: Int = {layouts[name]['size']}")
        lines.extend(members)
        lines.append("}")

    wasm_c_api.write_if_changed(arguments.output, "\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
