#!/usr/bin/env python3
"""Emits Kotlin struct-layout constants from the browser ABI manifest.

The Kotlin/Wasm binding places every descriptor into the Emscripten heap by
writing fields at byte offsets, because the two modules cannot share memory.
Those offsets are not guessable: `mln_render_target_extent` opens with a `size`
field and its `double` forces a four-byte tail pad, so its fields sit at 0, 4, 8,
and 16 rather than the 0, 4, 8 a reader of the field list would assume. Getting
one wrong produces a descriptor native misreads, not a compile error.

So they are generated from the manifest, which measured them with the pinned
Emscripten clang, and checked in the way the JVM binding checks in its jextract
output.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

PROLOGUE = """// Generated by scripts/generate-wasm-struct-layouts.py from the browser ABI
// manifest. Edit neither; change the generator or the manifest it reads.
//
// Offsets, sizes, and field accessors are measured for wasm32-unknown-emscripten.
// A host that loads a browser module built from different headers is rejected
// before any of these are used; see BrowserModule.
//
// The accessors exist so that no hand-written code names a *field* offset. An
// offset alone says where four bytes are, not whether they hold an integer, an
// enum, or a pointer, and reading a descriptor at the wrong width is the failure
// this generated layer exists to prevent. Hand-written code still positions its
// own scratch -- an out-parameter placed after a descriptor, say -- and those
// offsets belong to the caller rather than to any C struct.

package org.maplibre.nativeffi.internal.wasm.generated

import org.maplibre.nativeffi.internal.wasm.Heap
import org.maplibre.nativeffi.internal.wasm.HeapPointer

/** Byte offsets and sizes of the C API's descriptor structs. */
internal object StructLayouts {
  /**
   * Digest of the headers these offsets were measured from.
   *
   * The loader refuses a browser module whose manifest reports a different one. Nothing else can
   * catch that mismatch: the documented C ABI version stays zero for the whole prerelease, so a
   * module built from other headers reports the same version and the first descriptor written at
   * these offsets corrupts its heap.
   */
  const val HEADERS_DIGEST: String = "@HEADERS_DIGEST@"

"""


def kotlin_name(c_name: str) -> str:
    """`mln_render_target_extent` becomes `MLN_RENDER_TARGET_EXTENT`."""
    return c_name.upper()


def object_name(c_name: str) -> str:
    """`mln_render_target_extent` becomes `MlnRenderTargetExtent`."""
    return "".join(part.capitalize() for part in c_name.split("_"))


def field_name(c_field: str) -> str:
    """`scale_factor` becomes `scaleFactor`."""
    head, *rest = c_field.split("_")
    return head + "".join(part.capitalize() for part in rest)


#: How each declared C type is read and written through the Emscripten heap.
#: A type absent from this map gets no accessor: nested structs, arrays, and
#: function pointers are placed by their own object or by the caller, and
#: emitting a wrong-width accessor for one would be worse than emitting none.
SCALAR_ACCESSORS = {
    # Keyed on the *canonical* type as well as the fixed-width spelling, because
    # a typedef's name says nothing about its width: `mln_offline_region_id` is a
    # `uint64_t`, and only the desugared form says so. Clang reports `uint32_t`
    # as itself for a field declared that way and `unsigned int` only where a
    # typedef resolved to one, so both forms are keys.
    #
    # `long` and `unsigned long` are four bytes on wasm32, which is why they
    # share the 32-bit reader with `int`.
    "_Bool": (
        "Boolean",
        "Heap.loadByte({p}) != 0.toByte()",
        "Heap.storeByte({p}, if ({v}) 1 else 0)",
    ),
    "bool": (
        "Boolean",
        "Heap.loadByte({p}) != 0.toByte()",
        "Heap.storeByte({p}, if ({v}) 1 else 0)",
    ),
    "signed char": (
        "Int",
        "Heap.loadByte({p}).toInt()",
        "Heap.storeByte({p}, {v}.toByte())",
    ),
    "unsigned char": (
        "Int",
        "Heap.loadByte({p}).toInt() and 0xFF",
        "Heap.storeByte({p}, {v}.toByte())",
    ),
    "uint8_t": (
        "Int",
        "Heap.loadByte({p}).toInt() and 0xFF",
        "Heap.storeByte({p}, {v}.toByte())",
    ),
    "int8_t": (
        "Int",
        "Heap.loadByte({p}).toInt()",
        "Heap.storeByte({p}, {v}.toByte())",
    ),
    "short": ("Int", "Heap.loadShort({p})", "Heap.storeShort({p}, {v})"),
    "unsigned short": ("Int", "Heap.loadUShort({p})", "Heap.storeShort({p}, {v})"),
    "int16_t": ("Int", "Heap.loadShort({p})", "Heap.storeShort({p}, {v})"),
    "uint16_t": ("Int", "Heap.loadUShort({p})", "Heap.storeShort({p}, {v})"),
    "int": ("Int", "Heap.loadInt({p})", "Heap.storeInt({p}, {v})"),
    "unsigned int": ("Int", "Heap.loadInt({p})", "Heap.storeInt({p}, {v})"),
    "long": ("Int", "Heap.loadInt({p})", "Heap.storeInt({p}, {v})"),
    "unsigned long": ("Int", "Heap.loadInt({p})", "Heap.storeInt({p}, {v})"),
    "uint32_t": ("Int", "Heap.loadInt({p})", "Heap.storeInt({p}, {v})"),
    "int32_t": ("Int", "Heap.loadInt({p})", "Heap.storeInt({p}, {v})"),
    "size_t": ("Int", "Heap.loadInt({p})", "Heap.storeInt({p}, {v})"),
    "long long": ("Long", "Heap.loadLong({p})", "Heap.storeLong({p}, {v})"),
    "unsigned long long": ("Long", "Heap.loadLong({p})", "Heap.storeLong({p}, {v})"),
    "uint64_t": ("Long", "Heap.loadLong({p})", "Heap.storeLong({p}, {v})"),
    "int64_t": ("Long", "Heap.loadLong({p})", "Heap.storeLong({p}, {v})"),
    "float": ("Float", "Heap.loadFloat({p})", "Heap.storeFloat({p}, {v})"),
    "double": ("Double", "Heap.loadDouble({p})", "Heap.storeDouble({p}, {v})"),
}


def accessor(c_field: str, entry: dict) -> str:
    """Emits one field's getter and setter, or nothing for a type it cannot place."""
    c_type = entry.get("canonical", entry["type"]).strip()
    offset = entry["offset"]
    name = field_name(c_field)
    if c_type.endswith("*"):
        return (
            f"  fun {name}(base: HeapPointer): HeapPointer = "
            f"HeapPointer(Heap.loadInt(base + {offset}))\n"
            f"  fun set{name[0].upper()}{name[1:]}(base: HeapPointer, value: HeapPointer) {{ "
            f"Heap.storeInt(base + {offset}, value.address) }}"
        )
    if c_type not in SCALAR_ACCESSORS:
        return ""
    kotlin_type, load, store = SCALAR_ACCESSORS[c_type]
    getter = load.format(p=f"base + {offset}")
    setter = store.format(p=f"base + {offset}", v="value")
    return (
        f"  fun {name}(base: HeapPointer): {kotlin_type} = {getter}\n"
        f"  fun set{name[0].upper()}{name[1:]}(base: HeapPointer, value: {kotlin_type}) {{ "
        f"{setter} }}"
    )


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("manifest", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    arguments = parser.parse_args(argv)

    manifest = json.loads(arguments.manifest.read_text())
    structs = manifest.get("structs")
    if not structs:
        raise SystemExit(f"{arguments.manifest} carries no struct layouts")

    digest = manifest.get("headersDigest")
    if not digest:
        raise SystemExit(f"{arguments.manifest} carries no headersDigest")
    lines = [PROLOGUE.replace("@HEADERS_DIGEST@", digest)]
    lines.append("}")

    # The header's own enum values, so a binding never writes `1 shl 5` beside a
    # field name and hopes. A bit that moves in the headers moves here.
    enums = manifest.get("enums") or {}
    for name in sorted(enums):
        constants = enums[name]
        if not constants:
            continue
        lines.append("")
        lines.append(f"/** Values of `enum {name}`. */")
        lines.append(f"internal object {object_name(name)} {{")
        for constant, value in sorted(constants.items(), key=lambda e: e[1]):
            # Kotlin has no unsigned Int literal, so a flag on bit 31 arrives as
            # its two's-complement value. The bits are what native compares.
            signed = value - (1 << 32) if value >= (1 << 31) else value
            lines.append(f"  const val {constant}: Int = {signed}")
        lines.append("}")

    # One accessor object per struct, so a caller writes a named field rather
    # than an offset and a width.
    for name in sorted(structs):
        layout = structs[name]
        members = []
        for field, entry in sorted(
            layout["fields"].items(), key=lambda e: e[1]["offset"]
        ):
            emitted = accessor(field, entry)
            if emitted:
                # A field with an accessor publishes no offset. Publishing one
                # would let a caller reach past the width-safe setter and store
                # the wrong size at the right place, which is the failure the
                # accessors exist to remove.
                members.append(emitted)
            else:
                # A nested struct, union, array, or function pointer has no
                # accessor of its own. The offset is how a caller reaches it and
                # hands it to that struct's own object.
                members.append(
                    f"  const val OFFSET_{field.upper()}: Int = {entry['offset']}"
                )
        accessors = members
        if not accessors:
            continue
        lines.append("")
        lines.append(f"/** Fields of `struct {name}`. */")
        lines.append(f"internal object {object_name(name)} {{")
        lines.append(f"  const val SIZEOF: Int = {layout['size']}")
        lines.extend(accessors)
        lines.append("}")
    text = "\n".join(lines) + "\n"

    if arguments.output.exists() and arguments.output.read_text() == text:
        return 0
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
