"""Aggregate the monorepo's project tools for the devcontainer image.

mise has no config include, so the devcontainer's tool list is generated from
the project configs. `mise install --monorepo` is not a substitute: `mise oci
build` packages only the config it runs on and that config's parents.
"""

from __future__ import annotations

import pathlib
import re
import tomllib


MARKER_BEGIN = "# BEGIN generated tools"
MARKER_END = "# END generated tools"

HEADER = """\
# The published devcontainer is the aggregate environment: every tool used by a
# binding, example, or docs project, while normal root installs stay lean.
# Generated by `mise run ci:generate-devcontainer-tools`. Do not edit directly.\
"""

TOOLS_PATTERN = re.compile(r"^\[tools\]\n(.*?)(?=^\[|\Z)", re.M | re.S)


def project_configs(root: pathlib.Path) -> list[pathlib.Path]:
    """Every monorepo project config except the aggregate itself."""
    with (root / "mise.toml").open("rb") as file:
        config_roots = tomllib.load(file)["monorepo"]["config_roots"]
    paths = []
    for pattern in config_roots:
        if pattern == ".devcontainer":
            continue
        for directory in sorted(root.glob(pattern)):
            config = directory / "mise.toml"
            if config.is_file():
                paths.append(config)
    return paths


def tool_lines(config: pathlib.Path) -> dict[str, str]:
    """Map each tool in a config's `[tools]` table to its source line.

    Reusing the source line keeps the aggregate formatted exactly like the
    project configs, which the formatter has already normalized.
    """
    match = TOOLS_PATTERN.search(config.read_text())
    if not match:
        return {}
    lines = {}
    for line in match.group(1).splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        key = stripped.split("=", 1)[0].strip()
        lines[key.strip('"')] = stripped
    return lines


def aggregate(root: pathlib.Path) -> str:
    tools: dict[str, str] = {}
    sources: dict[str, pathlib.Path] = {}
    for config in project_configs(root):
        for tool, line in tool_lines(config).items():
            previous = tools.get(tool)
            if previous is not None and previous != line:
                raise SystemExit(
                    f"error: {tool} is declared differently in "
                    f"{sources[tool].relative_to(root)} and "
                    f"{config.relative_to(root)}:\n  {previous}\n  {line}"
                )
            tools[tool] = line
            sources.setdefault(tool, config)
    body = "\n".join(tools[tool] for tool in sorted(tools))
    return f"{MARKER_BEGIN}\n{HEADER}\n[tools]\n{body}\n{MARKER_END}"


def render(root: pathlib.Path) -> str:
    """The devcontainer config with its generated tools block replaced."""
    output = root / ".devcontainer" / "mise.toml"
    text = output.read_text()
    pattern = re.compile(
        rf"{re.escape(MARKER_BEGIN)}\n.*?{re.escape(MARKER_END)}", re.S
    )
    if not pattern.search(text):
        raise SystemExit(
            f"error: {output.relative_to(root)} is missing the "
            f"`{MARKER_BEGIN}` / `{MARKER_END}` markers"
        )
    return pattern.sub(lambda _: aggregate(root), text)
