"""Generate CI workflows from coverage groups and native target commands."""

from __future__ import annotations

import argparse
import difflib
import io
import json
import pathlib
import re
import sys

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap
from ruamel.yaml.scalarstring import LiteralScalarString

from ci.action_pins import catalog
from ci.coverage import GROUPS, check_name, group_targets, workflow_file, workflow_name
from ci.workflow import load_configuration, platform, target_rows

ROOT = pathlib.Path(__file__).resolve().parents[1]
GENERATED = "Generated by `mise run ci:generate-workflow`. Do not edit directly."
PINS = catalog(ROOT)
SCCACHE_ENVIRONMENT = "${{ github.event_name == 'push' && 'sccache' || '' }}"
RETENTION = "${{ github.event_name == 'pull_request' && 1 || 30 }}"

# These platforms supply native inputs to Kotlin Maven staging. The full run
# also retains its verified Maven repository for snapshot publication.
KOTLIN_MAVEN_PLATFORMS = {
    "android",
    "linux-gnu",
    "macos",
    "ios",
    "ios-simulator",
    "tvos",
    "tvos-simulator",
    "windows",
}
KOTLIN_SNAPSHOT_VERSION = "0.1.0-SNAPSHOT"


def action(reference: str, inputs: dict | None = None, **fields) -> dict:
    pin = PINS[reference]
    step = CommentedMap({**fields, "uses": f"{pin.action}@{pin.sha}"})
    step.yaml_add_eol_comment(pin.version, "uses", column=0)
    if inputs:
        step["with"] = inputs
    return step


def checkout() -> dict:
    return action("actions/checkout", {"persist-credentials": False})


def run(command: str, **fields) -> dict:
    return {
        **fields,
        "run": LiteralScalarString(command) if "\n" in command else command,
    }


def setup(
    target: str | None = None, *, zig=False, gradle=True, save_toolchains=False
) -> list[dict]:
    inputs = {
        "sccache-access-key-id": "${{ secrets.R2_SCCACHE_ACCESS_KEY_ID }}",
        "sccache-secret-access-key": "${{ secrets.R2_SCCACHE_SECRET_ACCESS_KEY }}",
    }
    if target:
        inputs["target"] = target
    if zig:
        inputs["zig"] = True
    if not gradle:
        inputs["gradle"] = False
    if save_toolchains:
        inputs["save-toolchains"] = True
    return [
        checkout(),
        {"uses": "./.github/actions/setup-ci-deps", "id": "setup", "with": inputs},
    ]


def target_job(row: dict) -> dict:
    preset = row["preset"]
    steps = setup(
        preset,
        zig=row["zig"],
        gradle=row["gradle"],
        save_toolchains=row["save_toolchains"],
    )
    steps.extend(run(command) for command in row["native_commands"])
    if row["package"]:
        steps.extend(
            [
                run(
                    f"mise run archive-native {preset}", name="Archive native artifact"
                ),
                run(
                    f"mise run install-native-package {preset} "
                    f"build/packages/native/dist/maplibre-native-c-{preset}.tar.gz",
                    name="Install packaged native artifact",
                ),
                *[
                    run(command, env={"MISE_TASK_SKIP": "//:build"})
                    for command in row["consumer_commands"]
                ],
            ]
        )
    # A failed job must not claim the immutable shared Zig cache with a partial
    # set of packages. Only rows covering every Zig project can save it.
    if row["zig"]:
        steps.append(
            action(
                "actions/cache/save",
                {
                    "path": LiteralScalarString(
                        "~/.cache/zig/p\n~/AppData/Local/zig/p\n"
                    ),
                    "key": "${{ steps.setup.outputs.zig-cache-key }}",
                },
                name="Save Zig packages",
                **{"if": "steps.setup.outputs.zig-cache-hit != 'true'"},
            )
        )
    if row["package"]:
        steps.append(
            action(
                "actions/upload-artifact",
                {
                    "name": f"native-package-{preset}-${{{{ github.sha }}}}",
                    "path": f"build/packages/native/dist/maplibre-native-c-{preset}.tar.gz",
                    "if-no-files-found": "error",
                    "retention-days": RETENTION,
                },
                name="Upload native artifact",
            )
        )
    return {
        "name": f"target / {preset}",
        "runs-on": row["runner"],
        "timeout-minutes": 120,
        "environment": SCCACHE_ENVIRONMENT,
        "steps": steps,
    }


def hygiene_job() -> dict:
    commands = [
        "mise run ci:generate-workflow --check",
        "mise run ci:generate-devcontainer-tools --check",
        "mise run ci:test",
        "mise run --force //bindings/dart:ffigen",
        "mise run --force //bindings/dotnet:generate",
        "mise run --force //bindings/kotlin:generate",
        "dprint output-resolved-config > /dev/null",
        "mise run fix",
    ]
    return {
        "name": "hygiene",
        "runs-on": "ubuntu-latest",
        "timeout-minutes": 30,
        "environment": SCCACHE_ENVIRONMENT,
        "steps": [
            *setup(gradle=False),
            *[run(command) for command in commands],
            run(
                "git update-index -q --refresh\n"
                "git diff --exit-code -- . ':(exclude)mise*.lock'\n"
                "git diff --cached --exit-code -- . ':(exclude)mise*.lock'\n",
                name="Check generated and formatted files",
            ),
        ],
    }


def docs_job() -> dict:
    versions = (ROOT / "gradle/libs.versions.toml").read_text()
    match = re.search(r'^android-compileSdk = "(\d+)"\s*$', versions, re.MULTILINE)
    if match is None:
        raise ValueError("android-compileSdk missing from gradle/libs.versions.toml")
    # Dokka configures the Android target and requires its SDK platform.
    return {
        "name": "docs",
        "runs-on": "ubuntu-latest",
        "timeout-minutes": 60,
        "environment": SCCACHE_ENVIRONMENT,
        "steps": [
            *setup(),
            action(
                "android-actions/setup-android",
                {
                    "packages": f"platform-tools platforms;android-{match[1]}",
                },
            ),
            run("mise run //docs:build"),
        ],
    }


def android_multi_job(rows: list[dict]) -> dict:
    return {
        "name": "Android multi-ABI packaging",
        "runs-on": "ubuntu-latest",
        "timeout-minutes": 30,
        "environment": SCCACHE_ENVIRONMENT,
        "needs": [
            f"target-{row['preset']}"
            for row in rows
            if platform(row["preset"]) == "android" and row["package"]
        ],
        "steps": [
            *setup("android-multi"),
            action(
                "actions/download-artifact",
                {
                    "pattern": "native-package-android-*-${{ github.sha }}",
                    "path": "build/packages/native/android-multi-input",
                },
                name="Download Android native artifacts",
            ),
            run(
                "mise run //:kotlin:verify-android-multi-abi build/packages/native/android-multi-input",
            ),
        ],
    }


def kotlin_maven_job(rows: list[dict]) -> dict:
    return {
        "name": "Kotlin Maven",
        "permissions": {"actions": "read", "contents": "read"},
        "needs": [
            f"target-{row['preset']}"
            for row in rows
            if row["package"] and platform(row["preset"]) in KOTLIN_MAVEN_PLATFORMS
        ],
        "uses": "./.github/workflows/_kotlin-maven.yml",
        "with": {
            "publish": False,
            "run_id": "${{ github.run_id }}",
            "sha": "${{ github.sha }}",
            "verified_retention_days": RETENTION,
            "version": KOTLIN_SNAPSHOT_VERSION,
        },
    }


def suite(source: dict, presets: dict, group: str) -> dict:
    selected = group_targets(source, presets, group)
    rows = [row for row in target_rows(source, presets) if row["preset"] in selected]
    jobs = {}
    if group in {"baseline", "extended"}:
        jobs.update(hygiene=hygiene_job(), docs=docs_job())
    jobs.update({f"target-{row['preset']}": target_job(row) for row in rows})
    if group == "extended":
        jobs["android-multi"] = android_multi_job(rows)
        jobs["kotlin-maven"] = kotlin_maven_job(rows)
    for name, job in jobs.items():
        job["if"] = f"contains(fromJSON(inputs.jobs), '{name}')"
    jobs["verified"] = {
        "name": "verified (${{ github.sha }} / ${{ inputs.scope }})",
        "runs-on": "ubuntu-slim",
        "timeout-minutes": 5,
        "if": "always()",
        "needs": list(jobs),
        "steps": [
            run(
                'jq -e -n --argjson expected "$EXPECTED" --argjson results "$RESULTS" --argjson selected "$SELECTED" '
                "  '($expected == ($results | keys)) and ($selected | length > 0)\n"
                "   and (($selected - $expected) | length == 0)\n"
                "   and all($expected[]; . as $job | $results[$job].result ==\n"
                '     (if $selected | index($job) then "success" else "skipped" end))\'\n',
                name="Require every coverage job",
                env={
                    "EXPECTED": json.dumps(sorted(jobs)),
                    "RESULTS": "${{ toJSON(needs) }}",
                    "SELECTED": "${{ inputs.jobs }}",
                },
            )
        ],
    }
    return {
        "name": f"CI {group} coverage",
        "on": {
            "workflow_call": {
                "inputs": {
                    key: {"type": "string", "required": True}
                    for key in ("scope", "jobs")
                }
            }
        },
        "permissions": {"contents": "read", "actions": "read"},
        "jobs": jobs,
    }


def caller(group: str) -> dict:
    events = {}
    if group == "extended":
        events.update(push={"branches": ["main"]}, workflow_dispatch=None)
    actions = ["opened", "synchronize", "reopened"]
    if group == "ready":
        actions.extend(["ready_for_review", "converted_to_draft"])
    elif group != "baseline":
        actions.extend(["labeled", "unlabeled"])
    events["pull_request"] = {"types": actions}
    return {
        "name": workflow_name(group),
        "on": events,
        "permissions": {"contents": "read", "actions": "read"},
        "concurrency": {
            "group": "${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}",
            "cancel-in-progress": "${{ github.event.action == 'synchronize' }}",
        },
        "jobs": {
            "plan": {
                "runs-on": "ubuntu-slim",
                "timeout-minutes": 5,
                "outputs": {
                    key: f"${{{{ steps.plan.outputs.{key} }}}}"
                    for key in ("mode", "result", "scope", "jobs")
                },
                "steps": [
                    checkout(),
                    run(
                        "bash .mise/tasks/ci/plan",
                        id="plan",
                        env={"CI_GROUP": group, "GH_TOKEN": "${{ github.token }}"},
                    ),
                ],
            },
            "coverage": {
                "name": "coverage",
                "needs": "plan",
                "if": "needs.plan.outputs.mode == 'run'",
                "uses": f"./.github/workflows/_ci-{group}.yml",
                "with": {
                    key: f"${{{{ needs.plan.outputs.{key} }}}}"
                    for key in ("scope", "jobs")
                },
                "secrets": "inherit",
            },
            "required": {
                "name": check_name(group),
                "runs-on": "ubuntu-slim",
                "timeout-minutes": 5,
                "if": "always()",
                "needs": ["plan", "coverage"],
                "steps": [
                    run(
                        'test "$PLAN" = success\n'
                        'case "$MODE" in\n'
                        '  run) test "$RESULT" = success ;;\n'
                        '  reuse) test "$RESULT" = skipped && test "$PREVIOUS" = success ;;\n'
                        '  omit) test "$RESULT" = skipped ;;\n'
                        "  *) exit 1 ;;\n"
                        "esac\n",
                        name="Check coverage result",
                        env={
                            "PLAN": "${{ needs.plan.result }}",
                            "MODE": "${{ needs.plan.outputs.mode }}",
                            "PREVIOUS": "${{ needs.plan.outputs.result }}",
                            "RESULT": "${{ needs.coverage.result }}",
                        },
                    )
                ],
            },
        },
    }


def retry_workflow() -> dict:
    # workflow_run gets a write token. Its checkout must stay on the trusted
    # default-branch commit, never the PR that triggered the failed run.
    trusted_checkout = action(
        "actions/checkout", {"ref": "${{ github.sha }}", "persist-credentials": False}
    )
    return {
        "name": "CI retry",
        "on": {
            "workflow_run": {
                "workflows": [workflow_name(group) for group in GROUPS],
                "types": ["completed"],
            }
        },
        "permissions": {"contents": "read", "actions": "write"},
        "concurrency": {
            "group": "${{ github.workflow }}-${{ github.event.workflow_run.id }}",
            "cancel-in-progress": False,
        },
        "jobs": {
            "retry": {
                "runs-on": "ubuntu-slim",
                "timeout-minutes": 5,
                "if": "github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt == 1",
                "steps": [
                    trusted_checkout,
                    run(
                        "python3 -m ci.retry",
                        name="Retry failed jobs and their dependents",
                        env={
                            "GH_TOKEN": "${{ github.token }}",
                            "CI_RUN_ID": "${{ github.event.workflow_run.id }}",
                        },
                    ),
                ],
            }
        },
    }


def workflows(source: dict, presets: dict) -> dict[str, dict]:
    result = {}
    for group in GROUPS:
        result[workflow_file(group)] = caller(group)
        result[f"_ci-{group}.yml"] = suite(source, presets, group)
    result["ci-retry.yml"] = retry_workflow()
    return result


def serialize(workflow: dict) -> str:
    yaml = YAML()
    yaml.indent(mapping=2, sequence=4, offset=2)
    yaml.width = 4096
    document = CommentedMap(workflow)
    document.yaml_set_start_comment(GENERATED)
    stream = io.StringIO()
    yaml.dump(document, stream)
    return stream.getvalue()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = workflows(*load_configuration(ROOT))
    directory = ROOT / ".github/workflows"
    valid = True
    for name, workflow in outputs.items():
        path = directory / name
        expected = serialize(workflow)
        actual = path.read_text() if path.exists() else ""
        if args.check:
            if actual != expected:
                valid = False
                sys.stderr.writelines(
                    difflib.unified_diff(
                        actual.splitlines(keepends=True),
                        expected.splitlines(keepends=True),
                        fromfile=str(path),
                        tofile=f"{path} (generated)",
                    )
                )
        else:
            path.write_text(expected)
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
