include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/src/internal/c/*.g.dart
    - tool/flutter_smoke/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
