// Generated by tools/bindgen. Do not edit.
#pragma once
#include <maplibre_native_c.h>
inline bool mln_android_custom_geometry_source_options_has_callbacks(
  const mln_custom_geometry_source_options* source
) {
  return source->fetch_tile != nullptr || source->cancel_tile != nullptr;
}
inline bool mln_android_custom_mvt_vector_source_options_has_callbacks(
  const mln_custom_mvt_vector_source_options* source
) {
  return source->fetch_tile != nullptr || source->cancel_tile != nullptr;
}
inline bool mln_android_wake_has_callbacks(const mln_wake* source) {
  return source->callback != nullptr;
}
