[package]
name = "rust-map"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
glow = "0.16.0"
glutin = "0.31.3"
glutin-winit = "0.4.2"
maplibre-native = { path = "../../bindings/rust/crates/maplibre-native" }
raw-window-handle = "0.6.2"
raw-window-handle05 = { package = "raw-window-handle", version = "0.5.2" }
winit = { version = "0.29.15", features = ["rwh_05", "rwh_06"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.5.2"
objc2-app-kit = { version = "0.2.2", features = ["NSResponder", "NSView", "objc2-quartz-core"] }
objc2-foundation = { version = "0.2.2", features = ["NSError", "NSGeometry", "NSObject", "NSString"] }
objc2-metal = { version = "0.2.2", features = ["MTLCommandBuffer", "MTLCommandEncoder", "MTLCommandQueue", "MTLDevice", "MTLDrawable", "MTLLibrary", "MTLPixelFormat", "MTLRenderCommandEncoder", "MTLRenderPass", "MTLRenderPipeline", "MTLResource", "MTLTexture"] }
objc2-quartz-core = { version = "0.2.2", features = ["CALayer", "CAMetalLayer", "objc2-metal"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Graphics_Gdi"] }
