//! Compatibility crate for the Java JNI binding package.
//!
//! The JNI bridge is generated by JavaCPP from the public C ABI as part of the
//! Gradle build. This crate remains in the workspace so existing contributor
//! validation commands can continue to target `maplibre-native-jni` while the
//! production JNI boundary no longer routes through Rust.

/// Reports that the Java JNI Rust bridge has been retired.
pub const JAVACPP_BRIDGE: &str = "javacpp";

#[cfg(test)]
mod tests {
    #[test]
    fn records_javacpp_bridge() {
        assert_eq!(super::JAVACPP_BRIDGE, "javacpp");
    }
}
