//! Workspace marker crate for the Java JNI binding package.
//!
//! The JNI bridge is generated by JavaCPP from the public C ABI as part of the
//! Gradle build. This crate keeps the package addressable by contributor
//! validation commands without participating in the production JNI boundary.

/// Reports that the Java JNI bridge is generated by JavaCPP.
pub const JAVACPP_BRIDGE: &str = "javacpp";

#[cfg(test)]
mod tests {
    #[test]
    fn records_javacpp_bridge() {
        assert_eq!(super::JAVACPP_BRIDGE, "javacpp");
    }
}
