[tasks.build]
usage = 'arg "[preset]" default="{{vars.host_native_preset}}"'
depends = [{ task = "//:build", args = ["{{usage.preset}}"] }]
run = '''
../../gradlew :examples:compose-map:build \
  -PmaplibreNativeCInstallDir="../../build/$usage_preset/install"
'''

[tasks.run]
depends = ["//:build"]
run = '''
../../gradlew :examples:compose-map:run \
  -PmaplibreNativeCInstallDir="{{vars.host_native_install_dir}}"
'''
