[tools]
"core:java" = "{{vars.java_version}}"

[tasks.build]
usage = 'arg "[preset]" default="{{vars.host_native_preset}}"'
depends = [{ task = "//:build", args = ["{{usage.preset}}"] }]
dir = "../.."
run = '''
./gradlew \
  -PmaplibreNativeCInstallDir="build/$usage_preset/install" \
  :examples:lwjgl-map:build
'''

[tasks.run]
usage = '''
arg "[render-target]" default="owned-texture" {
  choices "owned-texture" "borrowed-texture" "native-surface"
}
flag "--preset <preset>" default="{{vars.host_native_preset}}"
'''
depends = [{ task = ":build", args = ["{{usage.preset}}"] }]
dir = "../.."
run = '''
./gradlew \
  -PmaplibreNativeCInstallDir="build/$usage_preset/install" \
  :examples:lwjgl-map:run \
  --args="$usage_render_target"
'''
