[tools]
"core:java" = "{{vars.java_version}}"

[tasks.build]
extends = "ffi:preset"
dir = "../.."
run = '''
./gradlew \
  -PmaplibreNativeCInstallDir="build/$usage_preset/install" \
  :examples:lwjgl-map:build
'''

[tasks.run]
extends = "ffi:example-run"
dir = "../.."
run = '''
./gradlew \
  -PmaplibreNativeCInstallDir="build/$usage_preset/install" \
  :examples:lwjgl-map:run \
  --args="$usage_render_target"
'''
