function(mln_import_angle)
  if(NOT MLN_FFI_ANGLE_ROOT)
    message(FATAL_ERROR "MLN_FFI_ANGLE_ROOT must be set for ANGLE builds")
  endif()

  set(MLN_FFI_ANGLE_INCLUDE_DIR "${MLN_FFI_ANGLE_ROOT}/include")
  set(MLN_FFI_ANGLE_EGL_LIBRARY "${MLN_FFI_ANGLE_ROOT}/libEGL.dylib")
  set(MLN_FFI_ANGLE_GLES_LIBRARY "${MLN_FFI_ANGLE_ROOT}/libGLESv2.dylib")

  if(NOT TARGET ANGLE::EGL)
    add_library(ANGLE::EGL SHARED IMPORTED GLOBAL)
    set_target_properties(
      ANGLE::EGL
      PROPERTIES
        IMPORTED_LOCATION "${MLN_FFI_ANGLE_EGL_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${MLN_FFI_ANGLE_INCLUDE_DIR}")
  endif()

  if(NOT TARGET ANGLE::GLESv2)
    add_library(ANGLE::GLESv2 SHARED IMPORTED GLOBAL)
    set_target_properties(
      ANGLE::GLESv2
      PROPERTIES
        IMPORTED_LOCATION "${MLN_FFI_ANGLE_GLES_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${MLN_FFI_ANGLE_INCLUDE_DIR}")
  endif()

  set(MLN_FFI_ANGLE_INCLUDE_DIR "${MLN_FFI_ANGLE_INCLUDE_DIR}" PARENT_SCOPE)
  set(MLN_FFI_ANGLE_LIBRARY_DIR "${MLN_FFI_ANGLE_ROOT}" PARENT_SCOPE)
endfunction()
