function(mln_import_egl)
  if(NOT MLN_FFI_EGL_ROOT)
    message(
      FATAL_ERROR "MLN_FFI_EGL_ROOT must be set for explicit EGL/GLES imports")
  endif()

  set(MLN_FFI_EGL_INCLUDE_ROOTS "${MLN_FFI_EGL_ROOT}")
  if(VCPKG_INSTALLED_DIR AND VCPKG_TARGET_TRIPLET)
    list(APPEND MLN_FFI_EGL_INCLUDE_ROOTS
         "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")
  endif()

  find_path(
    MLN_FFI_EGL_INCLUDE_DIR
    NAMES EGL/egl.h GLES2/gl2.h
    HINTS ${MLN_FFI_EGL_INCLUDE_ROOTS} PATH_SUFFIXES include
    REQUIRED NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
  find_library(
    MLN_FFI_EGL_LIBRARY
    NAMES EGL libEGL.so.1
    HINTS
      "${MLN_FFI_EGL_ROOT}"
      PATH_SUFFIXES
      .
      lib
      lib64
      "lib/${CMAKE_LIBRARY_ARCHITECTURE}"
      lib/aarch64-linux-gnu
      lib/x86_64-linux-gnu
    REQUIRED NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
  find_library(
    MLN_FFI_GLESV2_LIBRARY
    NAMES GLESv2 libGLESv2.so.2
    HINTS
      "${MLN_FFI_EGL_ROOT}"
      PATH_SUFFIXES
      .
      lib
      lib64
      "lib/${CMAKE_LIBRARY_ARCHITECTURE}"
      lib/aarch64-linux-gnu
      lib/x86_64-linux-gnu
    REQUIRED NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
  get_filename_component(
    MLN_FFI_EGL_LIBRARY_DIR "${MLN_FFI_EGL_LIBRARY}"
    DIRECTORY)

  add_library(MLN_FFI::EGL SHARED IMPORTED GLOBAL)
  set_target_properties(
    MLN_FFI::EGL
    PROPERTIES
      IMPORTED_CONFIGURATIONS
      Release
      IMPORTED_LOCATION
      "${MLN_FFI_EGL_LIBRARY}"
      INTERFACE_INCLUDE_DIRECTORIES
      "${MLN_FFI_EGL_INCLUDE_DIR}"
      IMPORTED_LOCATION_RELEASE
      "${MLN_FFI_EGL_LIBRARY}")

  add_library(MLN_FFI::GLESv2 SHARED IMPORTED GLOBAL)
  set_target_properties(
    MLN_FFI::GLESv2
    PROPERTIES
      IMPORTED_CONFIGURATIONS
      Release
      IMPORTED_LOCATION
      "${MLN_FFI_GLESV2_LIBRARY}"
      INTERFACE_INCLUDE_DIRECTORIES
      "${MLN_FFI_EGL_INCLUDE_DIR}"
      IMPORTED_LOCATION_RELEASE
      "${MLN_FFI_GLESV2_LIBRARY}")

  set(MLN_FFI_EGL_INCLUDE_DIR "${MLN_FFI_EGL_INCLUDE_DIR}" PARENT_SCOPE)
  set(MLN_FFI_EGL_LIBRARY_DIR "${MLN_FFI_EGL_LIBRARY_DIR}" PARENT_SCOPE)
endfunction()
