function(mln_import_egl)
  if(NOT MLN_FFI_EGL_ROOT)
    message(
      FATAL_ERROR "MLN_FFI_EGL_ROOT must be set for explicit EGL/GLES imports")
  endif()

  find_path(
    MLN_FFI_EGL_INCLUDE_DIR
    NAMES EGL/egl.h GLES2/gl2.h
    HINTS "${MLN_FFI_EGL_ROOT}" PATH_SUFFIXES include
    REQUIRED NO_DEFAULT_PATH)
  find_library(
    MLN_FFI_EGL_LIBRARY
    NAMES EGL
    HINTS "${MLN_FFI_EGL_ROOT}" PATH_SUFFIXES . lib
    REQUIRED NO_DEFAULT_PATH)
  find_library(
    MLN_FFI_GLESV2_LIBRARY
    NAMES GLESv2
    HINTS "${MLN_FFI_EGL_ROOT}" PATH_SUFFIXES . lib
    REQUIRED NO_DEFAULT_PATH)
  get_filename_component(
    MLN_FFI_EGL_LIBRARY_DIR "${MLN_FFI_EGL_LIBRARY}"
    DIRECTORY)

  add_library(MLN_FFI::EGL SHARED IMPORTED GLOBAL)
  set_target_properties(
    MLN_FFI::EGL
    PROPERTIES
      IMPORTED_LOCATION "${MLN_FFI_EGL_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES
      "${MLN_FFI_EGL_INCLUDE_DIR}")

  add_library(MLN_FFI::GLESv2 SHARED IMPORTED GLOBAL)
  set_target_properties(
    MLN_FFI::GLESv2
    PROPERTIES
      IMPORTED_LOCATION "${MLN_FFI_GLESV2_LIBRARY}"
      INTERFACE_INCLUDE_DIRECTORIES "${MLN_FFI_EGL_INCLUDE_DIR}")

  set(MLN_FFI_EGL_INCLUDE_DIR "${MLN_FFI_EGL_INCLUDE_DIR}" PARENT_SCOPE)
  set(MLN_FFI_EGL_LIBRARY_DIR "${MLN_FFI_EGL_LIBRARY_DIR}" PARENT_SCOPE)
endfunction()
