// Generated by tools/bindgen. Do not edit.
@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)

package org.maplibre.nativeffi.internal.c

import kotlinx.cinterop.*
import org.maplibre.nativeffi.internal.cinterop.*

/** The cinterop call behind each C function. */
internal actual object C {
  actual fun mln_acquired_frame_dispose(frame: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_acquired_frame_dispose(
      frame.toULong(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_acquired_frame_get_metal_texture(
    frame: Long,
    outFrame: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_acquired_frame_get_metal_texture(
      frame.toULong(),
      outFrame.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_acquired_frame_get_opengl_texture(
    frame: Long,
    outFrame: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_acquired_frame_get_opengl_texture(
      frame.toULong(),
      outFrame.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_acquired_frame_get_producer_sync(
    frame: Long,
    outSync: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_acquired_frame_get_producer_sync(
      frame.toULong(),
      outSync.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_acquired_frame_get_result(frame: Long, outResult: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_acquired_frame_get_result(
      frame.toULong(),
      outResult.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_acquired_frame_get_vulkan_texture(
    frame: Long,
    outFrame: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_acquired_frame_get_vulkan_texture(
      frame.toULong(),
      outFrame.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_acquired_frame_get_webgpu_texture(
    frame: Long,
    outFrame: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_acquired_frame_get_webgpu_texture(
      frame.toULong(),
      outFrame.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_acquired_frame_release(
    frame: Long,
    consumerCompletion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_acquired_frame_release(
      frame.toCPointer(),
      consumerCompletion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_acquired_frame_view_begin(frame: Long, outScope: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_acquired_frame_view_begin(
      frame.toULong(),
      outScope.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_acquired_frame_view_end(scope: Long) {
    org.maplibre.nativeffi.internal.cinterop.mln_acquired_frame_view_end(
      scope.toCPointer<CPointed>()
    )
  }

  actual fun mln_android_init(
    jniEnv: Long,
    jniClass: Long,
    context: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_android_init(
      jniEnv.toCPointer<CPointed>(),
      jniClass.toCPointer<CPointed>(),
      context.toCPointer<CPointed>(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_animation_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_animation_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_bound_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_bound_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_c_version(): Int = org.maplibre.nativeffi.internal.cinterop.mln_c_version().toInt()

  actual fun mln_camera_delta_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_camera_delta_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_camera_fit_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_camera_fit_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_camera_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_camera_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_camera_update_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_camera_update_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_custom_geometry_source_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_custom_geometry_source_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_custom_mvt_vector_source_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_custom_mvt_vector_source_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_event_batch_get(batch: Long, outView: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_event_batch_get(
      batch.toULong(),
      outView.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_event_batch_release(batch: Long) {
    org.maplibre.nativeffi.internal.cinterop.mln_event_batch_release(batch.toULong())
  }

  actual fun mln_frame_demand_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_frame_demand_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_free_camera_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_free_camera_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_geojson_source_data_create(
    data: Long,
    options: Long,
    outData: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_geojson_source_data_create(
      data.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      options.toCPointer(),
      outData.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_geojson_source_data_destroy(data: Long) {
    org.maplibre.nativeffi.internal.cinterop.mln_geojson_source_data_destroy(data.toULong())
  }

  actual fun mln_geojson_source_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_geojson_source_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_gpu_sync_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop.mln_gpu_sync_default().place(returned.toCPointer()!!)
  }

  actual fun mln_http_header_transform_response_set_header(
    response: Long,
    name: Long,
    nameSize: Long,
    value: Long,
    valueSize: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_http_header_transform_response_set_header(
      response.toCPointer(),
      name.toCPointer(),
      nameSize.convert(),
      value.toCPointer(),
      valueSize.convert(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_lat_lng_for_projected_meters(
    meters: Long,
    outCoordinate: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_lat_lng_for_projected_meters(
      meters.toCPointer<mln_projected_meters>()!!.pointed.readValue(),
      outCoordinate.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_log_clear_callback(outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_log_clear_callback(outDiagnostic.toCPointer())

  actual fun mln_log_set_async_severity_mask(mask: Int, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_log_set_async_severity_mask(
      mask.toUInt(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_log_set_callback(handler: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_log_set_callback(
      handler.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_logical_extent_physical_size(
    extent: Long,
    outWidth: Long,
    outHeight: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_logical_extent_physical_size(
      extent.toCPointer<mln_logical_extent>()!!.pointed.readValue(),
      outWidth.toCPointer(),
      outHeight.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_color_relief_layer(
    map: Long,
    layerId: Long,
    sourceId: Long,
    beforeLayerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_color_relief_layer(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      beforeLayerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_custom_geometry_source(
    map: Long,
    sourceId: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_custom_geometry_source(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_custom_mvt_vector_source(
    map: Long,
    sourceId: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_custom_mvt_vector_source(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_geojson_source_data(
    map: Long,
    sourceId: Long,
    data: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_geojson_source_data(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      data.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_geojson_source_url(
    map: Long,
    sourceId: Long,
    url: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_geojson_source_url(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      url.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_hillshade_layer(
    map: Long,
    layerId: Long,
    sourceId: Long,
    beforeLayerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_hillshade_layer(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      beforeLayerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_image_source_image(
    map: Long,
    sourceId: Long,
    coordinates: Long,
    coordinateCount: Long,
    image: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_image_source_image(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      coordinates.toCPointer(),
      coordinateCount.convert(),
      image.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_image_source_url(
    map: Long,
    sourceId: Long,
    coordinates: Long,
    coordinateCount: Long,
    url: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_image_source_url(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      coordinates.toCPointer(),
      coordinateCount.convert(),
      url.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_location_indicator_layer(
    map: Long,
    layerId: Long,
    beforeLayerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_location_indicator_layer(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      beforeLayerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_raster_dem_source_tiles(
    map: Long,
    sourceId: Long,
    tiles: Long,
    tileCount: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_raster_dem_source_tiles(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      tiles.toCPointer(),
      tileCount.convert(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_raster_dem_source_url(
    map: Long,
    sourceId: Long,
    url: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_raster_dem_source_url(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      url.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_raster_source_tiles(
    map: Long,
    sourceId: Long,
    tiles: Long,
    tileCount: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_raster_source_tiles(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      tiles.toCPointer(),
      tileCount.convert(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_raster_source_url(
    map: Long,
    sourceId: Long,
    url: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_raster_source_url(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      url.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_style_layer_json(
    map: Long,
    layerJson: Long,
    beforeLayerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_style_layer_json(
      map.toULong(),
      layerJson.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      beforeLayerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_style_source_json(
    map: Long,
    sourceId: Long,
    sourceJson: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_style_source_json(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      sourceJson.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_vector_source_tiles(
    map: Long,
    sourceId: Long,
    tiles: Long,
    tileCount: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_vector_source_tiles(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      tiles.toCPointer(),
      tileCount.convert(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_add_vector_source_url(
    map: Long,
    sourceId: Long,
    url: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_add_vector_source_url(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      url.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_apply_camera_delta(
    map: Long,
    delta: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_apply_camera_delta(
      map.toULong(),
      delta.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_attach_metal_borrowed_texture(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_attach_metal_borrowed_texture(
      map.toULong(),
      descriptor.toCPointer(),
      options.toCPointer(),
      outSession.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_attach_metal_owned_texture(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_attach_metal_owned_texture(
      map.toULong(),
      descriptor.toCPointer(),
      options.toCPointer(),
      outSession.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_attach_metal_surface(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_attach_metal_surface(
      map.toULong(),
      descriptor.toCPointer(),
      options.toCPointer(),
      outSession.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_attach_opengl_borrowed_texture(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_attach_opengl_borrowed_texture(
      map.toULong(),
      descriptor.toCPointer(),
      options.toCPointer(),
      outSession.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_attach_opengl_owned_texture(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_attach_opengl_owned_texture(
      map.toULong(),
      descriptor.toCPointer(),
      options.toCPointer(),
      outSession.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_attach_opengl_surface(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_attach_opengl_surface(
      map.toULong(),
      descriptor.toCPointer(),
      options.toCPointer(),
      outSession.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_attach_vulkan_borrowed_texture(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_attach_vulkan_borrowed_texture(
      map.toULong(),
      descriptor.toCPointer(),
      options.toCPointer(),
      outSession.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_attach_vulkan_owned_texture(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_attach_vulkan_owned_texture(
      map.toULong(),
      descriptor.toCPointer(),
      options.toCPointer(),
      outSession.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_attach_vulkan_surface(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_attach_vulkan_surface(
      map.toULong(),
      descriptor.toCPointer(),
      options.toCPointer(),
      outSession.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_attach_webgpu_borrowed_texture(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_attach_webgpu_borrowed_texture(
      map.toULong(),
      descriptor.toCPointer(),
      options.toCPointer(),
      outSession.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_attach_webgpu_owned_texture(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_attach_webgpu_owned_texture(
      map.toULong(),
      descriptor.toCPointer(),
      options.toCPointer(),
      outSession.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_attach_webgpu_surface(
    map: Long,
    descriptor: Long,
    options: Long,
    outSession: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_attach_webgpu_surface(
      map.toULong(),
      descriptor.toCPointer(),
      options.toCPointer(),
      outSession.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_begin_command_group(map: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_begin_command_group(
      map.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_camera_for_geometry(
    map: Long,
    geometry: Long,
    fitOptions: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_camera_for_geometry(
      map.toULong(),
      geometry.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      fitOptions.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_camera_for_lat_lng_bounds(
    map: Long,
    bounds: Long,
    fitOptions: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_camera_for_lat_lng_bounds(
      map.toULong(),
      bounds.toCPointer<mln_lat_lng_bounds>()!!.pointed.readValue(),
      fitOptions.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_camera_for_lat_lngs(
    map: Long,
    coordinates: Long,
    coordinateCount: Long,
    fitOptions: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_camera_for_lat_lngs(
      map.toULong(),
      coordinates.toCPointer(),
      coordinateCount.convert(),
      fitOptions.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_cancel_transitions(map: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_cancel_transitions(
      map.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_create_projection(map: Long, outProjection: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_create_projection(
      map.toULong(),
      outProjection.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_dispose(map: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_dispose(
      map.toULong(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_dump_debug_logs(map: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_dump_debug_logs(
      map.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_end_command_group(map: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_end_command_group(
      map.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_get_camera(map: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_get_camera(
      map.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_get_feature_state(
    map: Long,
    selector: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_get_feature_state(
      map.toULong(),
      selector.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_get_global_state(map: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_get_global_state(
      map.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_get_image_source_coordinates(
    map: Long,
    sourceId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_get_image_source_coordinates(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_get_loaded_style_json(map: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_get_loaded_style_json(
      map.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_get_snapshot(map: Long, outSnapshot: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_get_snapshot(
      map.toULong(),
      outSnapshot.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_get_style_image(
    map: Long,
    imageId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_get_style_image(
      map.toULong(),
      imageId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_get_style_layer(
    map: Long,
    layerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_get_style_layer(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_get_style_layer_filter(
    map: Long,
    layerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_get_style_layer_filter(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_get_style_layer_json(
    map: Long,
    layerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_get_style_layer_json(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_get_style_layer_property(
    map: Long,
    layerId: Long,
    propertyName: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_get_style_layer_property(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      propertyName.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_get_style_light_property(
    map: Long,
    propertyName: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_get_style_light_property(
      map.toULong(),
      propertyName.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_get_style_source(
    map: Long,
    sourceId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_get_style_source(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_get_style_transition_options(
    map: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_get_style_transition_options(
      map.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_get_style_url(map: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_get_style_url(
      map.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_invalidate_custom_geometry_source_region(
    map: Long,
    sourceId: Long,
    bounds: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_invalidate_custom_geometry_source_region(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      bounds.toCPointer<mln_lat_lng_bounds>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_invalidate_custom_geometry_source_tile(
    map: Long,
    sourceId: Long,
    tileId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_invalidate_custom_geometry_source_tile(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      tileId.toCPointer<mln_canonical_tile_id>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_invalidate_custom_mvt_vector_source_tile(
    map: Long,
    sourceId: Long,
    tileId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_invalidate_custom_mvt_vector_source_tile(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      tileId.toCPointer<mln_canonical_tile_id>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_lat_lng_bounds_for_camera(
    map: Long,
    camera: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_lat_lng_bounds_for_camera(
      map.toULong(),
      camera.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_lat_lng_bounds_for_camera_unwrapped(
    map: Long,
    camera: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_lat_lng_bounds_for_camera_unwrapped(
      map.toULong(),
      camera.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_lat_lng_for_pixel(
    map: Long,
    point: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_lat_lng_for_pixel(
      map.toULong(),
      point.toCPointer<mln_screen_point>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_lat_lng_for_pixel_unwrapped(
    map: Long,
    point: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_lat_lng_for_pixel_unwrapped(
      map.toULong(),
      point.toCPointer<mln_screen_point>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_lat_lngs_for_pixels(
    map: Long,
    points: Long,
    pointCount: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_lat_lngs_for_pixels(
      map.toULong(),
      points.toCPointer(),
      pointCount.convert(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_lat_lngs_for_pixels_unwrapped(
    map: Long,
    points: Long,
    pointCount: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_lat_lngs_for_pixels_unwrapped(
      map.toULong(),
      points.toCPointer(),
      pointCount.convert(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_list_style_layers(map: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_list_style_layers(
      map.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_list_style_sources(map: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_list_style_sources(
      map.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_meters_per_pixel_at_latitude(
    map: Long,
    latitude: Double,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_meters_per_pixel_at_latitude(
      map.toULong(),
      latitude,
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_move_style_layer(
    map: Long,
    layerId: Long,
    beforeLayerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_move_style_layer(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      beforeLayerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_map_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_map_pixel_for_lat_lng(
    map: Long,
    coordinate: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_pixel_for_lat_lng(
      map.toULong(),
      coordinate.toCPointer<mln_lat_lng>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_pixels_for_lat_lngs(
    map: Long,
    coordinates: Long,
    coordinateCount: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_pixels_for_lat_lngs(
      map.toULong(),
      coordinates.toCPointer(),
      coordinateCount.convert(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_projection_close(projection: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_projection_close(
      projection.toULong(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_projection_get_camera(
    projection: Long,
    outCamera: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_projection_get_camera(
      projection.toULong(),
      outCamera.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_projection_lat_lng_for_pixel(
    projection: Long,
    point: Long,
    outCoordinate: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_projection_lat_lng_for_pixel(
      projection.toULong(),
      point.toCPointer<mln_screen_point>()!!.pointed.readValue(),
      outCoordinate.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_projection_lat_lng_for_pixel_unwrapped(
    projection: Long,
    point: Long,
    outCoordinate: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_projection_lat_lng_for_pixel_unwrapped(
      projection.toULong(),
      point.toCPointer<mln_screen_point>()!!.pointed.readValue(),
      outCoordinate.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_projection_meters_per_pixel_at_latitude(
    projection: Long,
    latitude: Double,
    outMetersPerPixel: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_projection_meters_per_pixel_at_latitude(
      projection.toULong(),
      latitude,
      outMetersPerPixel.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_projection_pixel_for_lat_lng(
    projection: Long,
    coordinate: Long,
    outPoint: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_projection_pixel_for_lat_lng(
      projection.toULong(),
      coordinate.toCPointer<mln_lat_lng>()!!.pointed.readValue(),
      outPoint.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_projection_set_camera(
    projection: Long,
    camera: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_projection_set_camera(
      projection.toULong(),
      camera.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_projection_set_visible_coordinates(
    projection: Long,
    coordinates: Long,
    coordinateCount: Long,
    padding: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_projection_set_visible_coordinates(
      projection.toULong(),
      coordinates.toCPointer(),
      coordinateCount.convert(),
      padding.toCPointer<mln_edge_insets>()!!.pointed.readValue(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_projection_set_visible_geometry(
    projection: Long,
    geometry: Long,
    padding: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_projection_set_visible_geometry(
      projection.toULong(),
      geometry.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      padding.toCPointer<mln_edge_insets>()!!.pointed.readValue(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_release(map: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_release(
      map.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_remove_feature_state(
    map: Long,
    selector: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_remove_feature_state(
      map.toULong(),
      selector.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_remove_style_image(
    map: Long,
    imageId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_remove_style_image(
      map.toULong(),
      imageId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_remove_style_layer(
    map: Long,
    layerId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_remove_style_layer(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_remove_style_source(
    map: Long,
    sourceId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_remove_style_source(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_request_repaint(map: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_request_repaint(
      map.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_request_still_image(map: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_request_still_image(
      map.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_resize(map: Long, extent: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_resize(
      map.toULong(),
      extent.toCPointer<mln_logical_extent>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_bounds(
    map: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_bounds(
      map.toULong(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_custom_geometry_source_tile_data(
    map: Long,
    sourceId: Long,
    tileId: Long,
    data: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_custom_geometry_source_tile_data(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      tileId.toCPointer<mln_canonical_tile_id>()!!.pointed.readValue(),
      data.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_custom_mvt_vector_source_tile_data(
    map: Long,
    sourceId: Long,
    tileId: Long,
    data: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_custom_mvt_vector_source_tile_data(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      tileId.toCPointer<mln_canonical_tile_id>()!!.pointed.readValue(),
      data.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_custom_mvt_vector_source_tile_error(
    map: Long,
    sourceId: Long,
    tileId: Long,
    message: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_custom_mvt_vector_source_tile_error(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      tileId.toCPointer<mln_canonical_tile_id>()!!.pointed.readValue(),
      message.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_debug_options(
    map: Long,
    options: Int,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_debug_options(
      map.toULong(),
      options.toUInt(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_event_mask(
    map: Long,
    mask: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_event_mask(
      map.toULong(),
      mask.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_feature_state(
    map: Long,
    selector: Long,
    state: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_feature_state(
      map.toULong(),
      selector.toCPointer(),
      state.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_free_camera_options(
    map: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_free_camera_options(
      map.toULong(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_geojson_source_data(
    map: Long,
    sourceId: Long,
    data: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_geojson_source_data(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      data.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_geojson_source_synchronous_tiling(
    map: Long,
    sourceId: Long,
    enabled: Boolean,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_geojson_source_synchronous_tiling(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      enabled,
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_geojson_source_url(
    map: Long,
    sourceId: Long,
    url: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_geojson_source_url(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      url.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_global_state_property(
    map: Long,
    propertyName: Long,
    value: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_global_state_property(
      map.toULong(),
      propertyName.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      value.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_image_source_coordinates(
    map: Long,
    sourceId: Long,
    coordinates: Long,
    coordinateCount: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_image_source_coordinates(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      coordinates.toCPointer(),
      coordinateCount.convert(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_image_source_image(
    map: Long,
    sourceId: Long,
    image: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_image_source_image(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      image.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_image_source_url(
    map: Long,
    sourceId: Long,
    url: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_image_source_url(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      url.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_location_indicator_accuracy_radius(
    map: Long,
    layerId: Long,
    radius: Double,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_location_indicator_accuracy_radius(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      radius,
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_location_indicator_bearing(
    map: Long,
    layerId: Long,
    bearing: Double,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_location_indicator_bearing(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      bearing,
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_location_indicator_image_name(
    map: Long,
    layerId: Long,
    imageKind: Int,
    imageId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_location_indicator_image_name(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      imageKind.toUInt(),
      imageId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_location_indicator_location(
    map: Long,
    layerId: Long,
    coordinate: Long,
    altitude: Double,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_location_indicator_location(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      coordinate.toCPointer<mln_lat_lng>()!!.pointed.readValue(),
      altitude,
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_projection_mode(
    map: Long,
    mode: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_projection_mode(
      map.toULong(),
      mode.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_rendering_stats_view_enabled(
    map: Long,
    enabled: Boolean,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_rendering_stats_view_enabled(
      map.toULong(),
      enabled,
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_style_image(
    map: Long,
    imageId: Long,
    image: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_style_image(
      map.toULong(),
      imageId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      image.toCPointer(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_style_json(
    map: Long,
    json: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_style_json(
      map.toULong(),
      json.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_style_layer_filter(
    map: Long,
    layerId: Long,
    filter: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_style_layer_filter(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      filter.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_style_layer_max_zoom(
    map: Long,
    layerId: Long,
    maxZoom: Double,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_style_layer_max_zoom(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      maxZoom,
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_style_layer_min_zoom(
    map: Long,
    layerId: Long,
    minZoom: Double,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_style_layer_min_zoom(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      minZoom,
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_style_layer_property(
    map: Long,
    layerId: Long,
    propertyName: Long,
    value: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_style_layer_property(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      propertyName.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      value.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_style_layer_source_id(
    map: Long,
    layerId: Long,
    sourceId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_style_layer_source_id(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_style_layer_source_layer(
    map: Long,
    layerId: Long,
    sourceLayer: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_style_layer_source_layer(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      sourceLayer.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_style_layer_visibility(
    map: Long,
    layerId: Long,
    visibility: Int,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_style_layer_visibility(
      map.toULong(),
      layerId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      visibility.toUInt(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_style_light_json(
    map: Long,
    lightJson: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_style_light_json(
      map.toULong(),
      lightJson.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_style_light_property(
    map: Long,
    propertyName: Long,
    value: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_style_light_property(
      map.toULong(),
      propertyName.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      value.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_style_source_volatile(
    map: Long,
    sourceId: Long,
    isVolatile: Boolean,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_style_source_volatile(
      map.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      isVolatile,
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_style_transition_options(
    map: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_style_transition_options(
      map.toULong(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_style_url(
    map: Long,
    url: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_style_url(
      map.toULong(),
      url.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_tile_options(
    map: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_tile_options(
      map.toULong(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_set_viewport_options(
    map: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_set_viewport_options(
      map.toULong(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_tile_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_map_tile_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_map_update_camera(
    map: Long,
    update: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_map_update_camera(
      map.toULong(),
      update.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_map_viewport_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_map_viewport_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_metal_borrowed_texture_descriptor_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_metal_borrowed_texture_descriptor_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_metal_owned_texture_descriptor_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_metal_owned_texture_descriptor_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_metal_surface_descriptor_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_metal_surface_descriptor_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_network_get_status(outStatus: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_network_get_status(
      outStatus.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_network_set_status(status: Int, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_network_set_status(
      status.toUInt(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_opengl_borrowed_texture_descriptor_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_opengl_borrowed_texture_descriptor_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_opengl_owned_texture_descriptor_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_opengl_owned_texture_descriptor_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_opengl_supported_context_provider_mask(): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_opengl_supported_context_provider_mask().toInt()

  actual fun mln_opengl_surface_descriptor_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_opengl_surface_descriptor_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_plugin_get_register_function_v1(): Long =
    org.maplibre.nativeffi.internal.cinterop.mln_plugin_get_register_function_v1().toLong()

  actual fun mln_premultiplied_rgba8_image_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_premultiplied_rgba8_image_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_projected_meters_for_lat_lng(
    coordinate: Long,
    outMeters: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_projected_meters_for_lat_lng(
      coordinate.toCPointer<mln_lat_lng>()!!.pointed.readValue(),
      outMeters.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_projection_mode_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_projection_mode_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_render_frame_batch_get(batch: Long, outView: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_frame_batch_get(
      batch.toULong(),
      outView.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_frame_batch_release(batch: Long) {
    org.maplibre.nativeffi.internal.cinterop.mln_render_frame_batch_release(batch.toULong())
  }

  actual fun mln_render_session_abandon(session: Long, outResult: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_abandon(
      session.toULong(),
      outResult.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_acquire_frame(
    session: Long,
    outFrame: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_acquire_frame(
      session.toULong(),
      outFrame.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_attach_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_render_session_attach_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_render_session_barrier(session: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_barrier(
      session.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_clear_data(
    session: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_clear_data(
      session.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_create_projection(
    session: Long,
    outProjection: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_create_projection(
      session.toULong(),
      outProjection.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_destroy(session: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_destroy(
      session.toULong(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_detach(session: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_detach(
      session.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_dispose(session: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_dispose(
      session.toULong(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_drain_frame_results(
    session: Long,
    outBatch: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_drain_frame_results(
      session.toULong(),
      outBatch.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_dump_debug_logs(
    session: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_dump_debug_logs(
      session.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_get_capabilities(
    session: Long,
    outCapabilities: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_get_capabilities(
      session.toULong(),
      outCapabilities.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_get_snapshot(
    session: Long,
    outSnapshot: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_get_snapshot(
      session.toULong(),
      outSnapshot.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_query_feature_extensions(
    session: Long,
    sourceId: Long,
    feature: Long,
    extension: Long,
    extensionField: Long,
    arguments: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_query_feature_extensions(
      session.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      feature.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      extension.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      extensionField.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      arguments.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_query_rendered_features(
    session: Long,
    geometry: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_query_rendered_features(
      session.toULong(),
      geometry.toCPointer(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_query_source_features(
    session: Long,
    sourceId: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_query_source_features(
      session.toULong(),
      sourceId.toCPointer<mln_buffer_view>()!!.pointed.readValue(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_read_texture(
    session: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_read_texture(
      session.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_reduce_memory_use(
    session: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_reduce_memory_use(
      session.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_request_frame(
    session: Long,
    demand: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_request_frame(
      session.toULong(),
      demand.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_resize(
    session: Long,
    extent: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_resize(
      session.toULong(),
      extent.toCPointer<mln_logical_extent>()!!.pointed.readValue(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_service_driver_work(
    session: Long,
    maxWork: Long,
    outServiced: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_service_driver_work(
      session.toULong(),
      maxWork.convert(),
      outServiced.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_set_metal_borrowed_texture_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_set_metal_borrowed_texture_target(
      session.toULong(),
      descriptor.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_set_metal_surface_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_set_metal_surface_target(
      session.toULong(),
      descriptor.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_set_opengl_borrowed_texture_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_set_opengl_borrowed_texture_target(
      session.toULong(),
      descriptor.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_set_opengl_surface_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_set_opengl_surface_target(
      session.toULong(),
      descriptor.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_set_vulkan_borrowed_texture_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_set_vulkan_borrowed_texture_target(
      session.toULong(),
      descriptor.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_set_vulkan_surface_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_set_vulkan_surface_target(
      session.toULong(),
      descriptor.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_set_webgpu_borrowed_texture_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_set_webgpu_borrowed_texture_target(
      session.toULong(),
      descriptor.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_render_session_set_webgpu_surface_target(
    session: Long,
    descriptor: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_render_session_set_webgpu_surface_target(
      session.toULong(),
      descriptor.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_rendered_feature_query_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_rendered_feature_query_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_rendered_query_geometry_box(box: Long, returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_rendered_query_geometry_box(box.toCPointer<mln_screen_box>()!!.pointed.readValue())
      .place(returned.toCPointer()!!)
  }

  actual fun mln_rendered_query_geometry_line_string(
    points: Long,
    pointCount: Long,
    returned: Long,
  ) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_rendered_query_geometry_line_string(points.toCPointer(), pointCount.convert())
      .place(returned.toCPointer()!!)
  }

  actual fun mln_rendered_query_geometry_point(point: Long, returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_rendered_query_geometry_point(point.toCPointer<mln_screen_point>()!!.pointed.readValue())
      .place(returned.toCPointer()!!)
  }

  actual fun mln_resource_request_complete(handle: Long, response: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_resource_request_complete(
      handle.toULong(),
      response.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_resource_request_is_cancelled(
    handle: Long,
    outCancelled: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_resource_request_is_cancelled(
      handle.toULong(),
      outCancelled.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_resource_request_release(handle: Long) {
    org.maplibre.nativeffi.internal.cinterop.mln_resource_request_release(handle.toULong())
  }

  actual fun mln_resource_request_set_cancel_callback(
    handle: Long,
    handler: Long,
    outCancelled: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_resource_request_set_cancel_callback(
      handle.toULong(),
      handler.toCPointer(),
      outCancelled.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_resource_request_wait_until_retired(handle: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_resource_request_wait_until_retired(
      handle.toULong(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_resource_transform_response_set_url(
    response: Long,
    url: Long,
    urlSize: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_resource_transform_response_set_url(
      response.toCPointer(),
      url.toCPointer(),
      urlSize.convert(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_barrier(runtime: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_barrier(
      runtime.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_clear_http_header_transform(
    runtime: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_clear_http_header_transform(
      runtime.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_clear_resource_provider(
    runtime: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_clear_resource_provider(
      runtime.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_clear_resource_transform(
    runtime: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_clear_resource_transform(
      runtime.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_create(options: Long, outRuntime: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_create(
      options.toCPointer(),
      outRuntime.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_create_map(
    runtime: Long,
    options: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_create_map(
      runtime.toULong(),
      options.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_create_offline_region(
    runtime: Long,
    definition: Long,
    metadata: Long,
    metadataSize: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_create_offline_region(
      runtime.toULong(),
      definition.toCPointer(),
      metadata.toCPointer(),
      metadataSize.convert(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_delete_offline_region(
    runtime: Long,
    regionId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_delete_offline_region(
      runtime.toULong(),
      regionId,
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_dispose(runtime: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_dispose(
      runtime.toULong(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_drain_events(runtime: Long, outBatch: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_drain_events(
      runtime.toULong(),
      outBatch.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_get_event_mask(runtime: Long, outMask: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_get_event_mask(
      runtime.toULong(),
      outMask.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_get_offline_region(
    runtime: Long,
    regionId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_get_offline_region(
      runtime.toULong(),
      regionId,
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_get_offline_region_status(
    runtime: Long,
    regionId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_get_offline_region_status(
      runtime.toULong(),
      regionId,
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_invalidate_offline_region(
    runtime: Long,
    regionId: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_invalidate_offline_region(
      runtime.toULong(),
      regionId,
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_list_offline_regions(
    runtime: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_list_offline_regions(
      runtime.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_merge_offline_regions(
    runtime: Long,
    sideDatabasePath: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_merge_offline_regions(
      runtime.toULong(),
      sideDatabasePath.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_runtime_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_runtime_release(runtime: Long, completion: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_release(
      runtime.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_run_ambient_cache_operation(
    runtime: Long,
    operation: Int,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_run_ambient_cache_operation(
      runtime.toULong(),
      operation.toUInt(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_set_event_mask(runtime: Long, mask: Long, outDiagnostic: Long): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_set_event_mask(
      runtime.toULong(),
      mask.toULong(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_set_http_header_transform(
    runtime: Long,
    transform: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_set_http_header_transform(
      runtime.toULong(),
      transform.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_set_maximum_ambient_cache_size(
    runtime: Long,
    size: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_set_maximum_ambient_cache_size(
      runtime.toULong(),
      size.toULong(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_set_offline_region_download_state(
    runtime: Long,
    regionId: Long,
    state: Int,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_set_offline_region_download_state(
      runtime.toULong(),
      regionId,
      state.toUInt(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_set_offline_region_observed(
    runtime: Long,
    regionId: Long,
    observed: Boolean,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_set_offline_region_observed(
      runtime.toULong(),
      regionId,
      observed,
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_set_resource_provider(
    runtime: Long,
    provider: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_set_resource_provider(
      runtime.toULong(),
      provider.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_set_resource_transform(
    runtime: Long,
    transform: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_set_resource_transform(
      runtime.toULong(),
      transform.toCPointer(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_runtime_update_offline_region_metadata(
    runtime: Long,
    regionId: Long,
    metadata: Long,
    metadataSize: Long,
    completion: Long,
    outDiagnostic: Long,
  ): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_runtime_update_offline_region_metadata(
      runtime.toULong(),
      regionId,
      metadata.toCPointer(),
      metadataSize.convert(),
      completion.toCPointer(),
      outDiagnostic.toCPointer(),
    )

  actual fun mln_source_feature_query_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_source_feature_query_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_style_image_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_style_image_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_style_tile_source_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_style_tile_source_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_style_transition_options_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_style_transition_options_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_supported_render_backend_mask(): Int =
    org.maplibre.nativeffi.internal.cinterop.mln_supported_render_backend_mask().toInt()

  actual fun mln_vulkan_borrowed_texture_descriptor_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_vulkan_borrowed_texture_descriptor_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_vulkan_owned_texture_descriptor_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_vulkan_owned_texture_descriptor_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_vulkan_surface_descriptor_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_vulkan_surface_descriptor_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_webgpu_borrowed_texture_descriptor_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_webgpu_borrowed_texture_descriptor_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_webgpu_owned_texture_descriptor_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_webgpu_owned_texture_descriptor_default()
      .place(returned.toCPointer()!!)
  }

  actual fun mln_webgpu_surface_descriptor_default(returned: Long) {
    org.maplibre.nativeffi.internal.cinterop
      .mln_webgpu_surface_descriptor_default()
      .place(returned.toCPointer()!!)
  }
}
