// Generated by tools/bindgen. Do not edit.
@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)

package org.maplibre.nativeffi.internal.c

import kotlinx.cinterop.*
import org.maplibre.nativeffi.internal.cinterop.*

internal actual object UpcallStubs {
  actual val completion: Long =
    staticCFunction { userData: COpaquePointer?, result: CPointer<mln_completion_result>? ->
        Upcalls.completion(userData.toLong(), result.toLong())
      }
      .toLong()
  actual val completionRelease: Long =
    staticCFunction { userData: COpaquePointer? -> Upcalls.completionRelease(userData.toLong()) }
      .toLong()
  actual val releaseRoot: Long =
    staticCFunction { userData: COpaquePointer? -> Upcalls.releaseRoot(userData.toLong()) }.toLong()
  actual val logCallback: Long =
    staticCFunction {
        userData: COpaquePointer?,
        severity: UInt,
        event: UInt,
        code: Long,
        message: CPointer<ByteVar>? ->
        Upcalls.logCallback(
            userData.toLong(),
            severity.toInt(),
            event.toInt(),
            code,
            message.toLong(),
          )
          .toUInt()
      }
      .toLong()
  actual val resourceRequestCancelCallback: Long =
    staticCFunction { userData: COpaquePointer? ->
        Upcalls.resourceRequestCancelCallback(userData.toLong())
      }
      .toLong()
  actual val customGeometrySourceOptionsFetchTile: Long =
    staticCFunction { userData: COpaquePointer?, tileId: CValue<mln_canonical_tile_id> ->
        tileId.useContents {
          val tileIdAddress = ptr.toLong()
          Upcalls.customGeometrySourceOptionsFetchTile(userData.toLong(), tileIdAddress)
        }
      }
      .toLong()
  actual val customGeometrySourceOptionsCancelTile: Long =
    staticCFunction { userData: COpaquePointer?, tileId: CValue<mln_canonical_tile_id> ->
        tileId.useContents {
          val tileIdAddress = ptr.toLong()
          Upcalls.customGeometrySourceOptionsCancelTile(userData.toLong(), tileIdAddress)
        }
      }
      .toLong()
  actual val customMvtVectorSourceOptionsFetchTile: Long =
    staticCFunction { userData: COpaquePointer?, tileId: CValue<mln_canonical_tile_id> ->
        tileId.useContents {
          val tileIdAddress = ptr.toLong()
          Upcalls.customMvtVectorSourceOptionsFetchTile(userData.toLong(), tileIdAddress)
        }
      }
      .toLong()
  actual val customMvtVectorSourceOptionsCancelTile: Long =
    staticCFunction { userData: COpaquePointer?, tileId: CValue<mln_canonical_tile_id> ->
        tileId.useContents {
          val tileIdAddress = ptr.toLong()
          Upcalls.customMvtVectorSourceOptionsCancelTile(userData.toLong(), tileIdAddress)
        }
      }
      .toLong()
  actual val httpHeaderTransformCallback: Long =
    staticCFunction {
        userData: COpaquePointer?,
        kind: UInt,
        url: CPointer<ByteVar>?,
        outResponse: CPointer<mln_http_header_transform_response>? ->
        Upcalls.httpHeaderTransformCallback(
          userData.toLong(),
          kind.toInt(),
          url.toLong(),
          outResponse.toLong(),
        )
      }
      .toLong()
  actual val resourceProviderCallback: Long =
    staticCFunction {
        userData: COpaquePointer?,
        request: CPointer<mln_resource_request>?,
        handle: ULong ->
        Upcalls.resourceProviderCallback(userData.toLong(), request.toLong(), handle.toLong())
          .toUInt()
      }
      .toLong()
  actual val resourceTransformCallback: Long =
    staticCFunction {
        userData: COpaquePointer?,
        kind: UInt,
        url: CPointer<ByteVar>?,
        outResponse: CPointer<mln_resource_transform_response>? ->
        Upcalls.resourceTransformCallback(
          userData.toLong(),
          kind.toInt(),
          url.toLong(),
          outResponse.toLong(),
        )
      }
      .toLong()
  actual val wakeCallback: Long =
    staticCFunction { userData: COpaquePointer? -> Upcalls.wakeCallback(userData.toLong()) }
      .toLong()
}
