[tasks.build]
depends = ["//:ensure-native-library"]
run = "../../gradlew :bindings:kotlin-native:assemble"

[tasks.test]
depends = ["//:ensure-native-library"]
run = "../../gradlew :bindings:kotlin-native:check"
