// Generated by `mise run //bindings/typescript:generate`. Do not edit.

/**
 * The ABI schema fingerprint this binding was generated from.
 *
 * A runtime payload reports its own. The facade refuses to call one that
 * disagrees, because the call ABI indexes entrypoints rather than naming them.
 */
export const ABI_FINGERPRINT =
  "32384e560f0df23bc5cd4ef2fc9087a266560161d9c32d456edea1ceaf08624a";

/**
 * Digest of the public header bytes the generation ran against.
 *
 * The addon build refuses to link a native artifact whose headers differ,
 * because a checked-in dispatch table describes one exact library ABI.
 */
export const ABI_HEADER_DIGEST =
  "341181abcd4c3829124217e39ace6a194b2a69259074900d93bdf81cfd1ccd94";
