// Generated by `mise run //bindings/typescript:generate`. Do not edit.

/**
 * The ABI schema fingerprint this binding was generated from.
 *
 * A runtime payload reports its own. The facade refuses to call one that
 * disagrees, because the call ABI indexes entrypoints rather than naming them.
 */
export const ABI_FINGERPRINT =
  "4d25bf81864e53e286a07e4b59bb18247cff5fd1a8123db57bf200a3de2512c8";

/**
 * Digest of the public header bytes the generation ran against.
 *
 * The addon build refuses to link a native artifact whose headers differ,
 * because a checked-in dispatch table describes one exact library ABI.
 */
export const ABI_HEADER_DIGEST =
  "0d6dad96a46b655a6851e9fcf506b7c3ebea46b6286566f68914bf90b8713f02";
