// Generated by `mise run //bindings/typescript:generate`. Do not edit.

/**
 * The ABI schema fingerprint this binding was generated from.
 *
 * A runtime payload reports its own. The facade refuses to call one that
 * disagrees, because the call ABI indexes entrypoints rather than naming them.
 */
export const ABI_FINGERPRINT =
  "1caa4c67b70a8ff4b0b9552b133cc9b377ee8534934c3fe6313150e718eb9fb5";

/**
 * Digest of the public header bytes the generation ran against.
 *
 * The addon build refuses to link a native artifact whose headers differ,
 * because a checked-in dispatch table describes one exact library ABI.
 */
export const ABI_HEADER_DIGEST =
  "341181abcd4c3829124217e39ace6a194b2a69259074900d93bdf81cfd1ccd94";
