"""Generate Go APIs from the shared C ownership and value model."""

import re

from tools.bindgen import docs
from tools.bindgen.compiler import compile_api
from tools.bindgen.model import ModelError
from tools.bindgen.semantic import view_support

GO_KEYWORDS = {
    "break",
    "default",
    "func",
    "interface",
    "select",
    "case",
    "defer",
    "go",
    "map",
    "struct",
    "chan",
    "else",
    "goto",
    "package",
    "switch",
    "const",
    "fallthrough",
    "if",
    "range",
    "type",
    "continue",
    "for",
    "import",
    "return",
    "var",
}


def native_identifier(value: str) -> str:
    return "_" + value if value in GO_KEYWORDS else value


def name(value: str) -> str:
    return "".join(word[:1].upper() + word[1:] for word in value.split("_"))


def doc(bound, native: str, declared: str | None, *, operation: bool = False) -> str:
    """The Go doc comment of a declaration, or empty when it has none."""
    return docs.go_comment(bound.doc(native), declared, operation=operation)


def documented_operation(bound, native: str, source: str) -> str:
    """An operation's source with its comment before its function."""
    match = re.search(r"^func (?:\([^)]*\) )?(\w+)", source, re.MULTILINE)
    if not match:
        return source
    comment = doc(bound, native, match[1], operation=True)
    return source[: match.start()] + comment + source[match.start() :]


def native_call(function, *arguments, diagnostic="diagnostic"):
    """Calls a C function, passing diagnostic last when it takes one."""
    if function.diagnostic:
        arguments = (*arguments, diagnostic)
    return f"C.{function.name}({', '.join(arguments)})"


def lower(api):
    from .go_callbacks import sources
    from .go_operations import lower as lower_operations

    bound = compile_api(api)
    values, operations, generated, unsupported = lower_operations(bound)
    for value in bound.public_values.values():
        if value.kind == "enum" or value.default:
            values.require(value, input=value.kind == "record")
    owners = []
    used_support = set()
    for native, handle in sorted(bound.handles.items()):
        if handle.dispose in bound.source.runtime_exports:
            continue
        owner = values.owner(native)
        disposer = handle.dispose or handle.release
        declaration = next(
            (p.function for p in bound.operations if p.name == disposer), None
        )
        if not handle.dispose and (
            not declaration
            or declaration.return_type.canonical != "void"
            or len(declaration.parameters) != 1
        ):
            raise ModelError(
                [f"{native}: automatic ownership requires an unconditional disposer"]
            )
        dispose = native_call(
            bound.source.functions_by_name[disposer],
            f"C.{native}(raw)",
            diagnostic="nil",
        )
        owners.append(
            doc(bound, native, owner)
            + f'type {owner} struct {{ *bindingOwner }}\nfunc adopt{owner}(raw uint64, parent any) *{owner} {{ owner := &{owner}{{bindingAdopt(raw,parent,"{owner}",func(raw uint64){{ {dispose} }})}}; return owner }}\n'
            f"// owner returns the handle's owner state, or nil for a nil handle.\nfunc (handle *{owner}) owner() *bindingOwner {{ if handle == nil {{ return nil }}; return handle.bindingOwner }}"
        )
        used_support.add(disposer)
    go, header, c = [], [], []
    for record in list(values.records.values()):
        if record.registration:
            a, b, d = sources(values, record)
            go.append(a)
            header.append(b)
            c.append(d)
        if record.default:
            used_support.add(record.default)
    for plan in bound.operations:
        if plan.role == "support" and plan.name in used_support:
            generated.append(plan.name)
            unsupported.pop(plan.name, None)
    return (
        values.sources() + "\n" + "\n".join(owners + operations + go),
        header,
        c,
        generated,
        unsupported,
    )


def coverage(api):
    bound = compile_api(api)
    _, _, _, generated, unsupported = lower(bound)
    return {
        "generated": sorted(generated),
        "support": view_support(bound, generated),
        "unsupported": unsupported,
    }


def generate(api):
    bound = compile_api(api)
    chunks, header, c, _, _ = lower(bound)
    names = "\n".join(
        f"enum {{ binding_operation_{p.name} = {index} }};"
        for index, p in enumerate(bound.operations, 1)
    )
    source = (
        """// Code generated by tools/bindgen; DO NOT EDIT.
package maplibre
/*
#cgo pkg-config: maplibre-native-c
#include <stdlib.h>
#include <stdbool.h>
#include "maplibre_native_c/plugin.h"
#include "generated_callbacks.h"
*/
import "C"
"""
        + "\n".join(
            f'import "{module}"'
            for module in ("unsafe", "runtime", "runtime/cgo", "weak")
            if module.rsplit("/", 1)[-1] + "." in chunks
        )
        + "\n"
        + chunks
    )
    declarations = (
        """// Code generated by tools/bindgen; DO NOT EDIT.
#ifndef MLN_GO_GENERATED_CALLBACKS_H
#define MLN_GO_GENERATED_CALLBACKS_H
#include "maplibre_native_c.h"
#include "binding_callback.h"
void binding_release(void*);
void binding_release_forbid(void*);
"""
        + "\n".join(header)
        + "\n"
        + names
        + "\n#endif\n"
    )
    callbacks = """// Code generated by tools/bindgen; DO NOT EDIT.
#include "generated_callbacks.h"
extern void mlnGoCallbackRelease(void*);
extern uint64_t mlnGoCallbackOwner(void*);
void binding_release(void *p) { mlnGoCallbackRelease(p); }
void binding_release_forbid(void *p) {
    binding_policy policy = {0};
    binding_policy_enter(&policy);
    mlnGoCallbackRelease(p);
    binding_policy_leave(&policy);
}
""" + "\n".join(c)
    return {
        "generated_api.go": source,
        "generated_callbacks.h": declarations,
        "generated_callbacks.c": callbacks,
    }
