"""Emit the C declarations of the Kotlin binding and their three platform shims.

Common code calls `C`, an expect object with one function per C function it
uses. Every parameter is a primitive carrier (see kotlin_abi), so each shim is
a uniform list of declarations:

- JVM: one FFM downcall handle per function, and record layouts only for the
  records C passes or returns by value.
- Kotlin/Native: one call into the cinterop import of the headers.
- Android: one `external` function per C function, registered by the JNI glue
  this module writes, which casts each carrier to its C type.

`UpcallStubs` holds the C function pointer behind each `Upcalls` method.
"""

from __future__ import annotations

from dataclasses import dataclass

from ..model import CType, Function
from ..protocol import COMPLETION, COMPLETION_RESULT, DIAGNOSTIC
from .kotlin_abi import (
    POINTER,
    Abi,
    Array,
    LayoutError,
    Primitive,
    Record,
    width_expression,
)
from .kotlin_values import identifier

PACKAGE = "org.maplibre.nativeffi.internal.c"
CINTEROP = "org.maplibre.nativeffi.internal.cinterop"
HEADER = "// Generated by tools/bindgen. Do not edit.\n"

FFM = {
    "bool": "JAVA_BOOLEAN",
    "i8": "JAVA_BYTE",
    "u8": "JAVA_BYTE",
    "i16": "JAVA_SHORT",
    "u16": "JAVA_SHORT",
    "i32": "JAVA_INT",
    "u32": "JAVA_INT",
    "i64": "JAVA_LONG",
    "u64": "JAVA_LONG",
    "size": "JAVA_LONG",
    "ssize": "JAVA_LONG",
    "f32": "JAVA_FLOAT",
    "f64": "JAVA_DOUBLE",
    "ptr": "JAVA_LONG",
}

JNI_LETTER = {
    "Boolean": "Z",
    "Byte": "B",
    "Short": "S",
    "Int": "I",
    "Long": "J",
    "Float": "F",
    "Double": "D",
    "Unit": "V",
}

JNI_TYPE = {
    "Boolean": "jboolean",
    "Byte": "jbyte",
    "Short": "jshort",
    "Int": "jint",
    "Long": "jlong",
    "Float": "jfloat",
    "Double": "jdouble",
    "Unit": "void",
}

JVALUE = {
    "Boolean": "z",
    "Byte": "b",
    "Short": "s",
    "Int": "i",
    "Long": "j",
    "Float": "f",
    "Double": "d",
}

# Kotlin/Native: from a carrier to the cinterop parameter, and back.
TO_CINTEROP = {
    "bool": "",
    "i8": "",
    "u8": ".toUByte()",
    "i16": "",
    "u16": ".toUShort()",
    "i32": "",
    "u32": ".toUInt()",
    "i64": "",
    "u64": ".toULong()",
    "size": ".convert()",
    "ssize": ".convert()",
    "f32": "",
    "f64": "",
    "ptr": ".toCPointer()",
}

FROM_CINTEROP = {
    "bool": "",
    "i8": "",
    "u8": ".toByte()",
    "i16": "",
    "u16": ".toShort()",
    "i32": "",
    "u32": ".toInt()",
    "i64": "",
    "u64": ".toLong()",
    "size": ".toLong()",
    "ssize": ".toLong()",
    "f32": "",
    "f64": "",
    "ptr": ".toLong()",
}

CINTEROP_TYPE = {
    "bool": "Boolean",
    "i8": "Byte",
    "u8": "UByte",
    "i16": "Short",
    "u16": "UShort",
    "i32": "Int",
    "u32": "UInt",
    "i64": "Long",
    "u64": "ULong",
    "size": "size_t",
    "ssize": "ssize_t",
    "f32": "Float",
    "f64": "Double",
}


@dataclass(frozen=True)
class Parameter:
    name: str
    c_name: str
    ctype: CType
    kind: object
    # The trailing address a record result that C returns by value goes to.
    returned: bool = False

    @property
    def carrier(self):
        return "Long" if isinstance(self.kind, Record) else self.kind.carrier


@dataclass(frozen=True)
class Signature:
    function: str
    parameters: tuple[Parameter, ...]
    result: object
    result_ctype: CType

    @property
    def carrier(self):
        if self.result is None or isinstance(self.result, Record):
            return "Unit"
        return self.result.carrier


DIAGNOSTIC_POINTER = CType(
    "pointer",
    f"{DIAGNOSTIC} *",
    f"struct {DIAGNOSTIC} *",
    pointee=CType("record", DIAGNOSTIC, f"struct {DIAGNOSTIC}", DIAGNOSTIC),
)


class NativeShims:
    def __init__(self, bound, functions: dict[str, Function], sites):
        self.bound = bound
        self.abi = Abi(bound.source)
        self.sites = list(sites)
        self.signatures = [self.signature(f) for _, f in sorted(functions.items())]
        self.layouts = {}

    def classify(self, ctype):
        if ctype.kind == "void" or ctype.spelling == "void":
            return None
        return self.abi.classify(ctype)

    def signature(self, function: Function) -> Signature:
        parameters = [
            Parameter(identifier(p.name), p.name, p.type, self.classify(p.type))
            for p in function.parameters
        ]
        if function.diagnostic:
            parameters.append(
                Parameter(
                    "outDiagnostic", "out_diagnostic", DIAGNOSTIC_POINTER, POINTER
                )
            )
        result = self.classify(function.return_type)
        if isinstance(result, Record):
            parameters.append(
                Parameter(
                    "returned",
                    "returned",
                    CType("pointer", function.return_type.spelling + " *", ""),
                    POINTER,
                    returned=True,
                )
            )
        for parameter in parameters:
            if isinstance(parameter.kind, Array):
                raise LayoutError(f"{function.name}: array parameters have no carrier")
        return Signature(function.name, tuple(parameters), result, function.return_type)

    def kotlin_parameters(self, signature):
        return ", ".join(f"{p.name}: {p.carrier}" for p in signature.parameters)

    # Common.

    def common(self):
        lines = [
            f"  fun {s.function}({self.kotlin_parameters(s)}): {s.carrier}"
            for s in self.signatures
        ]
        return (
            HEADER
            + f"package {PACKAGE}\n\n"
            + "/**\n"
            + " * The C functions the binding calls, over primitive carriers: an address or a 64-bit\n"
            + " * integer is a Long, and a record C takes by value crosses as the address of a copy. A record\n"
            + " * C returns by value is written to the trailing `returned` address.\n"
            + " */\n"
            + "internal expect object C {\n"
            + "\n".join(lines)
            + "\n}\n"
        )

    def runtime_layouts(self):
        """Offsets of the records the handwritten completion and status runtime reads."""
        objects = []
        for record, public in (
            (COMPLETION, "CompletionLayout"),
            (COMPLETION_RESULT, "CompletionResultLayout"),
            (DIAGNOSTIC, "DiagnosticLayout"),
        ):
            if record not in self.bound.source.records_by_name:
                continue
            narrow = self.abi.record_named(record, 32)
            wide = self.abi.record_named(record, 64)
            members = [
                f"  val SIZEOF: Int = {width_expression((narrow.size, wide.size))}"
            ]
            for field, offset in wide.offsets.items():
                members.append(
                    f"  val {field.upper()}: Int = {width_expression((narrow.offsets[field], offset))}"
                )
            objects.append(
                f"internal object {public} {{\n" + "\n".join(members) + "\n}"
            )
        return (
            HEADER
            + f"package {PACKAGE}\n\n"
            + "import org.maplibre.nativeffi.internal.memory.w\n\n"
            + "\n\n".join(objects)
            + "\n"
        )

    # JVM.

    def ffm_layout(self, kind):
        """The FFM layout expression of a C type inside a record."""
        if isinstance(kind, Primitive):
            return "ADDRESS" if kind is POINTER else FFM[kind.name]
        if isinstance(kind, Array):
            return f"Ffm.array({kind.length}, {self.ffm_layout(kind.element)})"
        self.record_layout(kind)
        return kind.name

    def record_layout(self, kind):
        # Nested layouts come first: an object initializes its properties in order.
        if kind.name in self.layouts:
            return
        layout = self.abi.record(kind, 64)
        members, cursor = [], 0
        for field, child in kind.fields:
            offset = layout.offsets[field]
            if not kind.union and offset > cursor:
                members.append(f"Ffm.pad({offset - cursor})")
            members.append(f'{self.ffm_layout(child)}.withName("{field}")')
            size, _align = self.abi.size_align(child, 64)
            cursor = max(cursor, offset + size) if not kind.union else max(cursor, size)
        if layout.size > cursor:
            members.append(f"Ffm.pad({layout.size - cursor})")
        builder = "Ffm.union" if kind.union else "Ffm.struct"
        self.layouts[kind.name] = (
            f"internal val {kind.name}: GroupLayout = {builder}({', '.join(members)})"
        )

    def ffm_argument(self, kind):
        if isinstance(kind, Record):
            self.record_layout(kind)
            return kind.name
        return FFM[kind.name]

    def jvm(self):
        handles, functions = [], []
        for s in self.signatures:
            parameters = [p for p in s.parameters if not p.returned]
            layouts = [self.ffm_argument(p.kind) for p in parameters]
            result = "null" if s.result is None else self.ffm_argument(s.result)
            handles.append(
                f'  private val {s.function} = Ffm.downcall("{s.function}", {", ".join([result, *layouts])})'
            )
            arguments = [
                f"Ffm.value({p.name}, {p.kind.name})"
                if isinstance(p.kind, Record)
                else p.name
                for p in parameters
            ]
            if isinstance(s.result, Record):
                arguments.insert(0, f"Ffm.into(returned, {s.result.name})")
                call = (
                    f"{s.function}.invokeExact({', '.join(arguments)}) as MemorySegment"
                )
                functions.append(
                    f"  actual fun {s.function}({self.kotlin_parameters(s)}) {{ {call} }}"
                )
            elif s.result is None:
                functions.append(
                    f"  actual fun {s.function}({self.kotlin_parameters(s)}) {{ {s.function}.invoke({', '.join(arguments)}) }}"
                )
            else:
                functions.append(
                    f"  actual fun {s.function}({self.kotlin_parameters(s)}): {s.carrier} = "
                    f"{s.function}.invokeExact({', '.join(arguments)}) as {s.carrier}"
                )
        stubs = []
        for site in self.sites:
            arguments = []
            for _local, ctype, _carrier in site.parameters:
                arguments.append(self.ffm_argument(self.abi.classify(ctype)))
            result = self.classify(site.result)
            stubs.append(
                f'  actual val {site.name}: Long = Ffm.upcall("{site.name}", '
                + ", ".join(
                    [
                        "null" if result is None else self.ffm_argument(result),
                        *arguments,
                    ]
                )
                + ")"
            )
        imports = (
            "import java.lang.foreign.GroupLayout\n"
            "import java.lang.foreign.MemorySegment\n"
            "import java.lang.foreign.ValueLayout.*\n\n"
        )
        layouts = [self.layouts[name] for name in self.layouts]
        return {
            "C.kt": HEADER
            + f"package {PACKAGE}\n\n"
            + imports
            + "/** The FFM downcall behind each C function. */\n"
            + "internal actual object C {\n"
            + "\n".join(handles)
            + "\n\n"
            + "\n".join(functions)
            + "\n}\n\n"
            + "// The layout of each record that C passes or returns by value, nested ones first.\n"
            + "\n".join(layouts)
            + "\n",
            "UpcallStubs.kt": HEADER
            + f"package {PACKAGE}\n\n"
            + "import java.lang.foreign.ValueLayout.*\n\n"
            + "internal actual object UpcallStubs {\n"
            + "\n".join(stubs)
            + "\n}\n",
        }

    # Kotlin/Native.

    def opaque(self, ctype):
        """Whether a pointer type points to void, which cinterop imports as COpaquePointer."""
        pointee = ctype.pointee
        if pointee is None and ctype.kind == "typedef":
            typedef = self.bound.source.typedefs_by_name.get(ctype.declaration)
            pointee = typedef.type.pointee if typedef else None
        return pointee is not None and (
            pointee.kind == "void" or pointee.spelling.removeprefix("const ") == "void"
        )

    def cinterop_type(self, ctype):
        kind = self.abi.classify(ctype)
        if isinstance(kind, Record):
            return f"CValue<{kind.name}>"
        if kind is POINTER:
            pointee = ctype.pointee
            if pointee is None and ctype.kind == "typedef":
                pointee = self.bound.source.typedefs_by_name[
                    ctype.declaration
                ].type.pointee
            if (
                pointee is None
                or pointee.kind == "void"
                or pointee.spelling.endswith("void")
            ):
                return "COpaquePointer?"
            if pointee.kind in {
                "char_s",
                "char_u",
                "schar",
                "uchar",
            } or pointee.spelling.removeprefix("const ") in {
                "char",
                "unsigned char",
                "signed char",
            }:
                return "CPointer<ByteVar>?"
            target = self.abi.classify(pointee)
            if isinstance(target, Record):
                return f"CPointer<{target.name}>?"
            raise ValueError(f"{ctype.spelling}: no cinterop pointer rule")
        return CINTEROP_TYPE[kind.name]

    def native(self):
        functions = []
        for s in self.signatures:
            parameters = [p for p in s.parameters if not p.returned]
            arguments = []
            for p in parameters:
                if isinstance(p.kind, Record):
                    arguments.append(
                        f"{p.name}.toCPointer<{p.kind.name}>()!!.pointed.readValue()"
                    )
                elif p.kind is POINTER and self.opaque(p.ctype):
                    # Kotlin cannot infer the pointee of an opaque pointer parameter.
                    arguments.append(f"{p.name}.toCPointer<CPointed>()")
                else:
                    arguments.append(p.name + TO_CINTEROP[p.kind.name])
            call = f"{CINTEROP}.{s.function}({', '.join(arguments)})"
            head = f"  actual fun {s.function}({self.kotlin_parameters(s)})"
            if isinstance(s.result, Record):
                functions.append(f"{head} {{ {call}.place(returned.toCPointer()!!) }}")
            elif s.result is None:
                functions.append(f"{head} {{ {call} }}")
            else:
                functions.append(
                    f"{head}: {s.carrier} = {call}{FROM_CINTEROP[s.result.name]}"
                )
        stubs = []
        for site in self.sites:
            parameters, arguments, records = [], [], []
            for local, ctype, _carrier in site.parameters:
                parameters.append(f"{local}: {self.cinterop_type(ctype)}")
                kind = self.abi.classify(ctype)
                if isinstance(kind, Record):
                    records.append(local)
                    arguments.append(f"{local}Address")
                else:
                    arguments.append(local + FROM_CINTEROP[kind.name])
            call = f"Upcalls.{site.name}({', '.join(arguments)})"
            result = self.classify(site.result)
            if result is not None:
                call += TO_CINTEROP[result.name]
            for local in reversed(records):
                call = f"{local}.useContents {{ val {local}Address = ptr.toLong(); {call} }}"
            stubs.append(
                f"  actual val {site.name}: Long = staticCFunction {{ {', '.join(parameters)} -> {call} }}.toLong()"
            )
        return {
            "C.kt": HEADER
            + "@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)\n\n"
            + f"package {PACKAGE}\n\n"
            + "import kotlinx.cinterop.*\n"
            + f"import {CINTEROP}.*\n\n"
            + "/** The cinterop call behind each C function. */\n"
            + "internal actual object C {\n"
            + "\n".join(functions)
            + "\n}\n",
            "UpcallStubs.kt": HEADER
            + "@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)\n\n"
            + f"package {PACKAGE}\n\n"
            + "import kotlinx.cinterop.*\n"
            + "import platform.posix.size_t\n"
            + f"import {CINTEROP}.*\n\n"
            + "internal actual object UpcallStubs {\n"
            + "\n".join(stubs)
            + "\n}\n",
        }

    # Android.

    def android(self):
        externals = [
            f"  @JvmStatic actual external fun {s.function}({self.kotlin_parameters(s)}): {s.carrier}"
            for s in self.signatures
        ]
        stubs = [
            f"  actual val {site.name}: Long = Jni.upcallStub({index})"
            for index, site in enumerate(self.sites)
        ]
        kotlin = (
            HEADER
            + f"package {PACKAGE}\n\n"
            + "/** The JNI native behind each C function, registered by `src/androidMain/jni`. */\n"
            + "internal actual object C {\n"
            + "  init {\n    Jni.load()\n  }\n\n"
            + "\n".join(externals)
            + "\n}\n"
        )
        upcall_stubs = (
            HEADER
            + f"package {PACKAGE}\n\n"
            + "internal actual object UpcallStubs {\n"
            + "\n".join(stubs)
            + "\n}\n"
        )
        return {"C.kt": kotlin, "UpcallStubs.kt": upcall_stubs}, self.jni()

    def c_argument(self, parameter):
        kind, ctype = parameter.kind, parameter.ctype
        spelling = ctype.spelling
        if isinstance(kind, Record):
            return (
                f"MLN_JNI_RECORD({ctype.declaration or spelling}, {parameter.c_name})"
            )
        if kind is POINTER:
            return f"MLN_JNI_POINTER({spelling}, {parameter.c_name})"
        return f"({spelling}){parameter.c_name}"

    def jni(self):
        functions, methods = [], []
        for s in self.signatures:
            parameters = ["JNIEnv* env", "jclass type"] + [
                f"{JNI_TYPE[p.carrier]} {p.c_name}" for p in s.parameters
            ]
            arguments = [self.c_argument(p) for p in s.parameters if not p.returned]
            call = f"{s.function}({', '.join(arguments)})"
            if isinstance(s.result, Record):
                body = (
                    f"*MLN_JNI_POINTER({s.result_ctype.spelling}*, returned) = {call};"
                )
            elif s.result is None:
                body = f"{call};"
            elif s.result is POINTER:
                body = f"return MLN_JNI_ADDRESS({call});"
            else:
                body = f"return ({JNI_TYPE[s.carrier]}){call};"
            functions.append(
                f"static {JNI_TYPE[s.carrier]} {s.function}_jni({', '.join(parameters)}) {{\n  {body}\n}}"
            )
            descriptor = (
                "("
                + "".join(JNI_LETTER[p.carrier] for p in s.parameters)
                + ")"
                + JNI_LETTER[s.carrier]
            )
            methods.append(
                f'  {{"{s.function}", "{descriptor}", (void*){s.function}_jni}},'
            )
        upcalls, entries, stubs = [], [], []
        for index, site in enumerate(self.sites):
            parameters, values = [], []
            for local, ctype, carrier in site.parameters:
                c_name = local
                parameters.append(self.c_declaration(ctype, c_name))
                kind = self.abi.classify(ctype)
                if isinstance(kind, Record):
                    values.append(f"{{.j = MLN_JNI_ADDRESS(&{c_name})}}")
                elif kind is POINTER:
                    values.append(f"{{.j = MLN_JNI_ADDRESS({c_name})}}")
                else:
                    values.append(
                        f"{{.{JVALUE[carrier]} = ({JNI_TYPE[carrier]}){c_name}}}"
                    )
            result = self.classify(site.result)
            arguments = (
                f"jvalue arguments[] = {{{', '.join(values)}}};" if values else ""
            )
            array = "arguments" if values else "NULL"
            upcall = f"&mln_jni_upcalls[{index}]"
            if result is None:
                body = f"mln_jni_upcall_void({upcall}, {array});"
                c_result = "void"
            else:
                width = "long" if site.result_carrier == "Long" else "int"
                body = (
                    f"{JNI_TYPE[site.result_carrier]} result = {site.failure};\n"
                    f"  mln_jni_upcall_{width}({upcall}, {array}, &result);\n"
                    f"  return ({site.result.spelling})result;"
                )
                c_result = site.result.spelling
            upcalls.append(
                f"static {c_result} mln_jni_{site.name}({', '.join(parameters) or 'void'}) {{\n"
                + (f"  {arguments}\n" if arguments else "")
                + f"  {body}\n}}"
            )
            descriptor = (
                "("
                + "".join(JNI_LETTER[carrier] for _l, _c, carrier in site.parameters)
                + ")"
                + JNI_LETTER[site.result_carrier]
            )
            entries.append(f'  {{"{site.name}", "{descriptor}", NULL}},')
            stubs.append(f"  (void*)mln_jni_{site.name},")
        return (
            HEADER
            + "// The JNI half of each C function and upcall the Kotlin binding uses. Every\n"
            + "// argument is a primitive; mln_jni.h defines the casts and mln_jni.c the rest.\n"
            + '#include "mln_jni.h"\n\n'
            + "#include <maplibre_native_c.h>\n"
            + "#include <maplibre_native_c/plugin.h>\n\n"
            + "\n\n".join(functions)
            + "\n\nconst JNINativeMethod mln_jni_methods[] = {\n"
            + "\n".join(methods)
            + "\n};\nconst size_t mln_jni_method_count =\n"
            + "  sizeof mln_jni_methods / sizeof mln_jni_methods[0];\n\n"
            + "mln_jni_upcall mln_jni_upcalls[] = {\n"
            + "\n".join(entries)
            + "\n};\n\n"
            + "\n\n".join(upcalls)
            + "\n\nvoid* const mln_jni_upcall_stubs[] = {\n"
            + "\n".join(stubs)
            + "\n};\nconst size_t mln_jni_upcall_count =\n"
            + "  sizeof mln_jni_upcall_stubs / sizeof mln_jni_upcall_stubs[0];\n"
        )

    def c_declaration(self, ctype, local):
        spelling = ctype.spelling
        return (
            f"{spelling} {local}"
            if not spelling.endswith("*")
            else f"{spelling}{local}"
        )
