"""Emit the Zig public API from resolved values, owners and callback protocols."""

from __future__ import annotations

import re

from tools.bindgen.compiler import compile_api
from tools.bindgen.model import Api, CType, Function, ModelError, Record
from tools.bindgen.semantic import BoundApi

SCALARS = {
    "int8_t": "i8",
    "int16_t": "i16",
    "uint16_t": "u16",
    "intptr_t": "isize",
    "ptrdiff_t": "isize",
    "uintptr_t": "usize",
    "double": "f64",
    "float": "f32",
    "bool": "bool",
    "_Bool": "bool",
    "uint32_t": "u32",
    "uint8_t": "u8",
    "uint64_t": "u64",
    "int32_t": "i32",
    "int64_t": "i64",
    "size_t": "usize",
}


def identifier(value: str) -> str:
    return '@"' + value + '"'


def pascal(value: str) -> str:
    return "".join(word[:1].upper() + word[1:] for word in value.split("_"))


def camel(value: str) -> str:
    result = pascal(value)
    return result[:1].lower() + result[1:]


def native(type_: CType) -> str:
    return type_.declaration or type_.spelling.removeprefix("const ")


def failure(decl: Function | Record, reason: str) -> ModelError:
    return ModelError([f"{decl.location}: Zig: {decl.name}: {reason}"])


# A public function whose native call reports a diagnostic takes an optional
# Diagnostic last, and any error it returns records its details there.
DIAGNOSTIC_PARAMETER = "diagnostic: ?*diagnostics.Diagnostic"
DIAGNOSTIC_PREAMBLE = [
    "status.begin(diagnostic);",
    "errdefer |err| status.fail(diagnostic, err);",
]


def status_call(
    function: Function, arguments: list[str], diagnostic: str = "diagnostic"
) -> str:
    """Calls a status-returning C function through the diagnostic runtime."""
    if not function.diagnostic:
        raise failure(function, "status result requires a diagnostic parameter")
    tuple_ = ".{ " + ", ".join(arguments) + " }" if arguments else ".{}"
    return f"try status.call(c.{function.name}, {tuple_}, {diagnostic});"


def expose_parameter_names(plan, code):
    """Keep generated temporaries private while naming parameters from the header."""
    marker = f"pub fn {camel(plan.name.removeprefix('mln_'))}("
    start = code.index(marker) + len(marker)
    end = code.index("\n", start)
    signature = code[start:end]
    body = code[end:]
    aliases = []
    used = {"allocator", "diagnostic"}
    for index, parameter in enumerate(plan.function.parameters):
        internal = f"binding_arg_{index}"
        if not re.search(rf"\b{internal}:", signature):
            continue
        public = parameter.name
        if public == internal:
            continue
        if public in used or re.search(rf"\b{re.escape(public)}\b", body):
            public += "_input"
        while public in used:
            public += "_input"
        used.add(public)
        signature = signature.replace(internal + ":", identifier(public) + ":", 1)
        aliases.append(f"    const {internal} = {identifier(public)};")
    return (
        code[:start] + signature + ("\n" + "\n".join(aliases) if aliases else "") + body
    )


def lower(
    api: Api | BoundApi,
) -> tuple[list[str], list[str], dict[str, str], dict[str, list[str]]]:
    chunks, generated, unsupported = [], [], {}
    bound = compile_api(api)
    api = bound.source
    from .zig_values import Values

    value_types = Values(bound)
    for value in bound.public_values.values():
        if value.kind == "enum":
            value_types.add(value)
    unsupported.update(
        {name: "\n".join(reasons) for name, reasons in bound.unsupported.items()}
    )
    for plan in bound.operations:
        function = plan.function
        previous = dict(value_types.used)
        try:
            from .zig_operations import operation as lower_operation

            code, _, _, _ = lower_operation(plan, api, value_types)
            chunks.append(expose_parameter_names(plan, code))
            generated.append(function.name)
        except ModelError as error:
            value_types.used = previous
            unsupported[function.name] = str(error)
    return (
        [
            value_types.render(),
            *chunks,
        ],
        generated,
        unsupported,
        {},
    )


def generate(api: Api | BoundApi) -> dict[str, str]:
    chunks, _, _, _ = lower(api)
    prefix = """// Code generated by tools/bindgen; DO NOT EDIT.
const std = @import("std");
const c = @import("c.zig").raw;
const call = @import("call.zig");
const callback = @import("callback.zig");
const completion = @import("completion.zig");
const diagnostics = @import("diagnostics.zig");
const marshal = @import("marshal.zig");
const owner = @import("owner.zig");
const status = @import("status.zig");

pub const OwnedValue = marshal.OwnedValue;

"""
    bound = compile_api(api)
    owners = []
    for handle in bound.handles.values():
        if any(name not in bound.operations_by_name for name in handle.finalize):
            continue
        calls = []
        for finalizer in handle.finalize:
            function = bound.operations_by_name[finalizer].function
            calls.append(
                f"c.{finalizer}(raw);"
                if function.return_type.kind == "void"
                else status_call(function, ["raw"], "null")
            )
        owners.append(
            f'pub const {pascal(handle.native.removeprefix("mln_"))} = owner.Handle("{handle.native}", struct {{ fn dispose(raw: u64) status.Error!void {{ {" ".join(calls)} }} }}.dispose);'
        )
    # The generated surface is the package root, next to the runtime types it
    # exposes, so the package needs no file of re-exports.
    docs = (
        "//! Header-generated API. Release owners explicitly or call deinit.\n"
        "//! OwnedValue snapshots and futures retain their allocator until deinit.\n"
        "//! Each has unique ownership: move it rather than copy it, since deinit on two\n"
        "//! copies releases the native value twice.\n"
        "//! Callback contexts stay valid until release_context runs after native retirement.\n"
        "//! GPU descriptors are borrowed only inside the scoped getter callback.\n"
    )
    runtime = """
/// This whole API under one name, for callers that walk its declarations.
pub const generated = @This();
pub const Future = completion.Future;
pub const CommandCompletion = completion.CommandCompletion;
pub const Error = status.Error;
pub const BindingError = status.BindingError;
pub const Diagnostic = diagnostics.Diagnostic;
pub const validateAbiVersion = status.validateAbiVersion;

"""
    source = docs + prefix + runtime + "\n".join([*owners, *chunks])
    return {"maplibre_native_ffi.zig": source}


def coverage(api: Api | BoundApi) -> dict:
    _, generated, unsupported, _ = lower(api)
    return {"generated": generated, "unsupported": unsupported}
